### ISSUE TITLE
Acc > Enable to label the dropdown component

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluent-ui-react#1003]
### Problem description
when dropdown shows up the results, that results has parent element with aria-role list
Would be great if this list is labelled. 

### Proposed solution
from @silviuavram :
ideally it should be a prop in Dropdown that accepts a shorthand for a future DropdownLabel. Because this way we can leverage Downshift getLabelProps() to label the list and input text.

### MVP
[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

**Comment by silviuaavram** [comment]
Closed as fixed https://github.com/stardust-ui/react/pull/1446
