### ISSUE TITLE
Basic menu as toolbar

### ISSUE THREAD

**Issue by parasjindal** [microsoft/fluent-ui-react#1007]
## Feature Request
Basic menu that is similar to Menu as a Toolbar usage

### Problem description
Whenever an item is clicked, it set it's state to active. Due to which I am unable to use them as normal buttons. If I set **currentActiveIndex = -1** then I am unable to open submenu. 

### Proposed solution
A prop can be passed which makes them behave as a button and whenever it is clicked, it's active state is removed.

**Comment by jurokapsiar** [comment]
Toolbar component is now available for this use case.
