### ISSUE TITLE
Need svg icons used in share tray panel on calling screen

### ISSUE THREAD

**Issue by musingh1** [microsoft/fluent-ui-react#1012]
## Feature Request

We need a couple of icons that are needed for share tray in the calling screen - 
![image](https://user-images.githubusercontent.com/22622723/53766787-a1a61000-3e88-11e9-82ed-d25aec096f4a.png)

### Problem description
The corresponding icons in the teams app are
icons-call-control-present.html
icons-powerpoint-color.html

### Proposed solution
We need to port these icons to stardust

### MVP
[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

**Comment by notandrew** [comment]
These are now in the build
