### ISSUE TITLE
SVG Icons

### ISSUE THREAD

**Issue by 96andrei** [microsoft/fluent-ui-react#1022]
## Feature Request
Hi,
We need a generic "spinner" - like SVG icon, something similar to "circle notch" from Font Awesome. We need this for a Button and using the Loader component breaks the styling / doesn't look good.

It would be great to have the option to insert our own SVGs into the Icon component.

**Comment by codepretty** [comment]
Do you mean the spinner/loading animation like in Teams today?

https://codepen.io/teams-ux-engineers/pen/1c068c6d136debb86a7164054a2c21bf

**Comment by 96andrei** [comment]
This one:
![spinner](https://user-images.githubusercontent.com/12568550/53986795-6d984c80-411f-11e9-9484-4e24f8f6928a.jpg)

**Comment by ghost** [comment]
What is the status of that one?

**Comment by layershifter** [comment]
We already have `loading` prop on `Button`: https://stardust-ui.github.io/react/components/button/definition#states-loading

I think that this can be closed. @jurokapsiar ?

**Comment by levithomason** [comment]
Use Loading Button as @layershifter has pointed out.  For generic loading case, use the Loader.
