### ISSUE TITLE
Grid: Accessibility: Keyboard navigation is incorrect on the last row

### ISSUE THREAD

**Issue by johannao76** [microsoft/fluent-ui-react#1034]
### Steps
- Open the provided sample (link below)
- Arrow down to the first item in the last row
- Arrow down again

### Expected Result
- Nothing should happen (or we should go back to the first item in the first row

### Actual Result
- Taken to the item to the right of the currently focused item

### Version
0.23.0

### Testcase
https://codesandbox.io/s/9y5qylv8o4

**Comment by sophieH29** [comment]
Keyboard navigation was changed to non-circular https://github.com/stardust-ui/react/pull/1098/
