### ISSUE TITLE
[Drop down] Need a way to customize selected item highlight

### ISSUE THREAD

**Issue by vadimvar** [microsoft/fluent-ui-react#1045]
## Bug Report
Need a way to customize selection of drop down control, so, we may compose it from header and sub-header parts as shown on picture below. 

![image](https://user-images.githubusercontent.com/45048721/54165572-873adc00-441e-11e9-8500-60beeb9a34cc.png)

### Steps
A clear and concise description of steps to reproduce the problem.

### Expected Result
The result that you expected.

### Actual Result
The actual result that happened 💣

### Version
0.21.0

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
Please use a correct tracker when you're creating issues:
![image](https://user-images.githubusercontent.com/14183168/54428347-e9992280-4725-11e9-97b0-5fbbeae19bb4.png)
And fill descriptions fully, it will help us to provide solutions and fixes faster 👍 

---

If you mean case with multiple selection, it's already possible: https://stardust-ui.github.io/react/components/dropdown#usage-render. I also prepared an example: https://codesandbox.io/s/xo6nk5y29w

If you mean case with single selection, it's possible with `itemToString` and `searchInput`, too: https://codesandbox.io/s/jp049rw153
However, it's much more tricky, but it's satisfies your needs and it's possible to customize it.

**Comment by layershifter** [comment]
Closing for housekeeping, please let us know if you need additional help 👍
