### ISSUE TITLE
Add support for column count in Flex component

### ISSUE THREAD

**Issue by musingh1** [microsoft/fluent-ui-react#1060]
## Feature Request
We have a requirement to show a dynamic list of check-boxes in a questionnaire form in two columns in the column-first way. The containing container has a max-width, and the height is determined by the number of items
![image](https://user-images.githubusercontent.com/22622723/54333982-b3528a80-45e1-11e9-8fe5-8e8994038529.png)

### Problem description
We need a way to render a set of items in a column-first way inside a container.

### Proposed solution
In the angular app, we are using column-count: 2 css property on the container with block display (https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_column-count). Since this is a layout requirement, can we add such support in the Flex component.

### MVP
[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
https://stardust-ui.github.io/react/components/grid#variations-columns
I think that it's use case for `Grid` component. Does it satisfy your needs?

**Comment by layershifter** [comment]
Closing for housekeeping, let's us know if you will have issues 👍
