### ISSUE TITLE
[RFC]: `Alert` | `Banner ` |  `Message` component

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#1061]
## Problem description

We need a component that can offer users a visual representation similar to an alert regarding different states of the application for specific scenarios:
- there's a connectivity issue in the app
- some users are not available to chat
- an item needs extra visual attention because it might be urgent, etc

## Proposed solutions

Other libraries tackle this problem by introducing a dedicated component. You can see some examples in the next section (**Other Libraries Screenshots**, after **Proposed solutions**)

### Name:
1. Alert (used by most librariies) - **front runner** 
2. Message (used by [SUIR](https://react.semantic-ui.com/collections/message/))
3. Banner (used by [Attlassian](https://atlaskit.atlassian.com/packages/core/banner))

### v1:
```typescript
export interface AlertProps {

  /** Button shorthand for the action slot. */
  action?: ShorthandValue<ButtonProps>

  /** Generic animation property for applying different theme animations. */
  animation?: AnimationProp

  /** Controls Alert's relation to neighboring items. */
  attached?: boolean | 'top' | 'bottom'

  /** Content for childrenApi. */
  children?: TChildren

  /** Shorthand for primary content. */
  content?: TContent
 
  /** An alert may be formatted to display a danger message. */
  danger?: boolean

  /** An alert may be formatted to display information. */
  info?: boolean

  /** An alert may be formatted to display a successful message. */
  success?: boolean

  /** An alert may be formatted to display warning message. */
  warning?: boolean
}
```

### v2 (Auto Controlled Component):
```typescript
interface AlertPropsV2 extends AlertProps {
  /** The title of the alert **/
  header?: string

  /** An alert may be formatted to display an error or negative message. */
  error?: boolean
  negative?: boolean // EXPERIMENTAL - not sure we will add both

  /** An alert may be formatted to display a positive message. */
  positive?: boolean // EXPERIMENTAL - synonym for success  not sure we will add it
  
  /** Defines whether Alert is displayed. */
  open?: boolean

  /** Event for request to change 'open' value. */
  onOpenChange?: ComponentEventHandler<PopupProps>

  /** EXPERIMENTAL - some Alerts might need different style for all types/intents */
  appearance?: 'basic' | 'card'
}
```

### [Bootstrap](https://getbootstrap.com/docs/4.2/components/alerts/) - Alert:

- class names for describing the emphasis:`primary`, `secondary`, `success`, `danger`, `warning`, `info`, `light`, `dark` preceded by `alert-` suffix
- can have `header` and `content` (similar to Stardust's [`Header` with description](https://stardust-ui.github.io/react/components/header#variations-description))
- close button

### [Reactstrap](https://reactstrap.github.io/components/alerts/) - Alert:

- color:`primary`, `secondary`, `success`, `danger`, `warning`, `info`, `light`, `dark`
- can have `header` and `content` (similar to Stardust's [`Header` with description](https://stardust-ui.github.io/react/components/header#variations-description))
- `isOpen`: boolean prop for visibility state
- `toggle`: handler for controlling visibility
- `fade`: boolean prop for fade animation
- close button
- visually the same as Bootstrap

### [Ant Design](https://ant.design/components/alert/) - Alert:

Property | Description | Type | Default
-- | -- | -- | --
afterClose | Called when close animation is finished | () => void | -
banner | Whether to show as banner | boolean | false
closable | Whether Alert can be closed | boolean | -
closeText | Close text to show | string\|ReactNode | -
description | Additional content of Alert | string\|ReactNode | -
icon | Custom icon, effective when showIcon is true | ReactNode | -
message | Content of Alert | string\|ReactNode | -
showIcon | Whether to show icon | boolean | false, in bannermode default is true
type | Type of Alert styles, options: success, info, warning, error | string | info, in bannermode default is warning
onClose | Callback when Alert is closed | (e: MouseEvent) => void | -

### [Evergreen](https://evergreen.segment.com/components/alert/) - Alert:

Property | Type | Descriptio
-- | -- | --
child | renunion | The content of the alert. When a string is passed it is wrapped in a `<Text size={400} />` component.
intent | enum = 'none', 'success', 'warning', 'danger' | The intent of the alert.
title | node | The title of the alert.
hasTrim | bool = true | When true, show a border on the left matching the type.
hasIcon | bool = true | When true, show a icon on the left matching the type,
isRemoveable | bool = false | When true, show a remove icon button.
onRemove | func | Function called when the remove button is clicked.
appearance | enum = 'default', 'card' | The appearance of the alert.

### [VuetifyJs](https://vuetifyjs.com/en/components/alerts) - Alert:

![Screenshot 2019-03-14 at 20 32 32](https://user-images.githubusercontent.com/5442794/54386023-55cd4500-4698-11e9-988c-bbd97ad7fa6c.png)

### [Semantic-UI React](https://react.semantic-ui.com/collections/message/) - Message:

Name |	Type |	Description
-- | -- | --
as | {custom}	| An element type to render as (string or function).
attached | {bool, enum}	| A message can be formatted to attach itself to other content, Enums: 'bottom', 'top'
children | {node}	| Primary content.
className | {string}	 | Additional classes.
color | {enum}	 | A message can be formatted to be different colors. Enums: 'red', 'orange', 'yellow', 'olive', 'green', 'teal', 'blue', 'violet', 'purple', 'pink', 'brown', 'grey', 'black'
compact | {bool}	| A message can only take up the width of its content.
content | {custom}	 | Shorthand for primary content.
error | {bool}	| A message may be formatted to display a negative message. Same as `negative`.
floating | {bool}	| A message can float above content that it is related to.
header | {custom}	| Shorthand for MessageHeader.
hidden | {bool}	 | A message can be hidden.
icon | {custom, bool}	| A message can contain an icon.
info |{bool}	 | A message may be formatted to display information.
list |{custom}	 |Array shorthand items for the MessageList. Mutually exclusive with children.
negative | {bool}	| A message may be formatted to display a negative message. Same as `error`.
onDismiss | {func}	| A message that the user can choose to hide. Called when the user clicks the "x" icon. This also adds the "x" icon.
positive | {bool}	| A message may be formatted to display a positive message. Same as `success`.
size | {enum}	| A message can have different sizes
success | {bool}	| A message may be formatted to display a positive message. Same as `positive`.
visible | {bool} |	A message can be set to visible to force itself to be shown.
warning |{bool}	|A message may be formatted to display warning messages.

### [Fabric](https://developer.microsoft.com/en-us/fabric#/components/messagebar#Variants) - MessageBar:

![Screenshot 2019-03-14 at 20 47 14](https://user-images.githubusercontent.com/5442794/54386935-70082280-469a-11e9-8795-97f1ce46fe33.png)

### [Material UI](https://material-ui.com/demos/snackbars/) - Snackbar:

Name | Value | Description
-- | -- | --
action | node  | The action to display.
anchorOrigin | enum | The anchor of the Snackbar: { horizontal: enum: 'left' \| 'center' \| 'right', vertical: enum: 'top' \| 'bottom'} 
autoHideDuration | number | The number of milliseconds to wait before automatically calling the onClose function. onClose should then set the state of the open prop to hide the Snackbar. This behavior is disabled by default with the null value.
ClickAwayListenerProps | object |   | Properties applied to the ClickAwayListener element.
ContentProps | object |   | Properties applied to the SnackbarContent element.
message | node |   | The message to display.
onClose | func | Callback fired when the component requests to be closed. Typically onClose is used to set state in the parent component, which is used to control the Snackbar open prop. 
open | bool |   | If true, Snackbar is open.

### [Bootstrap](https://getbootstrap.com/docs/4.2/components/alerts/) and [Reactstrap](https://reactstrap.github.io/components/alerts/) - Alert:

![Screenshot 2019-03-14 at 19 58 06](https://user-images.githubusercontent.com/5442794/54384400-6da2ca00-4694-11e9-9ac1-ad2f084b5553.png)

### [Ant Design](https://ant.design/components/alert/) - Alert:

![Screenshot 2019-03-14 at 20 18 19](https://user-images.githubusercontent.com/5442794/54385201-5ebd1700-4696-11e9-9164-b1d4076f2891.png)

### [Evergreen](https://evergreen.segment.com/components/alert/) - Alert:

![Screenshot 2019-03-14 at 20 23 25](https://user-images.githubusercontent.com/5442794/54385503-118d7500-4697-11e9-8ebb-7dfb54f70e00.png)
![Screenshot 2019-03-14 at 20 23 36](https://user-images.githubusercontent.com/5442794/54385512-13efcf00-4697-11e9-8ec2-e3dedc3290c6.png)

### [VuetifyJs](https://vuetifyjs.com/en/components/alerts) - Alert:

![Screenshot 2019-03-14 at 20 30 01](https://user-images.githubusercontent.com/5442794/54385938-1dc60200-4698-11e9-8a70-b67b508eb1b1.png)

### [Semantic-UI React](https://react.semantic-ui.com/collections/message/) - Message:
![Screenshot 2019-03-14 at 20 34 09](https://user-images.githubusercontent.com/5442794/54386129-93ca6900-4698-11e9-8ee2-12b33f8d78aa.png)
![Screenshot 2019-03-14 at 20 34 16](https://user-images.githubusercontent.com/5442794/54386136-962cc300-4698-11e9-8077-0136d4185e51.png)
![Screenshot 2019-03-14 at 20 34 24](https://user-images.githubusercontent.com/5442794/54386139-975df000-4698-11e9-99fa-6f077db8a489.png)

### [Fabric](https://developer.microsoft.com/en-us/fabric#/components/messagebar#Variants) - MessageBar:

![Screenshot 2019-03-14 at 20 45 58](https://user-images.githubusercontent.com/5442794/54386861-3f27ed80-469a-11e9-8170-b8296f30cf60.png)

### [Material UI](https://material-ui.com/demos/snackbars/) - Snackbar:
![Screenshot 2019-03-15 at 00 57 36](https://user-images.githubusercontent.com/5442794/54399146-647a2300-46bd-11e9-81ea-b5fc132b1df0.png)

**Comment by layershifter** [comment]
### Naming

I propose to go with `Alert,` it has the similar name in ARIA patterns: https://www.w3.org/TR/wai-aria-practices/examples/alert/alert.html

### `type` vs separate props
We can not use `type`, it's an HTML attribute. So, let's go with separate props. We had a long discussion before about the color palette, so I propose to simply use its defintions: `danger`, `info`, `success`, `warning`.

### Slots

Actually, I see that we have everywhere `description`/`content`, `header`, `statusIcon`/`stateIcon` and `closeIcon`.

![image](https://user-images.githubusercontent.com/14183168/54427649-c53c4680-4723-11e9-9a5e-a0f46ce99bbe.png)

![image](https://user-images.githubusercontent.com/14183168/54427679-d7b68000-4723-11e9-956f-aa85d2fc7128.png)

---

## Conclusions

I vote for the minimal implementation:
- `danger`, `info`, `success`, `warning` to customize, defaults to `info`. SUI has [`basic`](https://semantic-ui.com/collections/message.html#message), but I propose to omit it
- `content`. Prefer instead of `description`, it doesn't make any sense to call it description in the case below:
![image](https://user-images.githubusercontent.com/14183168/54427867-60cdb700-4724-11e9-8525-2f57e9cbc13b.png)
- `closeIcon` and `onClose`: we will have the similar thing in `Dialog` component, so let's align
- skip `header` and `statusIcon`/`icon` for initial implementation

**Comment by bmdalex** [comment]
great feedback, thanks @layershifter 👍

**Comment by bmdalex** [comment]
still not sure what makes more sense.. `danger` vs `error` vs both (since we already have `success` and the natural opposite is `failure` or `error` rather than `danger`)

but we will start with `success`, `danger`, `info`, `warning` and iterate from there. 1st PR soon 😃
