### ISSUE TITLE
Perf: FocusZone is leaking memory

### ISSUE THREAD

**Issue by johannao76** [microsoft/fluent-ui-react#1067]
### Steps
When running our code in Teams in stand-alone mode (local dev), we are noticing detached DOM nodes accruing to 62K retained size in the chrome dev tools

![image](https://user-images.githubusercontent.com/11838969/54507573-308e4000-48ff-11e9-8b39-768ed0140633.png)

### Expected Result
No leak

### Actual Result
Leaking memory

### Version
0.23.1

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by kuzhelov** [comment]
this issue wasn't reproduced for v0.24 - closing for now..
