### ISSUE TITLE
Alert component follow-up

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#1077]
## Alert component follow-up

`Alert` component was created in #1063 there are a few things we need to follow up on:

- [ ] make `Alert` an auto controlled component (https://github.com/stardust-ui/react/pull/1063#discussion_r266504497)
- [ ] adapt v2 API:
  - header (https://github.com/stardust-ui/react/pull/1063#discussion_r266394494)
  - other intent props (`error`, `negative`)
```typescript
interface AlertPropsV2 extends AlertProps {
  /** The title of the alert **/
  header?: string

  /** An alert may be formatted to display an error or negative message. */
  error?: boolean
  negative?: boolean // EXPERIMENTAL - not sure we will add both

  /** An alert may be formatted to display a positive message. */
  positive?: boolean // EXPERIMENTAL - synonym for success  not sure we will add it
  
  /** Defines whether Alert is displayed. */
  open?: boolean

  /** Event for request to change 'open' value. */
  onOpenChange?: ComponentEventHandler<PopupProps>

  /** EXPERIMENTAL - some Alerts might need different style for all types/intents */
  appearance?: 'basic' | 'card'
}
```
- [ ] implement other themes
- [ ] add visual tests in other themes
- [ ] remove display flex so that `children` are displayed on different lines (see: https://codesandbox.io/s/xr52j56xxz?module=/example.js) suggested by @layershifter

**Comment by jurokapsiar** [comment]
this is not required anymore.
