### ISSUE TITLE
yarn generate fails

### ISSUE THREAD

**Issue by stuartlong** [microsoft/fluent-ui-react#1084]
## Bug Report
`yarn generate:component MyComponent` fails:
 ```ps
E:\stardust-ui\react [master ≡]> yarn generate:component
yarn run v1.5.1
error An unexpected error occurred: "Command \"generate:component\" not found.".
info If you think this is a bug, please open a bug report with the information provided in "E:\\stardust-ui\\react\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Steps
I followed the [setup-local-development.md](https://github.com/stardust-ui/react/blob/master/.github/setup-local-development.md#contributorsl) and the [add-a-feature.md](https://github.com/stardust-ui/react/blob/master/.github/add-a-feature.md), but when I got to the `yarn generate` step, the command failed.

### Version
0.23.1

**Comment by miroslavstastny** [comment]
This was removed in #819
We should update doc as well @layershifter
