### ISSUE TITLE
Chevron-up and triangle-up icons are missing

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#1085]
Need chevron-up or triangle-up icon to implement less button for share-tray preview listing
![image](https://user-images.githubusercontent.com/47372422/54729001-2c039a80-4b3e-11e9-9438-78526cc9bd51.png)
![image](https://user-images.githubusercontent.com/47372422/54729034-5a817580-4b3e-11e9-84ba-9b1fcd87fb7a.png)
![image](https://user-images.githubusercontent.com/47372422/54729043-69682800-4b3e-11e9-96a5-4aeb9fdb110f.png)

**Comment by hughreeling** [comment]
https://github.com/stardust-ui/react/pull/585

**Comment by vini-gupta** [comment]
We can export these icons from the stardust non-exported list of icons
triangle-down => triangledownsmall
chevron-down => chevrondown
