### ISSUE TITLE
Icons for enable private viewing

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#1095]
### Problem description
Need support for the following icon to show if private viewing is enabled.
![image](https://user-images.githubusercontent.com/47372422/54859443-79ad0e00-4cca-11e9-82e9-5e86bfea5a10.png)

**Comment by alinais** [comment]
#1194

**Comment by hughreeling** [comment]
https://github.com/stardust-ui/react/pull/585
