### ISSUE TITLE
Provider requires a theme but Docs suggest not supplying one

### ISSUE THREAD

**Issue by stuartlong** [microsoft/fluent-ui-react#1110]
## Bug Report
The docs on theme indicate that by default a theme does not have to be provided:
![image](https://user-images.githubusercontent.com/2327459/55035211-897f6780-4fd4-11e9-9bc6-c007c55c6f7a.png)

However, theme is a required input for the `Provider` component.
![image](https://user-images.githubusercontent.com/2327459/55035417-293cf580-4fd5-11e9-9714-1c0b383746f1.png)

### Version
0.25.0

### Testcase
https://codesandbox.io/s/mmxpnxzmyp?fontsize=14

**Comment by kuzhelov** [comment]
@stuartlong, thanks a lot for reporting this issue! Currently 'patch' fix is introduced for this issue, but we are working on improving overall docs functionality so that, amongst other things, it won't be possible to publish non-working code examples ✅
