### ISSUE TITLE
[IE11] Dropdown: 'open dropdown' arrow outside the component

### ISSUE THREAD

**Issue by kamilakorzec** [microsoft/fluent-ui-react#1139]
### Steps
Open dropdown component in IE11

### Expected Result
'Open dropdown' arrow as a part of the component
![image](https://user-images.githubusercontent.com/11797698/55319233-b8825700-5474-11e9-95a2-bbee000ea80d.png)

### Actual Result
'Open dropdown' arrow rendered below
![image](https://user-images.githubusercontent.com/11797698/55319194-a6081d80-5474-11e9-9546-b5d560f70781.png)

### Version
0.25.1

### Testcase
Repro on https://stardust-ui.github.io/react/components/dropdown in IE11

**Comment by jurokapsiar** [comment]
does not repro in 0.35, clsing
