### ISSUE TITLE
[IE11] Dropdown: opening and closing menu leaves an empty white div rendered

### ISSUE THREAD

**Issue by kamilakorzec** [microsoft/fluent-ui-react#1140]
### Steps
1. Open  https://stardust-ui.github.io/react/ in IE11
2. Select 'Dropdown' component
3. Open and close any of the sample dropdowns

### Expected Result
Dropdown closes without leaving any artifacts

### Actual Result
After closing a high, empty white div is left rendered, obscuring the rest of the page:
![image](https://user-images.githubusercontent.com/11797698/55319669-b10f7d80-5475-11e9-981d-2908617a308c.png)

### Version
0.25.1

### Testcase
Reproducible in https://stardust-ui.github.io/react/components/dropdown

**Comment by jurokapsiar** [comment]
does not repro in 0.35, closing the issue.
