### ISSUE TITLE
Dropdown accessibility broken when highlightFirstItemOnOpen prop is set

### ISSUE THREAD

**Issue by kohlikohl** [microsoft/fluent-ui-react#1149]
## Bug Report

Focus gets stuck inside the input field of the `<Dropdown>` component when `highlightFirstItemOnOpen` prop is set.

### Steps
See this [codepen](https://codesandbox.io/s/7245lw8l50) for repro.
* Press tab to navigate to buttons
* ENTER to open the popup
* When `highlightFirstItemOnOpen` is set pressing TAB does not switch to the button in the popup

### Expected Result
* Pressing TAB when focus is in the input field should switch focus to other elements in the popup.

### Version
0.25.1

**Comment by silviuaavram** [comment]
fixed
