### ISSUE TITLE
Menu with toolbarBehavior not keyboard accessible

### ISSUE THREAD

**Issue by kohlikohl** [microsoft/fluent-ui-react#1155]
### Steps
When using a menu as a toolbar with `toolbarBehavior` and `toolbarButtonBehavior`, where individual items open a Popup, pressing ENTER to open the Popup does not work.

https://codesandbox.io/s/r5p9p1487n

### Version
0.25.1

**Comment by jurokapsiar** [comment]
To modify the render tree (to add Popup),  please follow "Customizing render tree"in https://stardust-ui.github.io/react/shorthand-props

The example provided above is not valid as it renders two Menu.Items. Correct usage: https://codesandbox.io/s/jjwvq0969w

**Comment by dslane** [comment]
codesandbox has been updated, and the issue still persists. Please re-open this

**Comment by jurokapsiar** [comment]
There is indeed an issue if the popup state is controlled from outside. https://codesandbox.io/s/71xp67v0

**Comment by dslane** [comment]
Original sandbox has been updated with more descriptive console logs and multiple popups

https://codesandbox.io/s/r5p9p1487n

**Comment by kuzhelov** [comment]
@kohlikohl, @dslane, thanks a lot for providing the details around the issue - we are working on it
