### ISSUE TITLE
Grid component ability to trap focus for child elements

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#1171]
## Feature Request
Grid component property to access reference to child contents for actions like setting focus to nth child element etc.

**Comment by sophieH29** [comment]
Hi @vini-gupta!
It is possible to get items' refs since you're rendering them and can gather their refs.

```jsx
<Grid items={renderItems()} .../>
....
renderItems() {
    // array of grid items refs
    this.itemRefs = []

    return _.map(items, (item, index) => {
      const itemProps = {} as any
        const ref = React.createRef()

        this.itemRefs[index] = ref

     return <SomeItemElement ref={ref}>
    })
  }
}
```

And then if you need to focus one of the grid items by index
```jsx
 focusGridItemByIndex(index: number) {
    this.itemRefs[index] && this.itemRefs[index].current.focus()
}
```

Let us know if it resolves your problem. Meanwhile, I close this issue.
