### ISSUE TITLE
Confim close button implementation for popup

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#1173]
### Problem description
Please confirm if this approach is correct for adding close button for popups
https://codesandbox.io/s/p914zrr73x

**Comment by alinais** [comment]
@vini-gupta please provide some specs/ redlines for all the theming and approval from accessibility team

**Comment by hughreeling** [comment]
Dialog or popup?  Please provide more information.

**Comment by vini-gupta** [comment]
This requirement is for popup. @kuzhelov, @mnajdova @alinais, can you please confirm if the following approach should be used to add support for close button in popups.

`interface IScreenSharingButtonState {
  open: boolean;
}

export class ScreenSharingButton extends React.PureComponent<
  {},
  IScreenSharingButtonState
> {
  public state = {
    open: false
  };
  // tslint:disable-next-line:max-func-body-length
  public render() {
    return (
      <Flex>
        <Popup
          open={this.state.open}
          onOpenChange={this.handleOpenChange}
          primary
          pointing
          content={{
            content: (
              <>
                <Flex
                  column
                  gap="gap.smaller"
                  // tslint:disable-next-line:noStylesWithStardust
                >
                  <Flex hAlign="end" vAlign="start">
                    <Button
                      text
                      iconOnly
                      icon="close"
                      onClick={this.handleOpenChange}
                    />
                  </Flex>
                  <Flex>
                   <Text content="Popup with close button"/>
                  </Flex>
                </Flex>
              </>
            )
          }}
          trigger={
            <Button
              size="big"
              icon="call-control-present-new"
              circular
              primary
              onClick={this.handleOpenChange}
            />
          }
          position="below"
          align="end"
        />
      </Flex>
    );
  }
  private handleOpenChange = () => {
    this.setState({
      open: !this.state.open
    });
  };
}
`

**Comment by vini-gupta** [comment]
This request is for popup. @kuzhelov , @mnajdova, @alinais, can you please confirm if the following approach for handling popup close action on button click is the acceptable.
https://codesandbox.io/s/p914zrr73x

**Comment by vini-gupta** [comment]
awaiting confirmation on the above-mentioned approach.
@hughreeling @alinais @kuzhelov @mnajdova

**Comment by vini-gupta** [comment]
+ @jurokapsiar to review this example from accessibility perspective.
https://codesandbox.io/s/p914zrr73x

**Comment by pkumarie2011** [comment]
@vini-gupta Kindly explain why this is required? In other words where this would be used (MW Chat/MW Meeting)?

**Comment by codepretty** [comment]
Having an optional 'x' close icon in the top, right corner should be handled through a prop on the popup component.

**Comment by pkumarie2011** [comment]
@vini-gupta @codepretty Do we know where it would be used in MW Meeting? If we don't know that, it would be deprioritized.

**Comment by vini-gupta** [comment]
It is required for screen share dialog from chat as shown in the screenshot below: 
@kumar-microsoft  Please let me know if you need any further information.

**Comment by vini-gupta** [comment]
Hi @alinais, @codepretty, @hughreeling , @kumar-microsoft, any update in which version of Stardust upgrade this close button will be available as a prop in Popup component?

**Comment by pkumarie2011** [comment]
@jurokapsiar Can you reply here?

**Comment by jurokapsiar** [comment]
the popup example page was extended with an example of popup with close button in https://github.com/stardust-ui/react/pull/1667/files

There was no change directly in the library, other than the documentation.

**Comment by jurokapsiar** [comment]
this has been resolved
