### ISSUE TITLE
Icon for closing share tray

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#1196]
## Feature Request
We need icon for closing share tray
### Problem description
We need 3 icons for share tray
1.  open share-tray: we have one icon named 'call-control-present-new' for this.
2. close share-tray: this is **missing**
3. stop presenting: we have one icon named 'call-control-stop-presenting-new' for this

![image](https://user-images.githubusercontent.com/47372422/55832417-61aafc00-5aca-11e9-9c44-20d3d625b7b8.png)

**Comment by vini-gupta** [comment]
@musingh1 @alinais

**Comment by vini-gupta** [comment]
@alinais we need this icon when the share tray is open.

**Comment by hughreeling** [comment]
https://github.com/stardust-ui/react/pull/585

**Comment by vini-gupta** [comment]
#1278
