### ISSUE TITLE
Need exported classnames for Icon component

### ISSUE THREAD

**Issue by luzhon** [microsoft/fluent-ui-react#1207]
### Steps
When trying to resize an Icon svg to a custom size, I need to target the svg and could only do so with a custom selector  
...(isFileAttachIcon && {
      "& svg": { height: "2.8rem", width: "2.8rem" }
    })

### Expected Result
Expected to be able to do the following...
[`& .${icon.classNames}`]: { height: "2.8rem", width: "2.8rem" }

### Version
0.27.0

**Comment by layershifter** [comment]
Sorry, but I don't clearly understand your issue. We have `static className` on each component, so you can do `.${Icon.className}` and `.${Icon.className} svg` to access `svg` element.

You can also set custom `className`:
```jsx
<Icon className="first-icon" name="call-video" />
// document.querySelector(`.${Icon.className}.first-icon svg`)
```

---

However, I don't understand why you need this at all. `2.8rem` is `40px` which is a standard value and can be applied with `size` prop:
```jsx
<Icon name="call-video" size="largest" />
```

Can you please clarify?

**Comment by layershifter** [comment]
Closing for housekeeping, please ping us if the issue is not solved.
