### ISSUE TITLE
Closable Alert component is missing focus styles

### ISSUE THREAD

**Issue by kohlikohl** [microsoft/fluent-ui-react#1214]
## Bug Report

When focusing the "x" icon on a closable `<Alert>` component, the focus style is not visible.
This is reproducible on the stardust doc site.

### Version
0.27.0

**Comment by codepretty** [comment]
I'm working on the redlines & themeing for this component right now

**Comment by kohlikohl** [comment]
This seems to be resolved. @codepretty can you confirm and close if that's the case?

**Comment by alinais** [comment]
#1226
