### ISSUE TITLE
Theming of Dropdown component

### ISSUE THREAD

**Issue by kohlikohl** [microsoft/fluent-ui-react#1215]
## Bug Report
The dropdown component has following theming issues:

**Dark Theme**
* Results have white background and text
![image](https://user-images.githubusercontent.com/1196216/55997165-9bb50300-5c6e-11e9-8350-b9368843b48b.png)

**High Contrast Theme**
* Input field has white text on light background
* Results are shown as white text on white background
![image](https://user-images.githubusercontent.com/1196216/55997255-c7d08400-5c6e-11e9-925c-4a32b621cd45.png)

### Version
0.27 - reproducible on doc site

**Comment by codepretty** [comment]
We are picking up themeing/redlining of the Dropdown component next week

**Comment by KyleBastien** [comment]
@codepretty Any update on this? Still seeing the same bug.
