### ISSUE TITLE
Dropdown new features

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#1234]
### Problem description
We need to add few more features to the Dropdown component in order to enable different user scenarios (e.g. @mentionin scenario)

### Features:
- [x] add ability to position the items list in different positions relative to the trigger (same as `Popup`); will introduce `align` and `position` props #1312 
**needed for:** @mentionin scenario to open the `Dropdown` above the trigger

- [x] bold styles for items suggestions while filtering; will be introduced in the @mentions prototype
**needed for:** @mentionin scenario to open the `Dropdown` above the trigger

- [ ] adding new slots to the `Dropdown` items list:
**needed for:** @mentionin scenario to offer users more info to understand what a list of results is about in the Dropdown
  - header
  - footer
  - group headers? (no urgency yet)
**needed for:** @mentionin scenario to offer users more info to understand what a list of results is about in the Dropdown
**IMPORTANT**: Need to discuss implementation and accessibility requirements @silviuavram @jurokapsiar 

- [x] custom scrollbar (already tracked and will hopefully be leveraged)

**Comment by layershifter** [comment]
> adding new slots to the Dropdown items list:

It will be great if this can be implemented in the client's code via custom rendering of slot and we will not add overcomplications to Dropdown.

**Comment by bmdalex** [comment]
>> adding new slots to the Dropdown items list:

> It will be great if this can be implemented in the client's code via custom rendering of slot and we will not add overcomplications to Dropdown.

@layershifter 
Let's pair on this as I am not sure myself how it's goin go work with all the accessibility requirements..

fyi @jurokapsiar @silviuavram

**Comment by jurokapsiar** [comment]
closing, new issues can be created if header, footer or groups are needed
