### ISSUE TITLE
Need the SVG icon for the calling-nudge 

### ISSUE THREAD

**Issue by spoorthigururaj** [microsoft/fluent-ui-react#1240]
Need these Icons for placing calls to echo bot
![image](https://user-images.githubusercontent.com/3885292/56393020-f6f37200-61e7-11e9-8aab-a71cc85fcd70.png)

**Comment by alinais** [comment]
@codepretty is this covered in #1264 (the user-phone icon)?

**Comment by codepretty** [comment]
> @codepretty is this covered in #1264 (the user-phone icon)?

Yep!

**Comment by spoorthigururaj** [comment]
Excellent! thank you @codepretty
