### ISSUE TITLE
Need icons for calling screen

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#1241]
## Feature Request
We need the following icons for support calling scenarios
![image](https://user-images.githubusercontent.com/47372422/56395674-61101500-61f0-11e9-9a9f-e9446c57c86d.png)

## Tracking resolution progress
- [ ] Hold
- [ ] Transfer
- [ ] Park call
- [ ] Consult then transfer
- [ ] Start video with blur
- [x] Keypad (as `call-dialpad`) (#1271)

**Comment by vini-gupta** [comment]
@alinais @musingh1

**Comment by hughreeling** [comment]
https://github.com/stardust-ui/react/pull/585 - this PR provides an example for actions that should be taken to export existing icons to Teams theme.

**Comment by vini-gupta** [comment]
@assamad, you can export the following four icons from the not-exported list for calling-scenario
Hold => callhold
transfer => calltransfer
Start video with blur => blurbackground
keypad => calldialpad

We still need icons for the following two scenarios:
1. consult then transfer
2. call park

@kuzhelov I am closing this issue and recreating a new one just with the new icons.
