### ISSUE TITLE
Need zoom/pan support for video streams

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#1244]
## Feature Request
We need to support zoom/pan or video streams within screen sharing. Presently the zooming is supported at each individual component level but we want the entire shared screen video to have the support for zooming/panning within the screen share as shown in the gif below. 
Also we need some examples to be added to stardust website to explain how we can control zooming/panning across different components. 
### Problem description
Zoom in/out where the mouse pointer is clicked.
![zoomSS](https://user-images.githubusercontent.com/47372422/56443986-b826f000-62ab-11e9-8c29-cc476c57cfc2.gif)

**Comment by vini-gupta** [comment]
@alinais @jurokapsiar @musingh1

**Comment by kuzhelov** [comment]
this seems to be a component's behavior that is highly Teams-specific

**Comment by vini-gupta** [comment]
Filippos Zampounis confirmed this will be created as a custom component. Closing this issue for now.
