### ISSUE TITLE
Cast icon for prejoin

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#1245]
## Feature Request
Need an icon for casting in pre-join screen
### Problem description
A clear and concise description of what the problem is. Ex. I have an issue when [...]
![image](https://user-images.githubusercontent.com/47372422/56447747-085b7d80-62bf-11e9-8f8a-252399f930c1.png)

**Comment by hughreeling** [comment]
https://github.com/stardust-ui/react/pull/585

**Comment by vini-gupta** [comment]
#1278
