### ISSUE TITLE
Alignment issues with Flex

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#1249]
## Bug Report
By default Flex component is adding additional space around the child Flex components. We want to control/limit this spacing. This spacing not controlled via padding or margin on flex component.

### Expected Result
The result that you expected.
![image](https://user-images.githubusercontent.com/47372422/56556575-31913d80-654d-11e9-8ddb-48589359b5f8.png)

### Actual Result
![SpacingWithNestedFlexComponent](https://user-images.githubusercontent.com/47372422/56556700-87fe7c00-654d-11e9-8b26-340be49a1b44.jpg)

**Code:**
`<Flex column gap="gap.smaller">
          <Header
            as="h4"
                       styles={getHeaderStyles()}
                       content={isDesktopShare ? "Desktop" : "Window"}
          />
          <Flex
            accessibility={gridBehavior}
            fill
            styles={getPanelContainerStyles()}
            ref={isDesktopShare ? this.props.gridRef : null}
          ><Button
        text
        styles={getShareTrayItemContainerStyles}
        variables={getItemTypeButtonVariables}
        key={preview.id}
        onClick={this.onClick}
      >
        <Flex column>
          <ShareTrayItemPreviewImage preview={preview} />
          {previewTitle && (
            <Text
              content={previewTitle}
              truncated
              styles={getPreviewLabelStyles}
            />
          )}
        </Flex>
      </Button>
 </Flex>
</Flex>`

**where styles include**
`export const getShareTrayItemContainerStyles = (): ICSSInJSStyle => ({
  width: "calc(100% - .8rem)",
  maxWidth: "15.2rem",
  minWidth: "14rem",
  margin: "0.4rem",
  padding: "0.4rem",
  boxSizing: "border-box",
  display: "block",
  border: "0",
  ":hover": {
    cursor: "pointer",
    background: appBrand06_80alpha,
    borderRadius: "0.3rem",
    color: "white"
  }
});

export const getPanelContainerStyles = (): ICSSInJSStyle => ({
  width: "100%",
  height: "auto",
  overflow: "auto",
  flexFlow: "row wrap",
  margin: "0",
  justifyContent: "center"
});
export const getPreviewLabelStyles = (): ICSSInJSStyle => ({
  overflow: "hidden",
  textOverflow: "ellipsis",
  whiteSpace: "nowrap",
  lineHeight: "3.2rem !important",
  marginLeft: "0.4rem",
  verticalAlign: "top",
  fontSize: "1.2rem",
  textAlign: "left"
});

export const getPreviewImageContainerStyles = (
  isIconOnly: boolean
): ICSSInJSStyle => ({
  position: "relative",
  height: "8rem",
  width: "14.4rem",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  background: sharingPanelDefaultBackground,
  ...(isIconOnly && {
    border: `0.1rem solid ${previewItemBorderColor}`
  })
});

export const getPreviewImageStyles = (isIconOnly: boolean): ICSSInJSStyle => ({
  objectFit: "cover",
  ...(isIconOnly && {
    objectFit: "scale-down",
    padding: "2rem",
    boxSizing: "border-box"
  })
});

export const getIconContainerStyles = (): ICSSInJSStyle => ({
  width: "2.2rem",
  height: "2.2rem",
  position: "absolute",
  left: "0.2rem",
  bottom: "0.2rem",
  padding: "0.2rem",
  backgroundColor: iconContainerBackgroundColor,
  display: "flex",
  justifyContent: "center",
  alignItems: "center"
});`

**Comment by vini-gupta** [comment]
@alinais @kuzhelov @musingh1

**Comment by kuzhelov** [comment]
note that, in contrast to what is stated in the issue, `Flex` by default **doesn't** introduce any additional spacings around its child elements - please, consider to take a look on the following example that indicates that: https://codesandbox.io/s/yqwnqnyrx?module=/example.js

@vini-gupta, please, provide more concise description of what makes it to be the `Flex` issue. 

Thank you!
