### ISSUE TITLE
Icon for screen share

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#1250]
### Problem description
We need the following icon for desktop screen sharing to be used in the share tray.
![image](https://user-images.githubusercontent.com/47372422/56557682-e37e3900-6550-11e9-9afe-83cee70d502d.png)

![image](https://user-images.githubusercontent.com/47372422/56557655-c34e7a00-6550-11e9-8507-b13de6bda575.png)

**Comment by hughreeling** [comment]
See https://github.com/stardust-ui/react/pull/585 - this provides all the necessary instructions to prepare the PR that will export this icon to Teams theme

**Comment by vini-gupta** [comment]
#1278
