### ISSUE TITLE
Add support for input slider and toggle button

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#1255]
### Problem description
We need support for adding 
1. input slider for controlling volume in device panel 
2. toggle button to toggle for scenarios like enable system audio, private viewing etc.
![image](https://user-images.githubusercontent.com/47372422/56600347-51584e00-65ad-11e9-9703-b0159fe95515.png)
![image](https://user-images.githubusercontent.com/47372422/56600442-88c6fa80-65ad-11e9-8442-8aa032deb578.png)
![image](https://user-images.githubusercontent.com/47372422/57033424-bb05d700-6c01-11e9-9ae8-1468b4c4308d.png)

**Comment by jurokapsiar** [comment]
Fixed by https://github.com/stardust-ui/react/pull/1559 and https://github.com/stardust-ui/react/pull/1405
