### ISSUE TITLE
Docs: Improve types and default values

### ISSUE THREAD

**Issue by hughreeling** [microsoft/fluent-ui-react#1274]
### Problem description
Currently we're very inconsistent in display of default values for properties on the DocSite.
For example, 
Boolean values default to false, but this isn't clear
Some enumerations have default value in practise, but this isn't shown i.e. hAlign in Flex
Other enumerations don't and behaviour changes when property is present or not. i.e. gap in Flex.  Probably gap should have 'none' in enumeration and default to that.

### Proposed solution
Review all properties and check if defaults are sensible and reflected on DocSite correctly.
Maybe create rules.  Boolean defaults to false, number to 0, enumeration to first value.

**Comment by alinais** [comment]
#1277

**Comment by jurokapsiar** [comment]
closing as the duplicate is closed
