### ISSUE TITLE
Initial rendering of Popup can't evaluate the correct alignment

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#1279]
## Bug Report
First rendering of popup can't evaluate the correct alignment as shown in the attached video:

[PopupRenderingBug.zip](https://github.com/stardust-ui/react/files/3133529/PopupRenderingBug.zip)

Code:

> `import * as React from "react";
import { Button, Popup, Flex } from "@msteams/components-teams-stardust-ui";
import { CallingShareTray } from "@msteams/components-calling-share-tray";

interface IScreenSharingButtonState {
  open: boolean;
}

export class ScreenSharingButton extends React.PureComponent<
  {},
  IScreenSharingButtonState
> {
  public state = {
    open: false
  };
  // tslint:disable-next-line:max-func-body-length
  public render() {
    return (
      <Flex>
        <Popup
          open={this.state.open}
          onOpenChange={this.handleOpenChange}
          primary
          pointing
          content={{
            content: (
              <>
                <Flex
                  column
                  gap="gap.smaller"
                  // tslint:disable-next-line:noStylesWithStardust
                  styles={{
                    maxWidth: "720px",
                    maxHeight: "334px",
                    width: "100%",
                    height: "100%",
                    overflowY: "auto",
                    overflowX: "auto"
                  }}
                >
                  <Flex hAlign="end" vAlign="start">
                    <Button
                      text
                      iconOnly
                      icon="close"
                      // tslint:disable-next-line:noStylesWithStardust
                      styles={{
                        width: "30px",
                        height: "30px"
                      }}
                      onClick={this.handleOpenChange}
                    />
                  </Flex>
                  <Flex>
                    <CallingShareTray isSSFC={true} />
                  </Flex>
                </Flex>
              </>
            )
          }}
          trigger={
            <Button
              size="big"
              icon="call-control-present-new"
              circular
              primary
              onClick={this.handleOpenChange}
            />
          }
          position="below"
          align="end"
        />
      </Flex>
    );
  }
  private handleOpenChange = () => {
    this.setState({
      open: !this.state.open
    });
  };
}
`
@kuzhelov @mnajdova @jurokapsiar @alinais @hughreeling

**Comment by vini-gupta** [comment]
Video capturing the issue:
[PopupRenderingBug.zip](https://github.com/stardust-ui/react/files/3135127/PopupRenderingBug.zip)

Code:
[PopupCode.txt](https://github.com/stardust-ui/react/files/3135131/PopupCode.txt)

@kuzhelov @mnajdova

**Comment by kuzhelov** [comment]
it seems that the case provided here is related to async rendering of the Popup. Note that Popup evaluates its position given the content that is present at moment when Popup is rendered. To ask Popup to re-evaluate its positioning after async data is rendered, please, consider to use technique suggested in docs: https://stardust-ui.github.io/react/components/popup#usage-async

**Comment by bmdalex** [comment]
@vini-gupta did @kuzhelov 's suggestion help you fixed the issue? can we close this item?

**Comment by layershifter** [comment]
Our example in docs covers the case with content updates. Please provide us an example on CodeSandbox if it will not resolve the issue.

Closing for housekeeping.
