### ISSUE TITLE
[RFC]: Extract theme function for applying hover and focus styles

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#1295]
# [RFC]: Extract theme function for applying hover and focus styles

## Problem description

Plenty of components apply the same set of styles when different parts are hovered / focused, especially in High Contrast (HC) theme.

Related to #1259

Here are the patterns I've identified so far. These styles are (or should be) applied for most actionable slots in most components.

#### 1. on hover:
- filled icon

#### 2. on focus:
- filled icon
- double border:
  - inner: 1px white
  - outer: 1px black

| default | :hover | :focus |
|:-------:|:------:|:--------:|
| ![Screenshot 2019-05-07 at 13 10 13](https://user-images.githubusercontent.com/5442794/57303380-7c7a8b80-70dd-11e9-97f8-386a76130c23.png) | ![Screenshot 2019-05-07 at 13 10 21](https://user-images.githubusercontent.com/5442794/57303386-80a6a900-70dd-11e9-88fb-f1305e3dde7a.png) | ![Screenshot 2019-05-07 at 13 10 28](https://user-images.githubusercontent.com/5442794/57303394-843a3000-70dd-11e9-9dd7-e7887cbd0bd6.png) |

#### 1. on hover:
- filled icon

#### 2. on focus:
- filled icon
- double border:
  - inner: 1px black
  - outer: 1px white

| default | :hover | :focus |
|:-------:|:------:|:--------:|
| ![Screenshot 2019-05-07 at 12 57 19](https://user-images.githubusercontent.com/5442794/57303427-96b46980-70dd-11e9-960e-daf6a7d78518.png) | ![Screenshot 2019-05-07 at 12 57 26](https://user-images.githubusercontent.com/5442794/57303441-9b791d80-70dd-11e9-95f8-f6adf3102911.png) | ![Screenshot 2019-05-07 at 12 57 33](https://user-images.githubusercontent.com/5442794/57303446-9fa53b00-70dd-11e9-9a8c-b77fc9923f26.png) |

#### 1. on hover:
- filled icon
- 1px black border
- yellow background color

#### 2. on focus:
- filled icon
- double border:
  - inner: 1px black
  - outer: 1px cyan
- yellow background color

| default | :hover | :focus |
|:-------:|:------:|:--------:|
| ![Screenshot 2019-05-06 at 19 08 29](https://user-images.githubusercontent.com/5442794/57303472-afbd1a80-70dd-11e9-892e-0e44489eabaa.png) | ![Screenshot 2019-05-06 at 19 08 36](https://user-images.githubusercontent.com/5442794/57241952-898e7080-7032-11e9-8bb3-baa1d554f294.png) | ![Screenshot 2019-05-06 at 19 08 43](https://user-images.githubusercontent.com/5442794/57242027-bb9fd280-7032-11e9-8f45-a15e6ac9828b.png) |

## Proposed solution
Extract this logic in reusable function (with some customizable values) and call it across all relevant components.

#### List of components and the slots where this logic needs to be applied:
- [ ] `Alert`: `action` slot
- [ ] `Attachment`: component itself and `action` slot
- [ ] `Button`: component itself and `icon` slots
- [ ] `Chat.Message`: `content`, `actionMenu` and `reactionGroup` slots
- [ ] `Label`: `icon` slot
- [ ] `selectable` `List`: `items` slot
- [ ] `underlined` and `iconOnly` `Menu`: `items` slot
- [ ] `RadioGroup`: `items` slot
- [ ] `Reaction`: `icon` slot

**Comment by codepretty** [comment]
i think we just want a 1px black border for hover, not a cyan/black on hover

**Comment by bmdalex** [comment]
@codepretty I updated the description
please check the list of components as well and feel free to edit it

**Comment by levithomason** [comment]
This is an idea that many of us agree with.  We've also discussed it with other libraries as a thing to standardize on.  We're ready for some demonstration of how this would work but the core team is not able to produce that at the moment.

Contributions welcome 🙌
