### ISSUE TITLE
Need to update Teams icon for MW

### ISSUE THREAD

**Issue by notandrew** [microsoft/fluent-ui-react#1296]
### Steps
A clear and concise description of steps to reproduce the problem.

### Expected Result
The result that you expected.

### Actual Result
The actual result that happened 💣

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by alinais** [comment]
@notandrew, do we have already the new icon so that we can update it?

**Comment by notandrew** [comment]
@alinais - I don't think it's in Stardust yet...

**Comment by codepretty** [comment]
It's not in Stardust, but we do have the new icon from design.

**Comment by alinais** [comment]
![image](https://user-images.githubusercontent.com/1826985/61812385-ac673e80-ae43-11e9-9ee1-9815c0d91cc5.png)
