### ISSUE TITLE
Dropdown, can't define default selected item

### ISSUE THREAD

**Issue by KyleBastien** [microsoft/fluent-ui-react#1302]
### Problem description

Dropdown doesn't currently have a way to set a "currently selected item" for a single selection Dropdown. There is a `activeSelectedIndex` but this seems to only apply to Dropdown's of type `multiple`, but even then, also doesn't seem to actually select the item, unless I'm wrong? Which I'm totally okay with being wrong here.

### Proposed solution

Ideally Dropdown would expose something like a `defaultSelectedItemIndex` prop. Here you could pass in an index of an item in the `items` array. Then when Dropdown is rendered, it displays that item as the selected item. There could also be a `selectedItemIndex` prop, that would allow the user full control of the selected index.

For example, in the "super heroes" Dropdown example from the docs, you could do something like this:

```
import React from 'react'
import { Dropdown } from '@stardust-ui/react'
const inputItems = [
  'Bruce Wayne',
  'Natasha Romanoff',
  'Steven Strange',
  'Alfred Pennyworth',
  `Scarlett O'Hara`,
  'Imperator Furiosa',
  'Bruce Banner',
  'Peter Parker',
  'Selina Kyle',
]

const DropdownExample = () => (
  <Dropdown
    items={inputItems}
    defaultSelectedItemIndex={1}
    getA11ySelectionMessage={{
      onAdd: item => `${item} has been selected.`,
    }}
  />
)
```

And the Dropdown would render looking like this:

![image](https://user-images.githubusercontent.com/3861611/57399515-3e857200-7186-11e9-951e-12ea672a639e.png)

### MVP

This is what it looks like if you try to use `defaultActiveSelectedIndex` or `activeSelectedIndex` right now.

https://codesandbox.io/s/lrk2x03oz7?fontsize=14

**Comment by silviuaavram** [comment]
I think you are mixing the API quite a bit.

There is `highlightedIndex` and there is `value`.

`defaultActiveSelectedIndex` and `activeSelectedIndex` are only for when we highlight the selected values, in multiple selection, by either clicking them or by Left/Right Arrow navigation.

I think you actually want to use `value` and `defaultValue` for the scenarios you describe.

**Comment by KyleBastien** [comment]
Sure enough, that's super non-obvious from the docs / examples, since I would expect a `defaultIndex` or `defaultKey`. But using `defaultValue` and passing in the entire value from the items array, does work.

Example for others:
https://codesandbox.io/embed/stardust-ui-example-o3fgl
