### ISSUE TITLE
Popup is closed incorrectly when click inside element

### ISSUE THREAD

**Issue by xiaolanli** [microsoft/fluent-ui-react#1324]
### Steps
1. click on the button, a Popup with an inner button "click me" shows up
2. click on "click me", the popup disappeared

### Expected Result
click on "click me", the popup should get smaller. 
*Notice that we put "e.preventDefault();" to the onClick handler, but it didn't trap the event. 

### Actual Result
the popup disappears

### Version
latest

### Testcase
https://codesandbox.io/s/031rl98lzw?fontsize=14

**Comment by johannao76** [comment]
I would like to add that this is also causing an issue with Enter key press on the toolbar buttons in compose, so we should address both issues in the same change. Keyboard events also have the same issue on the stickers picker. The deeper issue here seems to be that stardust is using native events as opposed to react events. These don't share the same pipeline and should not be mixed. We should only use react events.
