### ISSUE TITLE
[IE11][!important] Stardust documentation page not loading

### ISSUE THREAD

**Issue by kamilakorzec** [microsoft/fluent-ui-react#1343]
## Bug Report
When trying to open the stardust documentation page in IE11 Syntax error is thrown and the whole page crashes:
![image](https://user-images.githubusercontent.com/11797698/57846927-8e42e980-77d5-11e9-9fe9-19d959a7f7a5.png)

### Steps
Open https://stardust-ui.github.io/react/ in IE11

### Expected Result
Page is loading

### Actual Result
Blank page displayed

### Version
0.30

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by jurokapsiar** [comment]
this has been resolved, page loads. Layout issues are tracked separately
