### ISSUE TITLE
Need the ability to have an icon to mark a selected item in a dropdown

### ISSUE THREAD

**Issue by codepretty** [microsoft/fluent-ui-react#1349]
## Feature Request
For a selected dropdown item, we need to have an optional icon indicator for what is currently selected.

In this case, the icon should be a checkmark.

### Problem description
![image](https://user-images.githubusercontent.com/828692/57886326-cb14dd80-77e1-11e9-9d9b-cce5de9ff432.png)

### Questions
1. Would this be a `list` or a `menu` or would we want the option in both components?
2. Is the eye icon + "show" in this scenario a similar thing?
![image](https://user-images.githubusercontent.com/828692/57886275-b2a4c300-77e1-11e9-9cd8-a7f55225a50d.png)

**Comment by levithomason** [comment]
## Ideas

### `active`

It looks like the checkmark icon on the right of "New Conversation" is the active item indicator.  This could be achieved with an `::after` style in the theme and avoid needing a new slot.

### `description`

There is a slot on the right in Semantic called `description`, however, it is usually used for grayed out verbiage that further describes the item's text.

![image](https://user-images.githubusercontent.com/5067638/57943469-f999c380-7888-11e9-89b7-bd674a0d1993.png)

![image](https://user-images.githubusercontent.com/5067638/57943941-3fa35700-788a-11e9-8844-ecd434fb3563.png)

I could actually see this serving the goal of the second image you posted with "[eye] Show".  This looks like a possible description of the "Culture Club Inspirations" item that is shown on hover.

### `endIcon`

Many components support an icon on one side, like the Button, Label, MenuItem, and ListItem.  When the icon needs to move to the other side, we use the `iconPosition` prop.  However, we could support an icon on both sides.  Something like `icon` and `iconEnd`?

This idea is loosely borrowed from the concept of `start` and `end` representing an RTL safe way of positioning things.  We've used this terminology in the `iconPosition` prop and also in the List's layout with `start` and `end` areas.

## More Questions

1. Is this icon position used exclusively for toggling items on and off?
1. Is it formatted the same as a description/hint/help text (see `description` above)?

**Comment by jurokapsiar** [comment]
this has already been done
