### ISSUE TITLE
Missing icons: chevron-left and chevron-right

### ISSUE THREAD

**Issue by kamilakorzec** [microsoft/fluent-ui-react#1359]
We're missing left and right chevron for the navigation:
![image](https://user-images.githubusercontent.com/11797698/58016240-63ba9e80-7afd-11e9-832c-ffb45aa52277.png)

**Comment by codepretty** [comment]
What size are those icons? I believe this request is dependent on issue #1356 

Once we have all 3 sizes of icons, we just need to rotate them to get the desired look. eg)
```
<Icon name="chevron" size="small" rotate={270} />
```

**Comment by jurokapsiar** [comment]
Icons can be added to the theme in overrides
