### ISSUE TITLE
Create better element ID generator

### ISSUE THREAD

**Issue by silviuaavram** [microsoft/fluent-ui-react#1369]
## Bug Report
Replace the use of `_.uniqueId` with a better implementation, as these are re-generated at every render, and is confusing.

### Steps
Replace the lodash function in `dialogBehavior.ts` and `Accordion.tsx` with a better implementation, that will generate a unique ID but only once.

**Comment by layershifter** [comment]
If you need to do something one time in class components: do this in `constructor()`: `_.uniqueId()` works as expected for me.

For function components, we can use existing hook: https://github.com/reach/reach-ui/blob/master/packages/auto-id/src/index.js
