### ISSUE TITLE
API: Enable adding child render functions

### ISSUE THREAD

**Issue by alinais** [microsoft/fluent-ui-react#1374]
### Problem description

Existing `render()` function is very complicated because its syntax is not intuitive.

#### Render Props in `children`

Introduce [Render Props](https://reactjs.org/docs/render-props.html) pattern to:

```jsx
<Image disabled>
  {(props) => <img {...props} />}
</Image>
```

One of the benefits of this design is that it's common and widely used API.

All components should support this pattern, expect utility components like `Positioner`, `Portal` and `Ref`. This should work even for components that don't support Children API.

This will also work well to wrap components:

```jsx
<Menu>
  {(props, ElementType) => (
    <Popup>
     <ElementType {...props />
    </Popup>
  )}
</Menu>
```

#### Render Props in shorthands

This will enable all shorthand to use the `children` prop for accepting calculated values as well.
Once this is implemented, try solving the issue linked above with the pattern.

```jsx
<DropdownItem
    image={{
      disabled: true,
      children: (props, ElementType) => <ElementType {..._.without('avatar', props)} />
  }}
/>
```

#### Remove `render()` callback

This means that we don't render callback anymore 🎉 

#### Passed JSX element is now content

Before we tried to apply props to passed element:
```jsx
<Button content='Foo' /> // everything is fine
<Button content={<div>Foo</div>} /> // 💣  we will try to apply props
```

This decision caused numerous problems to us, we have even try to disable ability to pass JSX elements...

**Solution**: deal with JSX elements like with primitives

```jsx
<Button content='Foo' />
<Button content={{ content: <div>Foo</div>}} /> // will be equal
```

**Comment by jurokapsiar** [comment]
this has been done - children callback function
