### ISSUE TITLE
Button text is cut off in the bottom

### ISSUE THREAD

**Issue by PetraVujevic** [microsoft/fluent-ui-react#1376]
### Steps
Create a Button, for example
< Button content= "See how this very long text shows up on the button" / >
 
### Expected Result
Button text is fully visible and not cut off in the bottom

### Actual Result
Button text is cut off in the bottom on letter such as 'y' and 'g'

### Version
^0.29.1

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by codepretty** [comment]
This is just missing a `line-height` of 20px

**Comment by codepretty** [comment]
Oh, looks like we might have a reset adding arbitrary line-heights??

![image](https://user-images.githubusercontent.com/828692/58507326-5aa57f00-8146-11e9-8120-eed2045b0bd3.png)
