### ISSUE TITLE
<Text> is missing textAlign prop

### ISSUE THREAD

**Issue by francescopalmiotto** [microsoft/fluent-ui-react#1378]
## Feature Request
`<Text>` is missing `textAlign` prop.

### Problem description
`<Header>` has a `textAlign` prop, `<Text>` doesn't. 
Currently this problem can be overcome by simply using `align`; since this prop is not supported, it is passed down to the underlying HTML DOM element and it just works, but, as we discussed offline, this is not the right approach.

### Proposed solution
Let's add `textAlign` prop if nobody is against it. 
Should be fairly easy to implement it, I could submit a PR for it.

**Comment by jurokapsiar** [comment]
closing as there is a way to pass align
