### ISSUE TITLE
Flex with wrap includes gap between wrapped components

### ISSUE THREAD

**Issue by dslane** [microsoft/fluent-ui-react#1389]
### Steps
When creating a Flex with the wrap property and a gap set, the gap is still included at the point where the wrap occurs. This causes the elements before a wrap point to appear narrower than the last element in the Flex, even if all items in the flex have the same value for grow

![image](https://user-images.githubusercontent.com/1444267/58353225-c88a3780-7e22-11e9-873f-74a3edb865bf.png)

### Expected Result
All wrapped elements with the same value for grow should be the same size, regardless of the gap and wrapping

### Actual Result
All non-last elements that are wrapped appear shorter due to the margin added by the gap 💣

### Version
0.31.0

### Testcase
https://codesandbox.io/s/flexwrapissue-njyey

**Comment by kuzhelov** [comment]
closing this issue, as example provided is not seen to be handled by flex layout algorithm (which gauarntees alignment in 1D direction only). This layout is expected to be handled with grid algorithm, using `auto-fit/fill` props (depends on the effect that is needed to be achieved): https://stackoverflow.com/questions/43129360/css-grid-wrapping

The API of `Flex` and `Grid` components from Stardust are an abstraction on top of these models - thus, if flex algo's spec doesn't support this layout, `Flex` won't either.
