### ISSUE TITLE
Increase `popper.js` version to `1.15.0`

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#1403]
### Description

`flipVariationsByContent` modifier was introduced in `1.15.0`, we should increase required PopperJS version
https://github.com/FezVrasta/popper.js/releases/tag/v1.15.0

#### Currently blocked by OSS approval for `popper.js` version `1.15.0`

_Originally posted by @layershifter in https://github.com/stardust-ui/react/pull/1384_

**Comment by alinais** [comment]
Fixed in #1439
