### ISSUE TITLE
Popup content jumps for a split second when opening 

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#1415]
### Steps
- build master
- go to `Popup` examples page: http://localhost:8080/components/popup#types-popup
- click the button to open the `Popup`

### Expected Result
Popup opens without jump

### Actual Result
Popup has a small but noticeable jump when opening (see gif below) 💣

![popup](https://user-images.githubusercontent.com/5442794/58549567-1aa8cf80-820c-11e9-8989-aa550c436368.gif)

### Version
UNRELEASED

**Comment by miroslavstastny** [comment]
See also #1361
