### ISSUE TITLE
Provider doesn't receive styles prop as of 0.31.0

### ISSUE THREAD

**Issue by PetraVujevic** [microsoft/fluent-ui-react#1424]
### Steps
```
<Provider
        theme={mergeThemes(this.state.theme, {
          staticStyles: [
            {
              a: {
                textDecoration: 'none'
              }
            }
          ]
        })}
        styles={**styles.provider**}
 >
...
< /Provider>
```

### Expected Result
As of 0.31.0 Provider is not receiving styles as prop. How should we style Provider?

### Actual Result
Provider is styling itself based on **styles.provider**

### Version
0.31.0

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by miroslavstastny** [comment]
Yup, `styles` prop on any Stardust component is used to override styles of that particular instance of the component.

That means that following code:
```jsx
<Provider styles={{background:'red'}} />
```
will make the `div` created by the `Provider` to be red, without influencing anything else.

I am sorry but I don't understand your issue. Could you please explain what you are trying to achieve?

**Comment by KyleBastien** [comment]
@miroslavstastny Something has changed in the Typing for the Stardust Provider and now if you try and apply a `styles` prop, it doesn't compile. If you try and do this:

```
<Provider theme={themes.teams} styles={{background: 'red'}}>
```

You will get a TypeScript error saying:

```
Property 'styles' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Provider> & Pick<Pick<Readonly<WithAsProp<ProviderProps>> & Readonly<{ children?: ReactNode; }>, "children" | "theme" | "rtl" | "renderer" | "disableAnimations"> & Pick<...> & Pick<...>, "children" | ... 4 more ... | "disableAnimations"> & Partial<...> & Partial<...>'
```

Specifically, our use case, is that want to style the provider div to take up 100% of our tab's available space, so we try and pass in styles like this:

```
<Provider theme={themes.teams} styles={{
      backgroundColor: 'transparent',
      display: 'flex',
      flexFlow: 'column',
      height: '100%'
    }}>
```

But, we get the same TypeScript error from above, that `styles` does not exist on the Provider type.

Was it intentional to remove the `styles` prop from the Provider Component?

**Comment by KyleBastien** [comment]
Note: Using a `// @ts-ignore`, allows for `styles` to pass the TypeScript compiler, and also applies the styles correctly to the `Provider`.

So, this looks to be a TypeScript types issue, but the underlying implementation is still the same.

**Comment by miroslavstastny** [comment]
I see, the code works but typings are incorrect, will fix that asap.

**Comment by KyleBastien** [comment]
Thanks @miroslavstastny!
