### ISSUE TITLE
implement copied to clipboard icon 

### ISSUE THREAD

**Issue by allina** [microsoft/fluent-ui-react#1432]
### Problem description
copied to clipboard icon is missing in stardust and I need it to implement copy meeting info button

### Proposed solution
implement the icon : 
![image](https://user-images.githubusercontent.com/2542298/58644914-92f1bc80-8302-11e9-89eb-4b26817d56c0.png)

### MVP
[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

**Comment by allina** [comment]
@mnajdova

**Comment by alinais** [comment]
@allina please update the description of your request to contain meaningful information. (e.g. a screenshot would be useful). Otherwise, I'll close this issue.

**Comment by allina** [comment]
@alinais @mnajdova updated . Do you have an ETA for this request ?

**Comment by alinais** [comment]
@allina, you can add it yourself faster by following the guidance here:
https://stardust-ui.github.io/react/faq#how-to-add-icons-to-stardust

**Comment by lawrencecushman** [comment]
Hey @alinais what if the icon isn't in Stardust yet? Do we just add it to both `/ProcessedIcons` and `/icons` folders?

**Comment by bcalvery** [comment]
Icon added in PR [1792](https://github.com/stardust-ui/react/pull/1792)
