### ISSUE TITLE
CSS Fallback values do not work (again)

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluent-ui-react#1460]
### Steps
Specify style as an array:
```jsx
styles: {
  border: ["1px solid red", "1px solid blue"],
},
```

### Expected Result
This is considered valid, both values are applied in CSS:
![image](https://user-images.githubusercontent.com/9615899/59028616-45260880-885c-11e9-9396-1a709fc236e0.png)

### Actual Result
No value applied
![image](https://user-images.githubusercontent.com/9615899/59028472-ed879d00-885b-11e9-9d80-dfd28f79b26f.png)

### Version
0.32.0, it broke between 0.29.0 and 0.29.1

### Testcase
https://codesandbox.io/s/css-fallback-value-wmg81

**Comment by mnajdova** [comment]
I would guess that the `expand css shorthands fela plugin` broke this. Let me investigate.

**Comment by miroslavstastny** [comment]
Yes, that's it.

**Comment by mnajdova** [comment]
Will introduce a PR with appropriate screenshot test to catch this.
