### ISSUE TITLE
Icon for Broadcast CQF category

### ISSUE THREAD

**Issue by lawrencecushman** [microsoft/fluent-ui-react#1486]
## Feature Request
![image](https://user-images.githubusercontent.com/1784684/59233594-fe0e7f00-8b9d-11e9-84ec-103d526a9586.png)

### Problem description
Please port the Broadcast CQF button over to Stardust. It can be renamed from `cqf-broadcast` to just `broadcast.tsx`, since it's used for much more than just CQF.

### Proposed solution
https://domoreexp.visualstudio.com/Teamspace/_git/Teamspace-Web?path=%2FWebClient%2Fsrc%2Fapp%2Fsvg%2Ficons-cqf-broadcast.html&version=GBdevelop

**Comment by jurokapsiar** [comment]
Icons can be added to themes overrides
