### ISSUE TITLE
Provider type errors

### ISSUE THREAD

**Issue by aniknafs** [microsoft/fluent-ui-react#149]
## Bug Report
Usage of Provider is triggering errors in the definition file of Provider (provider.d.ts). 
There have been no issues in 0.2.6/0.2.7 when `commonjs` version was exported instead of `es`

### Steps
```
import { Provider } from "@stardust-ui/react";
//just the import is triggering the errors
```
### Expected Result
No errors. 

### Actual Result
WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:19:47
    TS1005: '>' expected.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:19:54
    TS1003: Identifier expected.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:19:75
    TS1144: '{' or ';' expected.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:19:98
    TS1005: ';' expected.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:19:99
    TS1109: Expression expected.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:20:35
    TS1109: Expression expected.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:21:32
    TS1109: Expression expected.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:22:24
    TS1005: ';' expected.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:22:30
    TS1109: Expression expected.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:23:13
    TS1005: ';' expected.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:24:1
    TS1128: Declaration or statement expected.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:20:5
    TS7028: Unused label.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:21:5
    TS7028: Unused label.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:19:47
    TS7010: 'import', which lacks return-type annotation, implicitly has an 'any' return type.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:19:54
    TS7006: Parameter '(Missing)' implicitly has an 'any' type.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:19:76
    TS7008: Member 'IProviderConsumerProps' implicitly has an 'any' type.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:20:25
    TS7011: Function expression, which lacks return-type annotation, implicitly has an 'any' return type.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:21:22
    TS7011: Function expression, which lacks return-type annotation, implicitly has an 'any' return type.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:22:5
    TS2304: Cannot find name 'componentDidMount'.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:23:5
    TS2304: Cannot find name 'render'.

WARNING in [at-loader] ../../../node_modules/@stardust-ui/react/dist/es/components/Provider/Provider.d.ts:23:15
    TS2708: Cannot use namespace 'JSX' as a value.

### Version
0.3.0

**Comment by levithomason** [comment]
Fixed in the suspect repo.  There was no Stardust bug here 🎉
