### ISSUE TITLE
Docs: examples that contain React.Fragments are broken on CodeSandbox

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluent-ui-react#1519]
## Bug Report

`<>` is working in newly created CodeSandboxes: https://codesandbox.io/s/infallible-leftpad-gczx1
However, `<>`  is broken in ours 😭

It seems that we're using outdated template (`sandbox.config.json`):

```json
{"template":"create-react-app"}
```

**It works properly for TS examples.**

### Steps
1. Go to example: https://stardust-ui.github.io/react/components/checkbox#types-disabled
2. Click to "CodeSandbox" button

### Expected Result

Working example.

### Actual Result

![image](https://user-images.githubusercontent.com/14183168/59775202-0eff7480-92b1-11e9-8c80-8febd87abc29.png)

### Version
latest

**Comment by lucivpav** [comment]
Note: "react-scripts": "latest" should be added to `package.json`, this resolves the error
