### ISSUE TITLE
Docs: HTML previews are broken for some examples

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluent-ui-react#1529]
## Bug Report

![image](https://user-images.githubusercontent.com/14183168/59914903-b698b600-941b-11e9-9172-a305ee9361a9.png)

### Steps
1. Go to https://stardust-ui.github.io/react/components/dropdown#types-dropdown
2. Click `Try  it`

### Expected Result
Example is working

### Actual Result
The actual result that happened 💣
![image](https://user-images.githubusercontent.com/14183168/59914972-d7f9a200-941b-11e9-8cba-e8aa27fe62e5.png)

### Version
latest

**Comment by lucivpav** [comment]
*The actual error*
Invariant Violation: Portals are not currently supported by the server renderer. Render them conditionally so that they only appear on the client render.

**Comment by jurokapsiar** [comment]
fixed
