### ISSUE TITLE
`Sticky` / `Position` component to achieve different positions

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#1532]
### Problem description
Our users have no means to:
- position content / components relatively to other components / elements / parts of viewport
- position content/ components absolutely (CSS position absolute)
- make their content /components `sticky` on the screen (CSS position fixed)

### Proposed solution
Implement a new component to achieve different way to position content / components by:
- looking at the problems described above and figure out necessary set of features
- getting inspired by other libraries such as: https://react.semantic-ui.com/modules/sticky/

### MVP
[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

**Comment by miroslavstastny** [comment]
Addressed in #1854:
```jsx
import React from 'react'
import { Avatar } from '@stardust-ui/react'

const AvatarExampleShorthand = () => (
  <div style={{ height: '100px', outline: '1px solid #ccc', overflow: 'scroll' }}>
    <div>
      <Avatar name="Avatar 1" design={{ position: 'sticky', top: 0 }} />
      <p>a1.1</p>
      <p>a1.2</p>
      <p>a1.3</p>
    </div>
    <div>
    <Avatar name="Avatar 2" design={{ position: 'sticky', top: 0 }} />
      <p>a2.1</p>
      <p>a2.2</p>
      <p>a2.3</p>
    </div>
  </div>
)

export default AvatarExampleShorthand

```
