### ISSUE TITLE
Checkbox is not following the Teams Dark or Teams High contrast themes

### ISSUE THREAD

**Issue by fesouzamsft** [microsoft/fluent-ui-react#1547]
## Bug Report

When using the Teams Dark, or Teams High Contrast themes, the Checkbox component does not have appropriate styling in quite a few aspects. It should match what we see in the Teams app.

### Steps
1 - Go to https://stardust-ui.github.io/react/components/checkbox
2 - Change the theme to Teams Dark or Teams High Contrast
3 - Observe the checkbox checked and unchecked

### Expected Result
- The border of the unchecked checkbox should be white, not a shade of black
- The fill color of the checked checkbox should be a lighter shade of purple in Teams Dark and a bright yellow in Teams High Contrast.
- The checkmark should be smaller.
- The checkmark should be a shade of black, not white.

### Actual Result
- Unchecked:
![image](https://user-images.githubusercontent.com/12650823/60142944-e83db400-9770-11e9-8e73-489130c4ac0f.png)

- Checked:
![image](https://user-images.githubusercontent.com/12650823/60142937-deb44c00-9770-11e9-8834-28fb79da4f9e.png)

### Version
0.33.0

### Testcase
Can be reproduced at https://stardust-ui.github.io/react/components/checkbox

**Comment by vini-gupta** [comment]
FYI @alinais, @kumar-microsoft

**Comment by alinais** [comment]
@codepretty

**Comment by codepretty** [comment]
@bcalvery just picked up the work to redline & theme checkboxes

**Comment by alinais** [comment]
#1656
