### ISSUE TITLE
Dialog auto-focus is enabled for the first button in dialog window by default

### ISSUE THREAD

**Issue by bansalrachita** [microsoft/fluent-ui-react#1554]
### Steps
A Button on the Dialog Component, that closes the dialog window, auto-focuses on setting the state of the Dialog box to open. When the Dialog window is closed and re-opened, the close button is still focused. 

### Expected Result
Expected behavior should be when the Dialog is opened, the close button shouldn't be focused. The button should be focused only when button is clicked/active.

I figured this is due to a property trapFocus which sets another property- disableFirstFocus that defaults to "false”. This default behavior seems to be somewhat misleading from the normal behavior - which should be to not enforce focus by default.

### Actual Result
The button focus is enabled on setting Dialog state to open. When the Dialog is closed and re-opened, the close button is still focused.

### Version
0.29.1

### Testcase
https://codesandbox.io/embed/stardust-ui-example-uk3np

**Comment by jurokapsiar** [comment]
Hi, this is by design, for usability and accessibility. It allows the user to interact with the dialog. If the focus would not be inside of the dialog, the user, especially visually impaired user would not be aware that there is a dialog.

Can you please describe a use case where the focus would not need to be in the dialog?

**Comment by bansalrachita** [comment]
The use-case is more like which button to focus in the component when the dialog is opened/re-opened.

Is it possible to expose a prop which allows for focussing on specific button?

**Comment by jurokapsiar** [comment]
You can do following:
```
import { Button, Dialog } from '@stardust-ui/react'
import React from 'react'

const DialogExampleContent = () => (
  <Dialog
    cancelButton="Cancel"
    confirmButton={{ content: "Confirm", className: "confirm-button" }}
    content="Are you sure you want to confirm this action?"
    header="Action confirmation"
    trigger={<Button content="Open a dialog" />}
    trapFocus={{ firstFocusableSelector: "confirm-button" }}
  />
)

export default DialogExampleContent
```

See https://stardust-ui.github.io/react/focus-trap-zone for more details about focus trap zone which is used inside of the Dialog component.

**Comment by bansalrachita** [comment]
Thanks @jurokapsiar.
This satisfies what I'm looking for. Closing this issue.
