### ISSUE TITLE
Add more information to focusTrap/autoFocus Popup examples

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#1572]
### Problem description
Users find it confusing when they should or should not use focus trap in popup.

### Proposed solution
Add clarification to the examples

**Comment by alinais** [comment]
things to consider:
- Are both triggering componentDidUpdate and manually setting focus both equally good options or is one more preferable than another? Is there a reason to use one over the other?
- What does trapped mean here - just that the focus remains inside the popup until the popup is closed? What is the default behavior if you don't have this set?
