### ISSUE TITLE
Chat > Action menu is not position correctly for short message in chat 

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluent-ui-react#1577]
### Steps
Example:
https://6sokm.codesandbox.io/
1. Hover over second chat message for "Jane Doe" 
2. observe action menu rendering

### Expected Result
action menu should be whole rendered properly

### Actual Result
action menu is rendered to left and part of the items on the left side is not visible... 
![action_menu_bug](https://user-images.githubusercontent.com/22620150/60570729-74a03600-9d72-11e9-9c5f-8d9765778b52.gif)

Comment:
styles for actionMenu slot in chat message are applied in the way that caused the issue.

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by jurokapsiar** [comment]
fixed by https://github.com/stardust-ui/react/pull/1739
