### ISSUE TITLE
Muted attribute doesn't work on Embed videos

### ISSUE THREAD

**Issue by stuartlong** [microsoft/fluent-ui-react#1585]
## Bug Report

Settings `muted` or `muted={true}` on `Embed` components doesn't actually mute them.

### Steps
1. Create an embed component
2. Set it's source video as a mp4 video with sound
3. Add `muted={true}` to the embed control

### Expected Result
There should be a way to mute the component

### Actual Result
Can't mute

### Version
0.34.0

### Testcase
https://codesandbox.io/s/stardust-ui-example-owdmg

**Comment by layershifter** [comment]
`muted` is a prop of `Video` components, but this issue exists there, too: https://codesandbox.io/s/62dpz?module=/example.js

**Comment by stuartlong** [comment]
Right, yes, I don't expect Embed to take a specific muted attribute. But even setting the intrinsic muted attribute doesn't work.

**Comment by layershifter** [comment]
Was fixed in #1847.
