### ISSUE TITLE
Embed video has a white flash when toggle active state

### ISSUE THREAD

**Issue by stuartlong** [microsoft/fluent-ui-react#1586]
## Bug Report
When playing or pausing an embedded video there is a white flash when switching between the placeholder and the video. This is particualry annoying when the placeholder is the first frame of the video.

### Steps
Create an Embed component and press play

### Expected Result
Playing a video should smoothly show the video.

### Actual Result
There is a whiteflash before the video starts

### Version
0.34.0

### Testcase
https://codesandbox.io/s/stardust-ui-example-fm1ow

**Comment by lucivpav** [comment]
<del>Please see if PR #1768 resolves this. There is now a background color set. It behaves the same as Semantic UI's `Embed`.</del>

**Comment by lucivpav** [comment]
@jurokapsiar PR #1758 did not resolve this issue
