### ISSUE TITLE
Opening Typescript CodeSandbox for Chat broken

### ISSUE THREAD

**Issue by stuartlong** [microsoft/fluent-ui-react#1607]
## Bug Report
Opening the first chat example as a Typescript CodesandBox immediately fails:
![image](https://user-images.githubusercontent.com/2327459/60925791-77f75e00-a259-11e9-94dd-39e7e6797893.png)

### Steps
1. Navigate to https://stardust-ui.github.io/react/components/chat#types-chat
2. Hit "Try It" on first chat example
3. Switch to Typescript
4. Generate and open CodeSandbox

### Expected Result
CodeSandbox runs correctly

### Actual Result
CodeSandbox crashes

### Version
0.34.0

**Comment by stuartlong** [comment]
Also happens for Javascript

**Comment by lucivpav** [comment]
I couldn't reproduce it neither on [stardust-ui.github.io/react](stardust-ui.github.io/react) nor on master. I have tried Google Chrome and Edge and had not experienced any crash. I also tried both JS and TS. Are you still experiencing this issue?

**Comment by lucivpav** [comment]
I am unable to reproduce this issue on v0.34.0, v0.34.1 and on master. I tried both JS and TS and Chrome / Edge. Since the dependencies are set to `latest`, perhaps the cause has been already resolved. Are you still experiencing this issue?

**Comment by lucivpav** [comment]
This issue happens when lodash==4.17.12 on CodeSandbox. I am unable to reproduce this issue locally. The lodash dependency, however, is not needed to be specified in package.json.

**Comment by lucivpav** [comment]
I think the issue can occur when stardust uses different version of lodash internally, than the one the code example specifies in package.json.

Proposal: example package.json would use the same versions of dependencies as they are specified in stardust's package.json. @layershifter, is there a reason why the packages should stay 'latest'?

In createPackageJson.ts:
![image](https://user-images.githubusercontent.com/10930160/61445582-ecaf5400-a94d-11e9-93d2-a0c3c2290f64.png)

**Comment by lucivpav** [comment]
Note that the issue is no longer present (there are newer versions of lodash and other dependencies used). The question is, will it occur again in the future?

**Comment by lucivpav** [comment]
@layershifter @stuartlong what do you think?

**Comment by layershifter** [comment]
Let's use version from `package.json` 🏎
