### ISSUE TITLE
Provider renders a white background

### ISSUE THREAD

**Issue by dvdzkwsk** [microsoft/fluent-ui-react#1612]
## Bug Report

`Provider` renders a `Box` that has a background color. It seems like rendering a `Provider` should mostly be a transparent operation to the user, and thus not affect styling.

### Steps

1. Render a simple component wrapped in a Provider.

```js
<Provider theme={{ themes.teams }}>
  <p>Hello World>
</Provider>
```

### Expected Result

![Screen Shot 2019-07-10 at 11 01 49 AM](https://user-images.githubusercontent.com/6439050/60992820-22c35700-a302-11e9-8743-46706d45de2b.png)

### Actual Result

![Screen Shot 2019-07-10 at 11 00 21 AM](https://user-images.githubusercontent.com/6439050/60992750-f90a3000-a301-11e9-815f-64c800bc5b63.png)

### Version
0.34.0

**Comment by miroslavstastny** [comment]
Yup, we did that because without it users were confused, especially with this case:
```jsx
<Provider theme={{ themes.teamsDark }}>
  <p>I expect this to be light on dark</p>
</Provider>
```

Could you please go through description in #852 and share your opinion?
It also describes how you can override the styles to change the background/foreground color, or omit its `div` altogether.

**Comment by dvdzkwsk** [comment]
Ah, I had notifications turned off for the repo, so I didn't see your reply @miroslavstastny. I see now why this was done. It may not be worth changing the behavior for the reasons you cited (though my case is an anecdotal counterpoint, where I was confused by the new behavior).

It would be helpful to have a transparent Theme or Variables component that would allow parts of a tree to be customized, but it's easy enough to work around for now, so I'll close it unless others feel the same.
