### ISSUE TITLE
Getting error while importing from module themes/teams

### ISSUE THREAD

**Issue by hughreeling** [microsoft/fluent-ui-react#163]
## Bug Report
 Error is cannot find module @stardust-ui/react/themes/teams. Using Stardust version : 0.4.0.  Branch Name: Tempbranchproviderissue
import {
fontFaces,
staticStyles,
theme
} from "@stardust-ui/react/themes/teams";
"

### Steps
A clear and concise description of steps to reproduce the problem.
Steps to reproduce:
yarn install
yarn run storybook

### Expected Result
The result that you expected.

### Actual Result
The actual result that happened 💣

### Version
0.4.0

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by levithomason** [comment]
Working on this one.
