### ISSUE TITLE
Embed component in Chat.Message isn't accessible 

### ISSUE THREAD

**Issue by stuartlong** [microsoft/fluent-ui-react#1632]
## Bug Report
When an Embed component is embedded in a Chat.Message there's no way to navigate to the play / pause button via the keyboard.

### Steps
1. Embed an Embed component inside a Chat.Message
2. Try to play the Embedded object with the keyboard

### Expected Result
Should be able to navigate to the play / pause button

### Actual Result
Can't navigate to it. The Embed component is getting `tabIndex="-1"` when inside Chat.Message

### Version
0.34.1

### Testcase
https://codesandbox.io/s/stardust-ui-example-62bbh

**Comment by sophieH29** [comment]
Hi @stuartlong, I took a look at the issue.
`Chat` component is using `FocusZone` and each of the messages are inner FocusZones. 
When pressing `Enter` on `ChatMessage`, the focus goes inside and you can TAB between tabbable element inside a message, within the inner FocusZone. To make element tabbable/focusable for FocusZone, there is needed to set `data-is-focusable="true"` to that element/component. In your case - for the `Embed` component.
So if you apply this change, it will work as expected
```tsx
<Chat.Message
          content={
            <>
              <br />
              I can't focus this GIF
              <br />
              <Embed
                data-is-focusable="true" // ----> set attribute to make it tabbable
                placeholder="https://raw.githubusercontent.com/bower-media-samples/big-buck-bunny-480p-5s/master/poster.jpg"
                video="https://raw.githubusercontent.com/bower-media-samples/big-buck-bunny-1080p-5s/master/video.mp4"
              />
              <br />I can't focus this GIF
            </>
```

You can find more information about `FocusZone` here: https://stardust-ui.github.io/react/focus-zone

**Comment by stuartlong** [comment]
That worked, thanks!
