### ISSUE TITLE
TreeItem defaultOpen is not working

### ISSUE THREAD

**Issue by parasjindal** [microsoft/fluent-ui-react#1639]
## Bug Report
default open for tree item is not working when it contains a sub tree
### Steps
Pass `defaultOpen: true` prop to tree item

### Expected Result
Tree item's subtree should be open by default

### Actual Result
It's not open by default.

### Version
0.34.1

### Testcase
https://codesandbox.io/s/o1du5

**Comment by jurokapsiar** [comment]
This can be done, see https://microsoft.github.io/fluent-ui-react/components/tree/definition?showCode=true&showRtl=false&showTransparent=false&showVariables=false#usage-tree-initially-open-example
