### ISSUE TITLE
Support virtualized rendering of List/Chat items

### ISSUE THREAD

**Issue by kuzhelov** [microsoft/fluent-ui-react#1640]
### Problem description
The problem happens in cases when `List`/`Chat` content should be rendered as virtualized.

Virtualization capabilities are not provided by Stardust components, and this provides client with an options to either use existing library for this, or to write virtualization functionality by her own.

The most common choice for this situation is to use `react-virtualized`. Unfortunately, that attempt won't result in successful problem's resolution.

The core of the problem is that **_container components of `react-virtualized` should  own items rendering process_** (see `rowRenderer` in the example below), and this is not possible to achieve with Stardust - as for Stardust components it is also critical to control logic of items' rendering (to provide event handlers, accessibility attributes, etc).

```jsx
import { List as VirtualizedList } from 'react-virtualized'

<VirtualizedList
  ...
  rowRenderer={ ({ idx }) => .. render item given its index .. }
/>
```

### Proposed solutions

There are at least couple of options how this issue could be addressed. 

It is possible to **add virtualisation capabilities to implementation of Stardust components**, and provide the necessary API to the client to control it:

```jsx
import { Chat, List } from '@stardust-ui/react'

// `virtualized` logic is part of Stardust component's implementation
<List items={...} virtualized />
<Chat items={ ... } virtualized />
```

Another (admittedly, more involved) approach is to **extend capabilities of Stardust for composition scenarios**, so that something like the following will be possible:

```jsx
import { List } from '@stardust-ui/react'
import { List as VirtualizedList } from 'react-virtualized'

<List>
  { ({ renderItem }) => (
      <VirtualizedList 
        ...
        rowRenderer={args => /* render row with `renderItem` */ }  />)}
</List>
```

**Comment by jurokapsiar** [comment]
@kuzhelov please discuss with @silviuavram as he is looking into the tree virtualization

**Comment by levithomason** [comment]
Let's get some working examples for some of these proposals.  This decision will impact a lot of core patterns for us, one way or another.  I'd like to see virtualization done a couple ways and with a couple libraries before we make that call.

One concern is that we have shorthand APIs (with 4 input types) and children APIs already and adding a 6th form of component composition worries me a bit.  I'd like to see if we can simplify the API surface with real world usages.

**Comment by levithomason** [comment]
For clarity, try items with random sizes, stateful items that change size, resize the list container vertically and horizontally.  Ensure we support auto height and all changes to items and container layout that are reasonably expected in a UI for a list (and other virtualized components).

**Comment by silviuaavram** [comment]
https://github.com/stardust-ui/react/pull/1697 first prototype. Virtualization with https://react-window.now.sh/#/examples/list/variable-size. No accessibility (may be implemented later if we will go further with this). The tree is virtualised, with dynamic number of open items. Passing size before rendering (to react-window) is a limitation.

**Comment by jurokapsiar** [comment]
List and Chat can be virtualized when Children API is uesed. closing
