### ISSUE TITLE
Improve `Form.Field` API for `control` slot

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#1648]
# Improve `Form.Field` API for `control` slot

## Problem description

Currently the `control` slot for `Form.Field` is a shorthand that defaults to `{ as: Input }` object:
https://github.com/stardust-ui/react/blob/424ba3c8b20835921b79cf1591115b98623c7fef/packages/react/src/components/Form/FormField.tsx#L74

where `Input` is a Stardust component. This means the API for using a different control, let's say our `Slider` component and the primitive `<input type="range" />` is going to be:

- for custom components:
```jsx
<Form.Field label="Age" control={{ as: Slider }} id="age" />
```
- for primitives:
```jsx
<Form.Field label="Age" control={{ as: 'input', type: 'range' }} id="age" />
```

However, this API is unintuitive (why is `as` prop needed?) and should be simplified.

## Proposed solution

Change the type of `control` slot from shorthand, aka `ShorthandValue<BoxProps>` (`ReactNode | Props<BoxProps>`) to:

#### 1. `React.ReactNode`

The example above would become:
- for custom components:
```jsx
<Form.Field label="Age" control={<Slider />} id="age" />
```
- for primitives:
```jsx
<Form.Field label="Age" control={<input type='range' />} id="age" />
```

#### 2. `React.ElementType | 'button' | 'input' | 'select' | 'textarea'`

For this approach we need to add `type` props as well to the `Form.Field`. The example above would become:

- for custom components:
```jsx
<Form.Field label="Age" control={Slider} id="age" />
```
- for primitives:
```jsx
<Form.Field label="Age" control='input' type='range' id="age" />
```

similar to SUIR: https://github.com/Semantic-Org/Semantic-UI-React/blob/048bd35ad310bcae6e6ebc8cd9c5cf52f5b927f2/src/collections/Form/FormField.js#L153

### MVP
https://codesandbox.io/s/stardust-ui-example-x3x54

**Comment by levithomason** [comment]
Per offline meeting on this, let's start with proposal number 2 👍 Additional bonus, you can copy patterns and examples from SUIR.

**Comment by levithomason** [comment]
Yes, we'd like to change this.  We aren't getting any complaints nor time to do so, so housekeeping for now.

Contributions welcome.
