### ISSUE TITLE
implement meeting notes icon

### ISSUE THREAD

**Issue by MartinPtrl** [microsoft/fluent-ui-react#1649]
### Problem description
I'm missing an icon for Meeting Notes button.

### Proposed solution
Exactly the same icon as there already is in angular codebase
![image](https://user-images.githubusercontent.com/5823300/61302376-f74ed980-a7e5-11e9-9688-952292eadae2.png)

**Comment by codepretty** [comment]
Added in this PR: https://github.com/stardust-ui/react/pull/1953

fyi/ @MartinPtrl
