### ISSUE TITLE
Button `size` prop or `small`/`large` variations

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#1671]
### Problem description

We need a proper design term to suggest users they can use the `Button` component at a smaller size or with a more compact style.

This prop will only impact styling, functionality and accessibility stay the same

#### 1. string prop `size`

- API:
```jsx
<Button size="small" />
```
- implemented in:
  - [SUIR](https://react.semantic-ui.com/elements/button/#variations-size)
  - [Material UI](https://material-ui.com/api/button/#props)
  - [Reactstrap](https://reactstrap.github.io/components/buttons/)
  - [Bootstrap](https://getbootstrap.com/docs/4.2/components/buttons/#sizes)
  - [Evergreen](https://evergreen.segment.com/components/button/)
  - [Carbon Components React](http://react.carbondesignsystem.com/?path=/story/buttons--default)

#### 2. boolean prop `compact`

- API:
```jsx
<Button compact />
```
- alternative names:  `small`, `fitted` ?
- implemented in:
  - [SUIR](https://react.semantic-ui.com/elements/button/#variations-compact)
  - [Vuetify](https://vuetifyjs.com/en/components/buttons#api) (search for `small` or `large`)
  - [Blueprint](https://blueprintjs.com/docs/#core/components/button.props) (search for `small`)

**Comment by levithomason** [comment]
Let's add our size ramp 👍 
- small, smaller, smallest
- large, larger, largest
