### ISSUE TITLE
No space between label and checkbox in RTL

### ISSUE THREAD

**Issue by 96andrei** [microsoft/fluent-ui-react#1676]
## Bug Report
The checkbox component (toggle=true) has incorrect layout in RTL.

### Steps
1. Go to https://stardust-ui.github.io/react/components/checkbox
2. Scroll to the toggle example
3. Click RTL.

Expected: There should be some space between the label and the control.
Actual: There is no space.

### Version
0.34.1

**Comment by miroslavstastny** [comment]
The space is implemented using `:before` on the text. But the text has `dir="auto"` which causes `:before` to be on the left if LTR label is used:
![image](https://user-images.githubusercontent.com/9615899/61444590-f637bc80-a94b-11e9-98c7-62aaa3f1e352.png)

Works correctly for RTL labels:
![image](https://user-images.githubusercontent.com/9615899/61444880-8d9d0f80-a94c-11e9-9914-cae6ab0457b6.png)
