### ISSUE TITLE
Padding breaks Icon in Input 

### ISSUE THREAD

**Issue by lucivpav** [microsoft/fluent-ui-react#1678]
## Bug Report
Consider an Input component with an icon. When you apply a style with padding to it, the icon is not padded appropriately.

### Steps
```
<Input
    fluid
    icon="search"
    iconPosition="start"
    placeholder="Search"
    style={{ padding: "6px 60px 6px 60px" }}
  />
```
### Expected Result
![image](https://user-images.githubusercontent.com/10930160/61447082-92fc5900-a950-11e9-9cbd-c84a452f59cb.png)

### Actual Result
![image](https://user-images.githubusercontent.com/10930160/61446898-3c8f1a80-a950-11e9-8cb7-b248c6fbe2ca.png)

### Version
0.34.1

### Testcase
https://codesandbox.io/s/stardust-ui-example-g6mbe

**Comment by mnajdova** [comment]
The `icon` in the `Input` component has position `absolute`, because we want it to appear on top of the input. So instead of `padding`, try using `margin` and it should work as expected. Also, always use the `styles` prop instead of `style` when you use Stardust components.

**Comment by lucivpav** [comment]
The same issue happens with `clearable` prop.
![image](https://user-images.githubusercontent.com/10930160/62042033-59073e80-b1fd-11e9-9db0-4e5f43ea49e8.png)
