### ISSUE TITLE
Teams theme: Popup pointing styles still broken with focus trap

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluent-ui-react#1679]
## Bug Report

After fix in #1433 Popup pointing with focus trap is still broken:

![image](https://user-images.githubusercontent.com/9615899/61449687-c392c180-a955-11e9-89bf-4a0608c3e031.png)

### Version
0.34.1

### Testcase
https://codesandbox.io/s/popup-pointing-with-focustrap-broken-styles-8kenr

**Comment by layershifter** [comment]
It seems that is was fixed by #1565:

![image](https://user-images.githubusercontent.com/14183168/61450025-76631f80-a956-11e9-96f7-be5f435f6ae7.png)

**Comment by layershifter** [comment]
Fixed in `0.35.0`.
