### ISSUE TITLE
TreeItem does not apply styles to subtree slot

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluent-ui-react#1681]
### Steps
Style `subtree` slot in `TreeItem` in provider:
```jsx
TreeItem: {
  subtree: ({ variables }) => {
    return {
      border: '2px solid red',
    }
  },
},
```

### Expected Result
Subtree has a red border:
![image](https://user-images.githubusercontent.com/9615899/61459849-ed57e280-a96d-11e9-9db8-6c528ae615fb.png)

### Actual Result
Styles are not applied to the subtree slot.

### Version
0.34.1

### Testcase
https://codesandbox.io/s/subtree-styles-not-applied-3pltj

**Comment by miroslavstastny** [comment]
Not sure about `title` slot

**Comment by silviuaavram** [comment]
closing 'as designed' and will provide support to style items in case this pops up as higher priority than nopw.
