### ISSUE TITLE
Why fela?

### ISSUE THREAD

**Issue by echarles** [microsoft/fluent-ui-react#170]
I am wondering the reasons why `fela` has been chosen instead of e.g. `styled-components`.

I guess fela brings `state` on top of styling - Never used it, so curious to know how `stardust-ui` uses it.

**Comment by echarles** [comment]
I guess part of the answer to `why` can be found on https://github.com/Semantic-Org/Semantic-UI-React/issues/2708#issuecomment-382984665

Still, would be good to bring light in this repo.

**Comment by levithomason** [comment]
Thanks for the question.  We're not actually set on `fela` at this point.  We do know we need a library that:

- has the best perf
- includes react-native support
- includes vanilla JS support
- avoids proprietary convetions
- has a small footprint
- can be easily extended or replaced

So far in my research, fela does the best job at these things in concert.

Stardust's goal long term is not to be a React component library at all, but to offer a broad solution to UI in the form of specifications and utilities.  A bit more on that has been posted in our [/specifications](https://github.com/stardust-ui/specifications).

Once we have a final decision on our CSS in JS library (or method) of choice, we should indeed post about it.  I may include some of this response in our coming CSS in JS concept page in our [docs](https://stardust-ui.github.io/react).
