### ISSUE TITLE
Using space to activate Menu Item scrolls the page

### ISSUE THREAD

**Issue by mnajdova** [microsoft/fluent-ui-react#1708]
### Steps
Focus some menu item element and press space

### Expected Result
The element should be activated, but there should be no scrolling on the page.

### Actual Result
The element is activated, but the whole page scrolls.💣

### Short gif with the behavior
https://i.imgur.com/aIYJlOC.gif

v0.34.2

**Comment by sophieH29** [comment]
fixed https://github.com/stardust-ui/react/pull/1735
