### ISSUE TITLE
State management in-scope?

### ISSUE THREAD

**Issue by echarles** [microsoft/fluent-ui-react#171]
Upon current scope for `stardust-ui` (*), is `state management` (redux...) a target? This would be a nice needed feature.

(*)  Creating Components,  CSS-in-JS, Theming, Component API, Shorthand API, Event Stack, HTML Font Size, Parent Child Coupling

**Comment by echarles** [comment]
Food for thought: local and global state with constante https://medium.freecodecamp.org/reacts-new-context-api-how-to-toggle-between-local-and-global-state-c6ace81443d0

**Comment by levithomason** [comment]
Thanks for the question. Component state is in scope for stardust but application state is out of scope.

**Comment by echarles** [comment]
Thx for the answer.
