### ISSUE TITLE
Dialog: trigger will be unresponsive if component passed is imported from elsewhere

### ISSUE THREAD

**Issue by sushruth** [microsoft/fluent-ui-react#1713]
### Steps
1. Open this [sandbox](https://codesandbox.io/s/sd-bug-eet4e?&module=%2Fexample.js)
2. Click on "Open Dialog" button

### Expected Result
- Dialog must show up

### Actual Result
- Dialog does not open

### Version
0.34.3

### Testcase
https://codesandbox.io/s/sd-bug-eet4e?module=%2Fexample.js

**Comment by layershifter** [comment]
It's a known issue even from SUIR: your component should spread unhandled props.

```jsx
export const TriggerThis = props => (
  <Button {...props} content="Open a dialog" />
);
```

**Comment by sushruth** [comment]
That seems to work! Thanks @layershifter
