### ISSUE TITLE
Tooltip shadow in dark theme too heavy

### ISSUE THREAD

**Issue by daisygeng** [microsoft/fluent-ui-react#1717]
### Expected Result
Should use shadow-level-2
![image](https://user-images.githubusercontent.com/48726002/61819388-d3a01a80-ae07-11e9-9ad7-3a85ec11468c.png)

### Actual Result
![image](https://user-images.githubusercontent.com/48726002/61819310-9dfb3180-ae07-11e9-895d-fcaefb500bb7.png)

cc: @codepretty

**Comment by notandrew** [comment]
Looks like it's fixed now. The CSS looks correct and the correct styles are being applied.  Reactivate if you see this again. @daisygeng
