### ISSUE TITLE
Quick Start page is not relevant

### ISSUE THREAD

**Issue by silviuaavram** [microsoft/fluent-ui-react#1759]
Usage example is wrong. There is now `arrow right` icon in the Teams theme. Also The content is `Theming` not `FAQ`.

**Comment by lucivpav** [comment]
What is wrong with the example's use of `arrow right` icon?

**Comment by silviuaavram** [comment]
I tried to use it outside the docsite and no right arrow is rendered.

**Comment by lucivpav** [comment]
Relevant issue #1593

**Comment by lucivpav** [comment]
The icon issue will be resolved as part of this effort #1764
