### ISSUE TITLE
Remove Font Awesome icons from docs

### ISSUE THREAD

**Issue by lucivpav** [microsoft/fluent-ui-react#1762]
### Problem description
There are examples in docs that use Font Awesome icons. If such an example snippet is run on e.g. Codesandbox, the icons are not rendered at all, due to missing Font Awesome. The Font Awesome should not be used in docs at all.

### Proposed solution
1. Do not merge with Font Awesome theme in docs
2. All icon usages are from Teams theme
3. Icons that are not in Teams theme, but are used in docs, should be added to Teams theme

**Comment by layershifter** [comment]
Was fixed in #1764.
