### ISSUE TITLE
Add bluetooth icon

### ISSUE THREAD

**Issue by fesouzamsft** [microsoft/fluent-ui-react#1773]
### Problem description
The list of icons in Stardust does not have the Bluetooth icon (and outline):

![image](https://user-images.githubusercontent.com/12650823/62724667-5f997100-b9c8-11e9-9169-c7cd609408a1.png)

We need it for the "add a room" screen.

**Comment by jurokapsiar** [comment]
There is now a way to add icons on consumer side. Closing this issue.

**Comment by notandrew** [comment]
@jurokapsiar - closing this issue, looks like it was intended to be closed by you earlier...
