### ISSUE TITLE
Could a useStardustThemeContext Hook be added?

### ISSUE THREAD

**Issue by KyleBastien** [microsoft/fluent-ui-react#1802]
## Feature Request

Currently ThemeContext is exported from here:

https://github.com/stardust-ui/react/blob/3b21ea894ac8e16e15d559a888f796be9cd52718/docs/src/context/ThemeContext.tsx#L31

Could this also export a `useStardustThemeContext` Hook? This way this be composed into Functional Components more easily.

### Problem description

Currently it's a little cumbersome to compose in the current Stardust Theme Context in a Functional Component.

### Proposed solution

Add an exported Hook called `useStardustThemeContext` that looks similar to:

```
export const ThemeContext = React.createContext<ThemeContextData>(themeContextDefaults)

export const useStardustThemeContext = () => React.useContext<ThemeContextData>(ThemeContext);
```

**Comment by jurokapsiar** [comment]
The useStyles hook should be used to get computed styles. We do not want to expose internals (theme object), just the computed values
