### ISSUE TITLE
popupBehavior: tabbableTrigger with `false` not working on native tabbable element

### ISSUE THREAD

**Issue by silviuaavram** [microsoft/fluent-ui-react#1804]
## Bug Report
If the `trigger` is a tabbable element by default (`button`, `a`) and the Popup has `tabbableTrigger` as `false`, the `trigger` will still be tabbable since `popupBehavior` will not apply any `tabIndex` to it.

### Fix suggestion
Add `tabindex` as `-1` it `tabbableTrigger` is `false`.

**Comment by jurokapsiar** [comment]
discussed this offline - this should not be done because it would make the trigger focusable, which is not desired for the "popup on context" and context menu scenarios.

**Comment by jurokapsiar** [comment]
It might be ok to not add tabIndex in the popupBehavior at all if tabbableTrigger is false
