### ISSUE TITLE
Issue template sandbox points to semantic-ui-react

### ISSUE THREAD

**Issue by dvdzkwsk** [microsoft/fluent-ui-react#1812]
The Github issue template currently recommends forking https://codesandbox.io/s/2l3n74j9y to submit a test case, but that sandbox is still on semantic-ui-react.

**Comment by lucivpav** [comment]
Also the Support question contains Semantic UI links:
* Gitter Community Chat: https://gitter.im/Semantic-Org/Semantic-UI-React
* StackOverflow: https://stackoverflow.com/questions/tagged/semantic-ui-react using the tag `semantic-ui-react`

**Comment by layershifter** [comment]
I made a new CodeSandbox template that can be intergrated into our export and used as a default:
https://codesandbox.io/s/stardust-ui-example-ulq3j

It also includes theme switching.

**Comment by lucivpav** [comment]
> I made a new CodeSandbox template that can be intergrated into our export and used as a default:
> https://codesandbox.io/s/stardust-ui-example-ulq3j
> 
> It also includes theme switching.

Can we change the description to _A template for Stardust UI React issues_?
![image](https://user-images.githubusercontent.com/10930160/63581901-4ed82600-c598-11e9-9af7-eced84bbca26.png)

Also, the `example.js` seems heavy, can we have a clear comment describing where one can insert their example code?

**Comment by lucivpav** [comment]
Typo in 

> This example is <del>example</del> powered by Stardust UI

**Comment by layershifter** [comment]
> Can we change the description to _A template for Stardust UI React issues_?

Sure, this can be done in `package.json`

**Comment by layershifter** [comment]
> Also, the `example.js` seems heavy, can we have a clear comment describing where one can insert their example code?

It should include something more simple, definitely
