### ISSUE TITLE
Dropdown does not respect target in Provider context

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#1818]
### Steps
open https://codesandbox.io/s/stardust-ui-example-1phxh
Try to interact with the dropdown

### Expected Result
Aria live messages are rendered in the correct document
User can open the single selection non-search dropdown when clicking on it

### Actual Result
One of the aria live regions are rendered in the main document

### Version
0.36.1

**Comment by layershifter** [comment]
Will be fixed by #1810 as `Dropdown` uses `Portal` component:

https://github.com/stardust-ui/react/blob/706cddd49a97f3dae775f0d5fa26ace8339955b5/packages/react/src/components/Dropdown/Dropdown.tsx#L520

**Comment by jurokapsiar** [comment]
Downshift also has a aria live region rendered as child of body, so that would either need to be fixed or we need to make sure that Downshift uses the same.

**Comment by silviuaavram** [comment]
Will be fixed once we update to Downshift 3.2.14.

**Comment by silviuaavram** [comment]
https://github.com/stardust-ui/react/pull/1910
