### ISSUE TITLE
[RFC] Typescript type checking options

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluent-ui-react#184]
Stardust uses Typescript, but all it's [type checking options](https://www.typescriptlang.org/docs/handbook/compiler-options.html) are disabled, which kills a lot of Typescript's power.
Enabling (some of) the checks would make the code better and it'd easier to enable them in the early stage of the project.

I went through the list of compiler options which could be worth considering and also checked tsconfig in other projects which use Typescript.

option | project A | project B | [ionic/react](https://github.com/ionic-team/ionic/blob/master/react/tsconfig.json) | [vscode/src](https://github.com/Microsoft/vscode/blob/master/src/tsconfig.json) | [rxjs](https://github.com/ReactiveX/rxjs/blob/master/tsconfig.base.json) | description
-- | -- | -- | -- | -- | -- | --
`noImplicitReturns` |   | true | true | true | true | Report error   when not all code paths in function return a value.
`noImplicitAny` (1) |   | true | true |   | true | Raise error on   expressions and declarations with an implied `any` type.
`noImplicitThis` (1) |   |   |   | true | true | Raise error   on `this` expressions   with an implied `any` type.
`noUnusedParameters` |   | true | true |   |   | Report errors   on unused parameters.
`noUnusedLocals` |   | true | true | true |   | Report errors   on unused locals.
`alwaysStrict` (1) | true |   |   | true |   | Parse in strict mode and emit `"use   strict"` for each source file
`strictNullChecks` (1) |   |   |   |   |   | In strict null   checking mode, the `null` and `undefined` values are not in   the domain of every type and are only assignable to themselves and `any` (the one exception being   that `undefined` is   also assignable to `void`).
`strictFunctionTypes` (1) |   |   |   |   | true | Disable   bivariant parameter checking for function types.
`strictPropertyInitialization`   (1) |   |   |   |   |   | Ensure   non-undefined class properties are initialized in the constructor. This   option requires `--strictNullChecks` be enabled in order to take effect.

(1) part of `--strict`
Default value for all options is `false`.

Can we think of what would make sense to be enabled?

**Comment by kuzhelov** [comment]
There was a TS compilation problem caused by `--strict` flag which has enabled all these checks for our project (#158) - as a result, we've had to (temporarily) disable it.

Agree that proposed strategy to incrementally introduce this functionality back (by means of these discrete flags) is a good option for us, so that we will be able to carefully weight benefits and potential TS compilation problems (increased compilation time, overall stability of compilation process) with each option being introduced 👍

**Comment by levithomason** [comment]
Note, we resolved to disable strictNullChecks for now and align closely to projects A and B.

**Comment by miroslavstastny** [comment]
@kuzhelov - AFAIK the problem in #158 was caused by `strictNullChecks`, so, hopefully the others should be safe for build performance.
`stringNullChecks` is disabled in other projects as well, we are not going to enable it in stardust for now.

**Plan:** `noImplicitReturns` is now enabled by #185, I am going to enable others (`noImplicitAny`, `noUnusedParameters`, may be `noUnusedLocals` and `noImplicitThis`) - we agreed to enable one more each week and monitor it's impact on the build.

**Comment by jurokapsiar** [comment]
not valid anymore
