### ISSUE TITLE
Add MenuItem disabled prop

### ISSUE THREAD

**Issue by silviuaavram** [microsoft/fluent-ui-react#186]
## Feature Request
As a result of https://github.com/stardust-ui/react/pull/83 , it is required for the MenuItem Component to handle the `disabled` prop and act accordingly.
### Problem description
The `disabled` prop has been added to MenuItem, in order to be used to add the `aria-disabled` attribute on the element. However, adding this prop should trigger the actual disabled behaviour for the menu item, similar to how Button behaves, for instance.
### Proposed solution
Provide functionality to the MenuItem component in order to make it act similarly to Button when it receives the `disabled=true`

**Comment by silviuaavram** [comment]
@kuzhelov should we close this one? the PR was merged and the MenuItem has been given the `disabled` handled prop.

**Comment by levithomason** [comment]
Yes, please close issues when PRs are merged.  Do this automatically by adding `Fixes #186` in plain text to the PR description.

**Comment by miroslavstastny** [comment]
This issue was created as a follow-up of #83. In that PR, `disabled` prop was added to `MenuItem` but no support for disabled menu item was implemented.
