### ISSUE TITLE
Input with dark theme blends with background

### ISSUE THREAD

**Issue by bryceg** [microsoft/fluent-ui-react#1870]
## Bug Report
Using dark theme on an input causes it to use the same color as the body background, and it blends in becoming invisible.  

### Steps
1) go to: https://stardust-ui.github.io/react/components/input/definition
2) Change theme to teams dark

### Expected Result
Input should have a more gray background, similar to dropdown component

### Actual Result
Becomes invisible

![image](https://user-images.githubusercontent.com/2497408/64049619-3f258800-cb2a-11e9-8e0a-4d49273b4692.png)

![image](https://user-images.githubusercontent.com/2497408/64049637-4e0c3a80-cb2a-11e9-864b-d2f63294b7f3.png)

![image](https://user-images.githubusercontent.com/2497408/64049666-6aa87280-cb2a-11e9-9cb9-b124b71d6310.png)

![image](https://user-images.githubusercontent.com/2497408/64049683-7ac05200-cb2a-11e9-8486-86fe86a9126b.png)

### Version
0.37.0

**Comment by codepretty** [comment]
We addressed this issue by adding an `inverted` prop in https://github.com/stardust-ui/react/pull/1684

![image](https://user-images.githubusercontent.com/828692/64281152-5f2cc100-cf07-11e9-869b-1c90caedff0c.png)

**Comment by codepretty** [comment]
We have a task to do the same thing for Dropdown.

**Comment by levithomason** [comment]
Hm, shouldn't the default input and dropdown styles just work in dark mode?  No other component requires adding `inverted` when in dark mode.

Note, I don't think the OP is saying that they put in on a random background, but that they put it in dark mode:

![http://g.recordit.co/mkoKYKQI4o.gif](http://g.recordit.co/mkoKYKQI4o.gif)

**Comment by bryceg** [comment]
@levithomason correct, I have made no other styling changes except setting the theme to dark mode.

**Comment by codepretty** [comment]
There are Teams Design needs to support 2 different color backgrounds for Input in each theme depending on the background the component sits on. The `inverted` prop was added to account for support for both scenarios. @bryceg is there a certain scenario you are trying to support that isn't working? Have you tried using the `inverted` prop? If it's just in the component playground viewers, perhaps the background color of container should be swapped. Because the same problem happens in Teams default theme when `inverted` is selected.

![image](https://user-images.githubusercontent.com/828692/64464757-f63b7980-d0bd-11e9-8dcb-bf059772c0a8.png)

**Comment by bryceg** [comment]
@codepretty I don't think I want to use the inverted prop, as then the input is hidden on the light theme.  

I'm not setting any styling on my page background or the input component, just swapping the theme to "dark" based on the users Teams theme setting using the Provider component <Provider={theme}>...<Input/></Provider>.  
I would not expect to need to set inverted to true on this one component type, based on the state of the theme being dark or light.  The others seem to handle this just fine (Dropdown, Checkbox, etc.)

**Comment by codepretty** [comment]
We shouldn't update the background of the Input. The update should to be the background of the playground area.

**Comment by wictorwilen** [comment]
It seems like the default background for the dark theme is invalid and not the actual inputs. Here's two examples:
From the stardust-ui site:
![image](https://user-images.githubusercontent.com/5854279/65428387-9a3e5800-de14-11e9-841d-7079de4c9edf.png)
 
And from a custom component in a Teams configuration dialog:
![image](https://user-images.githubusercontent.com/5854279/65428452-ae825500-de14-11e9-9540-b2f6eb5a0db9.png)
And the light version:
![image](https://user-images.githubusercontent.com/5854279/65428507-c6f26f80-de14-11e9-9544-c7aacc340416.png)

**Comment by levithomason** [comment]
>We shouldn't update the background of the Input. The update should to be the background of the playground area.

@codepretty, note that the background of the playground area is the dark mode body background color.

**Comment by codepretty** [comment]
Yep. Creating a PR to address https://github.com/stardust-ui/react/issues/1478 which should fix this issue as well.
