### ISSUE TITLE
Wrong secondary button border in Firefox and Safari

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#188]
### Steps
Open https://stardust-ui.github.io/react/components/button
Scroll to Emphasis variant
Observe the secondary button border.

### Expected Result
Chrome:
![image](https://user-images.githubusercontent.com/13742664/45094062-85fcbf80-b11a-11e8-847d-a854a8339ee7.png)

### Actual Result
Firefox and Safari:
![image](https://user-images.githubusercontent.com/13742664/45093971-5352c700-b11a-11e8-8343-89ed8b2b7cdb.png)

### Version
0.5.0

**Comment by notandrew** [comment]
fixed with #216
