### ISSUE TITLE
Popper in Tooltip always executes positioning code

### ISSUE THREAD

**Issue by lucivpav** [microsoft/fluent-ui-react#1880]
## Bug Report

The `Tooltip`'s `Popper`'s positioning code is always executed, even if the tooltip content is not visible to the user. This is a performance issue if we have many `Tooltip` components.

### Expected Result
The content positioning code is only executed when the content is visible to the user.

### Actual Result
The content positioning code is executed even if the content is not visible 💣

### Version
0.37.0

**Comment by layershifter** [comment]
A bit rephrase:
We _should_ render `children`, we _should not_ execute positioning stuff in `Popper` until it's visible.
