### ISSUE TITLE
[RFC] Dialog: rename to modal

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluent-ui-react#1889]
Originally posted by @levithomason: https://github.com/stardust-ui/react/pull/1852#issuecomment-527228173

***

I don't think `modal={false}` makes sense for our Dialog since it is strictly a modal Dialog component only.  Its slots and usages dictate that it only works for the modal Dialog use cases.  It is always intended for "interrupting the users workflow".  It cannot reasonably serve any other "dialog" use cases such as a Popup, Date picker, etc.

A general purpose "dialog" for all use cases would just be a "window" component, basically a portal with no slots and little to no styling.  I think we should have specific components for the dialog use cases, hardcode the correct modal behaviors, and provide props for the optional parts.

Per ARIA:

**[Dialog](https://www.w3.org/TR/wai-aria-1.1/#dialog)** _(Doesn't describe our `Dialog`)_
- A descendant window of the primary window of a web application (Alert, Message, Popup, etc)
- Focus may move outside

**[Dialog (Modal)](https://www.w3.org/TR/wai-aria-practices/#dialog_modal)** _(Describes our `Dialog`)_
- Content outside is inert (cannot interact with it)
- Optionally has a backdrop/overlay
- Optionally closes on outside click
- Usually for interrupting the users workflow
- Focus cannot move outside

**✓** always, **×** never, **−** sometimes

| Feature                        | Dialog | +Modal Behavior |
|--------------------------------|--------|--------|
| Focuses an element inside      | ✓      | ✓      |
| Circular tab nav within        | ✓      | ✓      |
| Focus can leave dialog         | −      | ×      |
| Inert content outside          | −      | ✓      |
| Visible backdrop               | −      | −      |
| Close on outside click         | −      | −      |
| Close on ESC                   | −      | ✓      |

The modal behavior is a specific implementation of a Dialog where most features are hard coded.  The only features that remain optional are whether the backdrop is visible and whether it closes on outside click.

Rendering a Stardust Dialog without modal capabilities doesn't make sense and is an invalid interaction model for the component.  So, we should consider a props API that follows the **+Modal Behavior** column above.

### Modal vs Dialog

Have a look through all Dialog and Modal links in the [Open UI component matrix](https://open-ui.org/analysis/component-matrix).  There is consistency in all implementations that use the name "Modal".  They indicate a dialog with this particular anatomy and modal behavior.

The things called "Dialog" include modal dialogs, toast messages, popups, and invalid modal dialog cases.  The term dialog is not consistent nor clear in the wild.

Propose we also rename this component to `Modal`.  Although it is intended to describe a behavior in the aria specs, in the real world it is used to describe a component with the same anatomy, appearance, and behavior as what we've implemented.

## Proposed API

Note that in all cases of this component the content is to remain inert.  This is done by the backdrop intercepting clicks, whether opaque (on) or transparent (off).

**`<Modal />`** 
Inert outside, show backdrop, close on outside click.  Default behavior acts just as you'd expect a modal dialog to behave.

**`<Modal backdrop={false} />`**
Inert outside, transparent backdrop, close on outside click.  Propose the backdrop stay in the DOM so that it can intercept clicks but just made transparent.  This is because even when no backdrop is shown the content outside is still supposed to be inert.

**`<Modal closeOnOutsideClick={false} />`**
Inert outside, show backdrop, do not close on outside click.  Here we just ignore clicks on the backdrop, but it is still visible and in the DOM.

**`<Modal backdrop={false} closeOnOutsideClick={false} />`**
Inert outside, transparent backdrop, no not close on outside click.

## Conclusion

I think calling our component a "Modal" would make it much more clear to the community.  It also makes it more clear why it has the props it has and why it is lacking other features.

This also leaves room for us to implement other specific components for the other "dialog" components, like a date picker, popup, alert, tool window, etc.

We may also consider / prototype a lower level Dialog component which would allow configuration for all these use cases.  Sounds much like the [`Portal`](http://react.semantic-ui.com/addons/portal) component in SUIR which powers the Modal and Popup there.

**Comment by levithomason** [comment]
This looks good, thanks for extracting.  Closing for housekeeping though conversation and voting should continue.
