### ISSUE TITLE
Support Popup in Toolbar menu

### ISSUE THREAD

**Issue by joheredi** [microsoft/fluent-ui-react#1894]
### Problem description
Currently Toolbar component's (overflow) menu doesn't allow triggering popups from the (overflow) menu, popup support would have the following requirements:

### Proposed solution
Support triggering popups from Toolbar (overflow) menu keeping in mind that:
* (Overflow) menu should remain open when popup is opened

### MVP
[Fork, update, and replace this sandbox if you can show the proposed solution]:
https://codesandbox.io/s/stardust-ui-example-8ismt

**Comment by jurokapsiar** [comment]
Fixed by #1927, closing the issue. Target release 0.39
