### ISSUE TITLE
Focus stolen when under <Text as="label"

### ISSUE THREAD

**Issue by stuartlong** [microsoft/fluent-ui-react#1914]
## Bug Report
When a <Text as="label> element has both a <textarea> and a <div contenteditable="true"> child, then it is impossible to correctly focus the contenteditable div. When trying, the textarea always steals the focus.

### Steps
1. Create a textarea and contenteditable div as children of a <Text as="label"> element
2. Click into the contentediable div

### Expected Result
The user's cursor is placed inside the div

### Actual Result
The user's cursor is automoved to the textarea

### Version
0.38.0

### Testcase
https://codesandbox.io/s/stardust-ui-example-nroip

**Comment by mnajdova** [comment]
The same thing happens if you replace the `Text` component with the `label` tag: https://codesandbox.io/s/stardust-ui-example-uuxwb I don't understand how this is a issue with the `Text` component in Stardust.

**Comment by mnajdova** [comment]
Not sure what you are trying to achieve, but maybe @jurokapsiar or someone from the accessibility team help you with the structure.

**Comment by jurokapsiar** [comment]
I think this is not caused by Stardust or React - my assumption is that it is the default behavior of <label> html element, that when you click on it, it renders the input (text area) inside of it or the one that it is attached to.

@stuartlong can you please explain what do you want to achieve? Do you want to be able to dynamically edit the label for a text area?

**Comment by stuartlong** [comment]
I mean, the issue is that there are two focusable elements within the "label" text and one of them is simply not focusable. But, as you have pointed out, it seems to be a browser issue. We have a sufficient workaround on our end, just wanted to make you aware if it was a Stardust issue. Thanks for the help though.
