### ISSUE TITLE
Chat: Message action getting clipped on the top for the first message

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#1923]
### Steps
Create chat with overflow scroll. After scrolling down and hovering on the first message, the message action toolbar gets clipped.

### Expected Result
Toolbar is correctly repositioned

### Actual Result
Toolbar is clipped

### Version
0.38.0

### Testcase
https://codesandbox.io/s/stardust-ui-example-rngyn

**Comment by lucivpav** [comment]
Can you clarify on which issue you mean? If I scroll down the bottom in the example, I can no longer hover the first message (the message is no longer visible). There are two issues that come to my mind:
1. Hover the first message without scrolling, the action toolbar gets clipped (the top part is not visible)
2. When scrolling down to the bottom, hover the second message (the one with a lot of text), the action toolbar is not visible (it is probably rendered on top, out of viewport)
