### ISSUE TITLE
[RFC] Provider: Font sizes from Teams' theme siteVariables are too large

### ISSUE THREAD

**Issue by alinais** [microsoft/fluent-ui-react#193]
### Steps
Provider: is now getting siteVariables from Teams' theme. Font sizes are too large.

### Expected Result
The font sizes are as expected expected.

### Actual Result
Font sizes are too large, with following changes, they look much closer to the existing Teams app: 
bodyFontSize = "1rem" => "1.4rem"
htmlFontSize = "10px" => "14px"

### Version
0.5.0

**Comment by mnajdova** [comment]
The htmlFontSize is already 14px. Maybe we should just change it from 14px -> 10px and stay with the bodyFontSize to be 1rem?

**Comment by kuzhelov** [comment]
this has been addressed by #204 - now for `Teams` theme the same font sizes (and strategy to apply them) are used
