### ISSUE TITLE
[RFC] Input - need to support type="number"

### ISSUE THREAD

**Issue by alinais** [microsoft/fluent-ui-react#194]
### Problem description

Input: only supports text type.
we need type="number" 
defaultValue only accepts string (and not integer)

**Comment by mnajdova** [comment]
The input already support type='number'. 

![image](https://user-images.githubusercontent.com/4512430/45175719-634bd300-b20e-11e8-834f-9d4eeb0cc219.png)
 
Is there some additional logic that we should implement if the type is number?
