### ISSUE TITLE
Popup in Toolbar Menu is closed unintentionally

### ISSUE THREAD

**Issue by lucivpav** [microsoft/fluent-ui-react#1944]
## Bug Report
Looks like a bug in FocusZone
Note this can be resolved by https://github.com/stardust-ui/react/pull/1927/files/55d1425fcc05cbdceda0e9b587381956f7971e6d#diff-4d4eca3f4d470d78be4f0424c96bf8a7

Test should be added so that this issue does not happen again.

### Steps
1. Navigate to Toolbar Usage section
2. Observe the Popup in Menu example
3. Open the Popup
4. Click on Popup background
5. Observe Menu (and Popup) was closed

### Expected Result
Menu and Popup stays open

### Actual Result
Menu (and Popup) was closed

### Version
#1927

**Comment by jurokapsiar** [comment]
closed as there was no action
