### ISSUE TITLE
The textarea as the content to the Chat.Message does not respond to Up and Down arrow keys as expected

### ISSUE THREAD

**Issue by 123gafmann** [microsoft/fluent-ui-react#1947]
### Steps
The textarea as the content to the Chat.Message UI component does not respond to Up and Down arrow keys as expected

An example show casing the scenario: https://codesandbox.io/embed/stardust-ui-example-wu6yo

steps:
1) Type some multi line text in the textarea which is inside the chat message list.
2) Press Up or Down key to try to move the cursor.

### Expected Result
The cursor should move Up and Down along the text line.

### Actual Result
The cursor does not move at all for Up and Down keys 💣

### Version
stardust UI @0.38.1

### Testcase
[Fork, update, and replace this sandbox to show the bug]:
https://codesandbox.io/s/stardust-ui-example-8ismt

**Comment by jurokapsiar** [comment]
This needs to be fixed on consumer side by stopping the propagation of events in onKeyDown:

```
<textarea rows={10} onKeyDown={(e) => e.stopPropagation()} /> // TOOD: check correct key codes
```
Please note that propagation should be stopped only for desired keys - arrows, pgup, pgdown, home, end probably.
