### ISSUE TITLE
[RFC] Radio - create group options and add event handlers

### ISSUE THREAD

**Issue by alinais** [microsoft/fluent-ui-react#195]
### Problem description
A clear and concise description of what the problem is. Ex. I have an issue when [...]

### Proposed solution
A clear and concise description of what you want to happen. Add any considered drawbacks.

### MVP
[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

**Comment by jurokapsiar** [comment]
fixed in https://github.com/stardust-ui/react/pull/229
