### ISSUE TITLE
Error in Try it example causes focus loss

### ISSUE THREAD

**Issue by lucivpav** [microsoft/fluent-ui-react#1952]
## Bug Report

If you write an invalid code in an example's Try it box, it will cause the focus to be lost (its moved to document body). Looks like it happens because tree is unmounted.

![image](https://user-images.githubusercontent.com/10930160/65259920-c9e41c00-db05-11e9-8ee0-ffad09638eb8.png)

### Steps
1. Go to any example
2. Press Try it
3. Type something that leads to build error
4. Observe focus was lost

### Expected Result
Focus is preserved

### Actual Result
Focus has moved to document body

### Version
0.38.1

**Comment by layershifter** [comment]
It seems that issue exists somewhere in our code: https://codesandbox.io/s/focused-ride-oldnf

**Comment by lucivpav** [comment]
<del>The `unstable_hot` prop is causing it.</del>

**Comment by lucivpav** [comment]
Where can I find the most recent version of the `react-source-render` repo? The version `3.0.0-5` that is being used in Stardust.

I tried looking at the repo page: https://github.com/layershifter/react-source-render
The `master` branch has version `2.0.0-beta.6`,
while the `wip-wip` branch is on version `3.0.0-2`

**Comment by layershifter** [comment]
Pushed latest changes to `wip-wip`, actually we need to adopt this package under `docs-components`.

Good finding. It seems that there can be a mistake under `useHMRId`. But even in the worst way it shouldn't remount the tree...
