### ISSUE TITLE
Remove usage of global document and window from components

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#1964]
## Bug Report

Following components still contain references to global document/window:
- Dropdown.tsx line 814
- Loader.tsx line 105
- Popup.tsx line 276
- Toolbar.tsx lines 182, 189, 191
- ToolbarRadioGroup.tsx line 103

Also, check focusUtilities, lines 430 and 440 which also use the globals, but just as a fallback value.

### Version
0.39.0

**Comment by layershifter** [comment]
Linking #1963 as it contains all failures.
