### ISSUE TITLE
Dropdown multi-select: Misalignments on Chrome@Android

### ISSUE THREAD

**Issue by klapouchy90** [microsoft/fluent-ui-react#1965]
### Steps
Display multiselect dropdown (image+content) on Chrome @ Android, select an item
![image](https://user-images.githubusercontent.com/15650086/65504225-d16d4180-dec6-11e9-8b93-181138dd790f.png)
![image](https://user-images.githubusercontent.com/15650086/65504273-db8f4000-dec6-11e9-96a0-7238fb09865a.png)

### Expected Result
Selected item and the dropdown are styled appropriately

### Actual Result
Selected item pill as well as the items in the dropdown are misaligned
![image](https://user-images.githubusercontent.com/15650086/65504371-12fdec80-dec7-11e9-9d29-08bb53277939.png)

**Comment by silviuaavram** [comment]
![Screenshot 2019-10-23 at 3 47 47 PM](https://user-images.githubusercontent.com/11275392/67399445-8d945780-f5ac-11e9-8817-79bd1704d4a9.png)
 
The docsite example looks fine.

Is there something I'm missing related to repro steps?

**Comment by silviuaavram** [comment]
@klapouchy90 please reopen this with repro steps / details.
