### ISSUE TITLE
Tooltip: with `disabled` on `Button` will not hide

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluent-ui-react#2021]
### Steps
1. Open CodeSandbox: https://codesandbox.io/s/stardust-ui-example-mocbw?fontsize=14
2. Hover a button
3. Move cursor out of it

### Expected Result
Tooltip will hide

### Actual Result
Tooltip is visible 💣

![tooltip](https://user-images.githubusercontent.com/14183168/66557491-42148f00-eb52-11e9-8750-63bd079cea3f.gif)

### Version
0.40.0

**Comment by francescopalmiotto** [comment]
@layershifter 
I quickly tried to debug the issue and unfortunately it seems to be way tougher than it looks.
**Basically onMouseLeave even doesn't always fire on a disabled button**.

The same issue was reported more than 4 years ago in the react repo and it's still open.
https://github.com/facebook/react/issues/4251

One way to fix it would be to wrap the button in a `<div>` and add the event listeners on the div.

**Comment by mnajdova** [comment]
Exactly as you've said @francescopalmiotto mouse leave will not fire on disabled button. The recommendation is whenever you have disabled element, if you want tooltip around it, to add the tooltip on a wrapper element. I've seen this recommendation in Bootstrap too  -  https://v4-alpha.getbootstrap.com/components/tooltips/#overview (there is a comment in the overview).

Will make sure to add this on the Tooltip doc's site.
