### ISSUE TITLE
docs site is down

### ISSUE THREAD

**Issue by brambow** [microsoft/fluent-ui-react#2029]
### Steps
Navigate to https://stardust-ui.github.io/react/

### Expected Result
See the docs

### Actual Result
No site is displayed
![image](https://user-images.githubusercontent.com/6227786/66879668-2adc0400-ef8d-11e9-994d-2e177434b3b3.png)

**Comment by sushruth** [comment]
Would love to see it back live again.

**Comment by jsuddsjr** [comment]
I see that changes are afoot. Workaround, clone the repo, `npm run build:docs`, and host locally for now?

**Comment by layershifter** [comment]
You can access docs here: https://microsoft.github.io/fluent-ui-react/
Sorry for inconvenience.

**Comment by sushruth** [comment]
Is there any announcement or roadmap for the name change and what it signifies? Just to keep myself informed.

**Comment by jurokapsiar** [comment]
the docs site is up again and redirects for both repo and documentation should work. clarification will follow shortly, closing the issue.
