### ISSUE TITLE
Can't pass opacity in variables prop to description of Attachment

### ISSUE THREAD

**Issue by js-sapphire** [microsoft/fluent-ui-react#2068]
## Bug Report
Currently, the opacity of description of Attachment is 0.5 and passing opacity through variables prop does not work. However, using styles prop do.

### Steps
Try setting opacity of description in Attachment to any value through variables prop.

### Version
0.38.3

**Comment by jurokapsiar** [comment]
Fixed in https://github.com/microsoft/fluent-ui-react/pull/2012, will be released in 0.41
