### ISSUE TITLE
SplitButton- JAWS - Virtual cursor mode - focus is lost after closing the menu

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluent-ui-react#2082]
## Bug Report

Repro only for these examples:
Icon and Content, Toggle Button

### Steps
Run JAWS.
1. Navigate to “More options” button menu in cursor mode. (for example mentioned above) 
2. space to expand menu 
3.  press ESC key and observe the issue

### Expected Result
focus is back in SplitButton, like for example in first example: Split Button

### Actual Result
focus is lost to the body

**Comment by kolaps33** [comment]
first attempt of fix was done here: https://github.com/microsoft/fluent-ui-react/pull/2094

**Comment by silviuaavram** [comment]
https://github.com/microsoft/fluent-ui-react/pull/2145 fixed it
