### ISSUE TITLE
SplitButton - screen readers - cursor/browse mode and disabled splitButton

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluent-ui-react#2083]
Go through the points and fix it or report it as JAWS bugs. Please test it as well with NVDA and VoiceOver.
14.	[Screen readers]: In cursor mode, when navigating to “New conversation” disabled button JAWS reads as “New conversation button menu  Unavailable  menu”. (Expected: Screen reader should read as “New conversation split button menu Unavailable)
15.	[Screen readers]: On “More options” disabled button Screen reader reads as “Unlabeled 1 button menu Unavailable menu” (this will not repro when point 4 is fixed)

**Comment by silviuaavram** [comment]
@kolaps33 on `14` it reads `new conversation split button unavailable` and on `15` it reads `more options button menu unavailable menu`.

Looking at the HTML and aria attributes for both buttons can you suggest what is wrong with them?

**Comment by kolaps33** [comment]
Retested now with NVDA and JAWS and could not reproduce original reported issues.
