### ISSUE TITLE
[RFC] Popup position

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#210]
## Popup position

We are currently implementing a `Popup` component (#150) and in the first version of the API we're still undecided how to define the `position` of the `popup` relative to its `trigger` element (the element that created the `popup` and offers relevant info about positioning it).

### Problem description
In our terminology, element has four sides - `start`, `end`, `top`, `bottom`.

In current proposal that is introduced by #150 the popup's positioning is defined by the `position` prop, a string that can take the following values:

`'top-start' | 'top' | 'top-end' | 'bottom-start' | 'bottom' | 'bottom-end' | 'before-start' | 'before' | 'before-end' | 'after-start' | 'after' | 'after-end'`

As one can see, popup position consists of two words:
1. the first one defines `popup` position relative to `trigger` element:
- `top`
- `bottom`
- `before`
- `after`
2. the second one defines which side of the popup and trigger are aligned:
- `start` in `top-start` and `bottom-start` means `start` sides are aligned
- `end` in `top-end` and `bottom-end` means `end` sides are aligned
- `start` in `before-start` and `after-start` means `top` sides are aligned
- `end` in `before-end` and `after-end` means `bottom` sides are aligned

It is confusing that `start` and `end` are used for both vertical and horizontal alignment. This supports flex terminology (which uses `start`/`end` for both main and cross axis) as well as `popper.js`, but in Stardust context it collides with `start` and `end` which we use for `left` and `right`.
 
#### [1. Popper.js popup](https://popper.js.org/popper-documentation.html#Popper.placements)

Valid placements are: `'auto' | 'top' | 'right' | 'bottom' | 'left'`
Each placement can have a variation from this list: `'-start' | '-end'`

#### [2. MDN web docs: Popup Guid: Positioning]( https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/PopupGuide/Positioning) 

Single Word Alignment Values | Example
-- | --
`before_start`: The left side of the popup is aligned with the left side of the anchor, and the bottom of the popup is aligned along the top of the anchor. Equivalent to `topleft bottomleft` | ​![screen shot 2018-09-10 at 15 08 04](https://user-images.githubusercontent.com/5442794/45304936-8bdb1200-b519-11e8-93ff-5bbab12dba26.png)
`before_end`: The right side of the popup is aligned with the right side of the anchor, and the bottom of the popup is aligned along the top of the anchor. Equivalent to `topright bottomright` | ​![screen shot 2018-09-10 at 15 08 13](https://user-images.githubusercontent.com/5442794/45304940-909fc600-b519-11e8-9a82-6383f543e553.png)
`after_start`: The left side of the popup is aligned with the left side of the anchor, and the top of the popup is aligned along the bottom of the anchor. This value is commonly used for menu buttons. Equivalent to `bottomleft topleft` | ​![screen shot 2018-09-10 at 15 08 20](https://user-images.githubusercontent.com/5442794/45304948-94cbe380-b519-11e8-841f-4e6620fca691.png)
`after_end`: The right side of the popup is aligned with the right side of the anchor, and the top of the popup is aligned along the bottom of the anchor. Equivalent to `bottomright topright` | ​![screen shot 2018-09-10 at 15 08 26](https://user-images.githubusercontent.com/5442794/45304953-985f6a80-b519-11e8-8f67-8656d99016fe.png)
`start_before`: The top edge of the popup is aligned with the top edge of the anchor, and the right side of the popup is aligned along the left side of the anchor. Equivalent to `topleft topright` | ​![screen shot 2018-09-10 at 15 08 32](https://user-images.githubusercontent.com/5442794/45304957-9b5a5b00-b519-11e8-80fb-3da17fd2f8cc.png)
`start_after`: The bottom side of the popup is aligned with the bottom side of the anchor, and the right side of the popup is aligned along the left side of the anchor.  Equivalent to `bottomleft bottomright` | ​![screen shot 2018-09-10 at 15 08 37](https://user-images.githubusercontent.com/5442794/45304964-9eede200-b519-11e8-93cb-13e6d92d69df.png)
`end_before`: The top edge of the popup is aligned with the top edge of the anchor, and the left side of the popup is aligned along the right side of the anchor. This value is used for submenus. Equivalent to `topright topleft` | ​![screen shot 2018-09-10 at 15 08 41](https://user-images.githubusercontent.com/5442794/45304977-a614f000-b519-11e8-8652-c68fe85d275d.png)
`end_after`: The bottom side of the popup is aligned with the bottom side of the anchor, and the left side of the popup is aligned along the right side of the anchor. Equivalent to `bottomright bottomleft` | ![screen shot 2018-09-10 at 15 08 47](https://user-images.githubusercontent.com/5442794/45304988-ab723a80-b519-11e8-8ae1-fc1489a0f627.png)

#### [3. Jquery popup overlay](http://dev.vast.com/jquery-popup-overlay/)

1 | 2 | 3 | 4
-- | -- | -- | --
horizontal | `center' / 'left' / 'right' / 'leftedge' / 'rightedge'` | 'center' | Sets horizontal position. Options `leftedge` and `rightedge` can be used only for tooltips, and will align the tooltip to the left or right edge of the opening element (`openelement`).
-- | -- | -- | --
vertical | `'center' / 'top' / 'bottom' / 'topedge' / 'bottomedge'` | 'center' | Sets vertical position. Options `topedge` and `bottomedge` can be used only for tooltips, and will align the tooltip to the top or bottom edge of the opening element (`openelement`).

#### [4. JqueryUI popup](http://api.jqueryui.com/position/)

(default: "center")
Type: String

Defines which position **on the element being positioned** to align with the target element: `horizontal vertical` alignment.

A single value such as `right` will be normalized to `right center`, `top` will be normalized to `center top` (following CSS convention). Acceptable horizontal values: `left`, `center`, `right`. 

Acceptable vertical values: `top`, `center`, `bottom`. Example: `left top` or `center center`. Each dimension can also contain offsets, in pixels or percent, e.g., `right+10 top-25%`. Percentage offsets are relative to the element being positioned.
 
#### [5. Tippyjs popup](https://atomiks.github.io/tippyjs/)
 
A tooltip can be placed in four different ways in relation to its reference element. Additionally, the tooltip can be shifted:
`'Top' | 'Bottom' | 'Left' | 'Right' | 'Top-Start' | 'Top-End'`
![screen shot 2018-09-10 at 15 35 42](https://user-images.githubusercontent.com/5442794/45307042-52f16c00-b51e-11e8-8d7e-44b32d55e2a1.png)

#### [6. Bootstrap popup](https://getbootstrap.com/docs/4.1/components/popovers/)

**Four directions**
Four options are available: `'top`, `right`, `bottom`, and `left` aligned.

#### Proposal 1

Without checking other libraries, we introduce new terminology:
- for position: `'above' | 'below' | 'before' | 'after'`
- for alignment: `'start' | 'end' | 'top' | 'bottom'`
- add third word `-aligned`?

That results in combinations like:
`position="above-start"`
`position="above-start-aligned"`

Other ideas is renaming the prop to `placement`: that results in combinations like:
`placement="above-start"`
`placement="above-start-aligned"`

#### Proposal 2

Do we really need to combine the two into a single property? Wouldn't it make sense to leave them separate? Drawback is it allows conflicting combinations.

#### Proposal 3

Current proposal of #150 

#### Proposal 4
See above: [2. MDN web docs: Popup Guid: Positioning]( https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/PopupGuide/Positioning)

**Comment by levithomason** [comment]
Excellent write up, thanks!  I would go with proposal 2, `position` prop and `align` prop.  This is also consistent with other component props we have.

**Comment by levithomason** [comment]
Per our call, most agree with proposal 2 so let's start there.

**Comment by bmdalex** [comment]
implemented in #150
