### ISSUE TITLE
Components: add onChange-like callback

### ISSUE THREAD

**Issue by silviuaavram** [microsoft/fluent-ui-react#2119]
## Bug Report
Some components do not have the proper `onChange` type callbacks. For example `Menu` does not have `onActiveIndexChange`. Also Tree etc.

### Expected Result
Components should have these callbacks for the controlled props.

**Comment by levithomason** [comment]
We also need to have this in a conformance test to ensure the naming, callback signature, and behaviors are consistent.

There is a decision to be made about how we do this for collection components vs single components as well.  Example, a Menu (with items) vs something like an Input.
