### ISSUE TITLE
Reference to document is breaking serverside rendering

### ISSUE THREAD

**Issue by kobber** [microsoft/fluent-ui-react#2182]
## Bug Report

We're attempting to serverside render our app, but a few references to `document` in `
mergeProviderContexts.ts` makes it throw:
```
ReferenceError: document is not defined at mergeProviderContexts 
```
I found a previous commit in the project that removed references to `window` and `document`, I'm guessing with the intent of allowing serverside rendering, but in this specific case the usage was allowed with the use of `// eslint-disable-line no-undef`.

Am I missing something? Is there a yet-to-be documented configuration that would allow serverside rendering? Or is it simply not supported by the project yet?

### Version
0.42.0

**Comment by dashkevych** [comment]
I am getting the same issue when trying to use it in NextJS.

**Comment by levithomason** [comment]
@jurokapsiar We'll need this fixed for our own upcoming SSR requirements as well.  We have an `isBrowser()` utility that we use for preventing access to unguarded `document` and `window` globals.

Could you please add a task for us to implement an ESLint rule to ensures we're checking for browser before accessing `document`?

**Comment by layershifter** [comment]
> Could you please add a task for us to implement an ESLint rule to ensures we're checking for browser before accessing `document`?

We have already this, but as was mentioned in the issue originally we silenced it 💣 

I think that it will be a good thing to add a project test with Next.JS to be sure that our code can be bundled with SSR tools.
