### ISSUE TITLE
I want a behavior similar to https://microsoft.github.io/fluent-ui-react/focus-trap-zone but I want to focus on elements outside the focus trap zone too on tab or shift+tab. Please suggest.

### ISSUE THREAD

**Issue by mayank2013** [microsoft/fluent-ui-react#2185]
### Problem description
A clear and concise description of what the problem is. Ex. I have an issue when [...]

### Proposed solution
A clear and concise description of what you want to happen. Add any considered drawbacks.

### MVP
[Fork, update, and replace this sandbox if you can show the proposed solution]:
https://codesandbox.io/s/stardust-ui-example-8ismt

**Comment by jurokapsiar** [comment]
@mayank2013, the purpose of the trap zone is to not allow moving focus outside of the trap zone. Please provide more clear scenario. What do you want to achieve?

**Comment by jurokapsiar** [comment]
closing as there is insufficient information
