### ISSUE TITLE
Dialog focus on dismiss does not work when containing an Input with autofocus

### ISSUE THREAD

**Issue by davyrwoo** [microsoft/fluent-ui-react#2209]
## Bug Report
When Dialog content contains an Input with autoFocus, the default behavior for focus on dismiss does not work. 

Here is an example:
https://codesandbox.io/embed/fluent-ui-example-jbz4b?fontsize=14&hidenavigation=1&theme=dark

This situation comes from the need to have focus on the Input when the dialog is opened, which is a common pattern for accessibility. autoFocus has to be used in cases where there is a headerAction on the dialog - the Dialog's default focus behavior goes to the header action instead of the Input. 

Removing autoFocus will fix the focus behavior on dismiss, however it does not meet the accessibility requirement for focus on the Input when the dialog is opened.

### Steps
Create a Dialog that has content that contains an Input with autoFocus.
Use Keyboard navigation to activate the dialog
Use Keyboard navigation to close the dialog

### Expected Result
When dismissed, the focus should land on the element that triggered the dialog (as outlined in [focusTrap behavior ](https://microsoft.github.io/fluent-ui-react/focus-trap-zone#usage))

### Actual Result
Focus is undefined when closing the dialog

### Version
0.42.0

**Comment by jurokapsiar** [comment]
Custom focus handling provided by Fluent UI is not deisnged to work with native HTML auto focus mechanism. Instead of it, please follow the best practices descirbed for the component: "Do use trapFocus prop to control focus trapping behavior." - specifically the firstFocusableSelector prop of trapFocus config - https://microsoft.github.io/fluent-ui-react/focus-trap-zone#usage

**Comment by jurokapsiar** [comment]
```jsx
    <Input id="my-input" />;
...
      <Dialog
        trapFocus={{ firstFocusableSelector: '#my-input' }}
```
