### ISSUE TITLE
Space at the beginning/end of the string in Text content is ignored in Popup component

### ISSUE THREAD

**Issue by jelenamarjanovic95** [microsoft/fluent-ui-react#2215]
If there is a space at the beginning or end of the text content in a popup, it will be ignored. Can repro for LTR and RTL. Example:
`    <Popup
       trigger={<Button icon="more" content="Click me" />}
       content={
         <Flex>
            <Text>Jelena Marjanovic</Text>
            <Text> 5+, </Text>
         </Flex>
       }
     />
`
Screenshots:
LTR: ![image](https://user-images.githubusercontent.com/30659878/71985787-84ba3600-322b-11ea-8b60-699c2bae30a6.png)
RTL: ![image](https://user-images.githubusercontent.com/30659878/71985799-8dab0780-322b-11ea-9177-c9eca5df0405.png)

**Comment by mnajdova** [comment]
This is how html/react behaves... We have two options how we can fix this:

Children API: 
```
import React from 'react'
import { Button, Popup, Flex, Text } from '@fluentui/react'

const PopupExample = () => (
<Popup trigger={<Button icon="more" content="Click me" />} content={ <Flex> <Text>Jelena Marjanovic</Text> <Text>&nbsp;5+&nbsp;</Text> </Flex> } />
)

export default PopupExample

```
Shorthand API:
```
import React from 'react'
import { Button, Popup, Flex, Text } from '@fluentui/react'

const PopupExample = () => (
<Popup trigger={<Button icon="more" content="Click me" />} content={ <Flex> <Text>Jelena Marjanovic</Text> <Text content={`\xa05+\xa0`}/> </Flex> } />
)

export default PopupExample

```
