### ISSUE TITLE
Need an svg icon for 'gif' button

### ISSUE THREAD

**Issue by omkarsravan** [microsoft/fluent-ui-react#226]
Looking to create a button with a svg icon, like so: 
 <img width="40" alt="screen shot 2018-09-13 at 3 51 09 pm" src="https://user-images.githubusercontent.com/39198343/45520152-e1f3c380-b76c-11e8-8536-8ce7cb4b325f.png">
But I don't see an Icon that is an equivalent to this. Any help?

**Comment by kuzhelov** [comment]
@omkarsravan, this is a broader issue we are currently focused on to resolve (#230). Please, consider to look on this feature request to review the work that is already done - I will introduce status updates there as well.
