### ISSUE TITLE
Custom renderer for Tree element shorthands is called with referentially unstable props.

### ISSUE THREAD

**Issue by mifrdlik** [microsoft/fluent-ui-react#2295]
## Bug Report
The attached sandbox contains a Tree with a section and one item in the section. The shorthand collection is a stable object -- it is created upon mount and its address never changes. Yet the custom renderer (lines 19 and 46) detects 6 props that change nevertheless:["contentRef","siblings","onTitleClick","onFocusParent","onFocusFirstChild","onSiblingsExpand"]

### Steps
1. Use the Tree component to render the same shorthands on every render.
2. Use a custom renderer callback for these shorthands that memoizes the TreeItem component based on the props from the callback parameter.
3. Observe memo fail due to 6 props that are never referentially equal.

### Expected Result
["contentRef","siblings","onTitleClick","onFocusParent","onFocusFirstChild","onSiblingsExpand"] are referentially stable and React.memo can be used without filtering out unstable props in the prop equality handler.

### Actual Result
["contentRef","siblings","onTitleClick","onFocusParent","onFocusFirstChild","onSiblingsExpand"] are not referentially stable and have to be filtered out in order for React.memo to work properly.

### Version
0.43.0

### Testcase
https://codesandbox.io/s/fluent-ui-example-41jrj

**Comment by mbman** [comment]
This also affects other components like Popup, Dropdown and Toolbar

**Comment by mbman** [comment]
Also Dropdown possibly
