### ISSUE TITLE
RFC: Clarify logic and naming around styling and themes

### ISSUE THREAD

**Issue by hughreeling** [microsoft/fluent-ui-react#257]
### Problem description
Multiple areas around this are currently confusing to new users.
1) Very unclear what variables are available and how they affect a particular component
2) Naming is particular issue:
  Why aren't 'Site variables' - 'Theme variables'
  What is different between styles, variables and props on a component and how do they influence it
3) DocSite doesn't currently represent the theme and how it's variables are handled (we hardcode to 'teams' theme and make it appear those variables are always available). 

### Proposed solution
We need to look again at both logical structure and naming.
Some ideas:
Don't allow site / component variables to be same as css attributes (i.e. color / border) are NOT allowed - prefer instead themeColor / buttonColor
Rename site variables - Theme Primatives?
On components rename variables stylingVariables
Introduce some best practise naming conventions
Improve DocSite to represent mulitple theme and show variables more clearly
Investigate if we can represent theming as a object i.e.

Theme
   - themeColor : red
   - themeborder : none
    /Menu
      - menuColor : blue
      - menuStyle : italic

**Comment by kuzhelov** [comment]
Absolutely agree with each point of the Problem Description section. Have some thoughts around the resolution section, though:
- ` prefer instead themeColor / buttonColor`
  - suppose that we will chose the approach on naming variables with the component name being included: `buttonColor`, `iconBorder`, etc. This naming strategy could introduce quite a lot of maintainability problems to theme author, as with each renaming of the component (and we have quite a few in the recent time - but more realistic scenario is when some part of the component's logic is segregated as separate component. This will result in necessity to rename all the related variables, and this step is rather to be avoided). The same thought applies to the naming approach suggested for the `theme as an object` point (just this part, do not objecting the whole point in general)
- `Rename site variables - Theme Primatives?`
  - seems that we could start we smaller steps, and rename to something that is in the midst, like 'themeVariables'
- `On components rename variables stylingVariables`
  - to me it seems that it won't deliver the idea that those are theming aspect - maybe I am missing something, but not completely sure how this name improves the `variables` name we are using now, specifically, at which aspect it is more clear?
- `Improve DocSite to represent mulitple theme and show variables more clearly`, `Introduce some best practise naming conventions`
  - 👍 👍 👍 

---- 
To conclude, it seems that for the sake of obtaining progress we could start with introducing changes related to how the concept is represented in docs (as everyone has generally the same vision on that) - to make it more apparent to the client how these style customization pieces fit into the overall picture, - and pay additional thought to the 'renaming' part in the meanwhile.

Please, let me know about your thoughts.

**Comment by levithomason** [comment]
I think this topic is too large and we'll need to break it down to make any meaningful progress.  Example, consider the work involved in just the palette color names.  We'll need similar investigation and thinking on site variables, component variables, design terms, etc.

Suggest we close this issue and target one of these specific topics at time.

**Comment by hughreeling** [comment]
Closing issue.  Most of the points are either raised or already addresses in different PR.
