### ISSUE TITLE
react-popper has a forbidden dependency for Microsoft

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#263]
## Bug Report

We're using `react-popper` npm package to create `Popup` components with correct positioning around the trigger elements.

This package has a dependency on `create-react-context`, a package that **specifically excludes Microsoft (among other corporations) from the list of users** : [react-popper license](https://github.com/jamiebuilds/license).

**Therefore, Microsoft cannot use Stardust starting with `v0.5.2`.**

#### 1. Use `react-popper v0.9.2`

`v0.9.2` is the last stable `react-popper` version that didn't have a dependency on `create-react-context`, as you can see in: [feat: New react-popper API #117](https://github.com/FezVrasta/react-popper/pull/117).

We can update our `package.json` `"react-popper": "^1.0.2",` to `"react-popper": "^0.9.2",` and go from there.

**Drawbacks:**
- the API has changed  drastically from `v0.9.2` to `v1.0.2` (hence the major change) so we need to reimplement the `Popper` integration in our `Popup` implementation;
- no support, we're exposing ourselves to existing bugs in `react-popper v0.9.2`;
- we won't have the fixes for the bugs `react-popper` had until `v0.9.2`;

#### 2. Use `popper.js` directly and reimplement `react-popper` React layer
We can take a look at `react-popper` implementation of the `React` layer on top of `popper.js` and try implement ourselves only the bits we need for our `Popup` scenarios.

**Drawbacks:**
- will take the most time as there is plenty of work to be done here; this will be like a small library;
- we're basically reinventing the wheel since it's the same work as `react-popper`.

#### 3. Implement custom `Popup` positioning
`Semantic UI React` already implements custom positioning for `Popup` and we were initially relying on that: [SUIR Poppup.js](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/modules/Popup/Popup.js)

**Drawbacks:**
- the implementation in SUIR is suboptimal and incomplete;
- needs further work to handle all positioning cases (RTL, fitting in viewport, etc) and extensive testing.

**Comment by bmdalex** [comment]
Feedback much appreciated
@levithomason @mnajdova @alinais @miroslavstastny @kuzhelov

**Comment by kuzhelov** [comment]
@Bugaa92 here is a commit where he license of this package has been reverted back to true MIT one:

https://github.com/jamiebuilds/create-react-context/commit/f31c9edb9a1f93d5e673de5ea8b1e09a46f9b407#diff-9879d6db96fd29134fc802214163b95a

**Comment by bmdalex** [comment]
addressed in #264
