### ISSUE TITLE
Popup should support controlled mode / ContextMenu component

### ISSUE THREAD

**Issue by musingh1** [microsoft/fluent-ui-react#265]
### Problem description
We need a way to be able to override the open state of the Popup. e.g. when clicking on the items in the popup, we need to close the popup - 
![image](https://user-images.githubusercontent.com/22622723/45897799-fa776580-bd8c-11e8-97de-ed8cac5e0ed8.png)

### Proposed solution
Provide a way to say that the popup is closed now. Note - We still want to re-use the document click behavior from the popup.

### MVP
Not sure yet how to allow it. Probably, we can provide some callbacks through the component ref like fabric - https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Popup/Popup.types.ts.
Or
May be support menu as a shorthand prop in the popup, and have a prop to close the popup on item select. 
Or
I am sure this is a common requirement. Probably, create a separate ContextMenu component.

**Comment by kuzhelov** [comment]
@musingh1, thanks for posting this issue! At the moment we are working on PR that will address this problem.

**Comment by kuzhelov** [comment]
closing the issue as now it is already possible - Popup supports controlled mode:

```jsx
class Foo extends React.Component {
  ....
  render() {
     // Foo controls the state of the Popup
     <Popup open={this.state.isPopupOpen} ... />
  }
}
```
