### ISSUE TITLE
Stardust is unconsumable for TS client project with no --skipLibCheck flag

### ISSUE THREAD

**Issue by kuzhelov** [microsoft/fluent-ui-react#276]
### Steps
- create test app project: `create-react-app --scripts-version=react-scripts-ts`
- add Stardust as a dependency: `yarn add @stardust-ui/react`
- reference some components from Stardust in `App.tsx`
- try to build the project

### Expected Result
Project builds successfully.

### Actual Result
Project fails to build 💣

### Version
0.6.0

**Comment by kuzhelov** [comment]
According to preliminary debugging takeaways: 
- this problem is caused by compiler providing shorthand paths instead of relative ones for Stardust `.d.ts` files (when Stardust package is built prior to its publishing)
- our ad-hoc gulp plugin (that is aimed to substitute shortcut paths with relative ones) currently targets only the paths that start from `src` (this was done intentionally at initial stages, when we've seen this problem for src only). 

We might tweak gulp plugin's behavior to address broader set of path issues (actually, just tweak config), also might try to play with TS config.

**Comment by levithomason** [comment]
Noting this is present in the latest 0.7.0 as well.
