### ISSUE TITLE
Select component

### ISSUE THREAD

**Issue by aichi** [microsoft/fluent-ui-react#289]
## Component for Select box

There should be visual component which supports styling and renders as a HTML Select element. Similar to one used e.g. in Microsoft Teams application for device selection during call.

**Comment by levithomason** [comment]
Hi @aichi, what about the Dropdown component, #388?  It is planned to also support single selection as a Select does.  Would this fit the use case you're proposing or are you proposing to have a Select in addition to the Dropdown component?

The notable difference I see is that the Select you're proposing strictly uses the `select` element while the Dropdown uses custom markup and styling to appear as an advanced select component. The motivation for this is that the `select` element cannot be styled or customized, so a custom component is used instead.

**Comment by jurokapsiar** [comment]
this is a duplicate of #584
