### ISSUE TITLE
Popup is not opening on trigger's 'enter' key press

### ISSUE THREAD

**Issue by kuzhelov** [microsoft/fluent-ui-react#295]
## Bug Report

Popup is not displayed when `Enter` is pressed while trigger element is focused.

### Steps
- open Stardust Docs page, navigate to Popup: https://stardust-ui.github.io/react/components/popup
- for the first (default) example - focus on button and press `Enter`

### Expected Result
- alert message is displayed
- popup is opened

### Actual Result
- alert is displayed
- popup IS NOT opened

### Version
0.8.0

**Comment by jurokapsiar** [comment]
in my case, when I commented the alert() in the example, even space started to behave in a strange way - it opened the popup and closed it immediately. please check this as well.

**Comment by kuzhelov** [comment]
closing as this one is fixed by #304
