### ISSUE TITLE
The button when added as a media in a selectable list, does not inherit the styles (background/color etc.) from the list item

### ISSUE THREAD

**Issue by musingh1** [microsoft/fluent-ui-react#300]
### Steps
![image](https://user-images.githubusercontent.com/22622723/46377608-e31e5f00-c64d-11e8-841f-e8ce1fb8dd56.png)

### Expected Result
Probably the button should inherit the background when inside a list item. (Probably I can achieve this using text property, but just wanted to confirm if that is the recommended way.)
When the item is selected, the button should be inverted in color.

### Actual Result
The button does not change color and background when the item is selected.

### Version
latest (0.8.0)

**Comment by levithomason** [comment]
The suggested approach to this is to apply the proper props to the button to achieve the style you need.  Why?

1. Parents cannot responsibly override the styles of all possible children.
1. There is currently no dedicated concept for something like "list item action"

For `2`, this is something that might prove useful and something we may consider adding.  We just need more examples of this in the UI world to do so.  In that case, you'd have a dedicated `action` prop where you could define the button.  Similar to the Attachment's `action`:

https://stardust-ui.github.io/react/components/attachment#slots-attachment-action-example
