### ISSUE TITLE
Reimplement RadioGroupItem keyboard navigation

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#306]
### Problem description
In PR #287 we have introduced a fix for making keyboard navigation work properly for `RadioGroup` items that contain `Input` elements. It consists of introducing a new prop called `shouldFocus: boolean` to `RadioGroupItem`.

Fix details:
- when we navigate by keys we set `shouldFocus` to `true` for the currently checked `RadioGroupItem`;
- after the currently checked `RadioGroupItem` updates (React's `componentDidUpdate` hook), we try focus (by actively calling `focus` on the ref element).

### Proposed solution
My fix is a workaround that is aligned with the new keyboard navigation designs concepts proposed by @smykhailov in #256. Once that work is merged and stable we can leverage it for implementing 
keyboard navigation for `RadioGroup`.

**Comment by levithomason** [comment]
Focus and keyboard accessibility seem to be working correct:

https://stardust-ui.github.io/react/components/radio-group/definition
