### ISSUE TITLE
Popup: close popup when user clicks outside of the popup

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#307]
## Feature Request

There needs to be a possibility to close popup when the user clicks on the document (or focuses element outside of the popup). 

### Problem description
When the user opens a popup and clicks on the document outside of the popup, the popup remains open.

### Proposed solution
Use Portal or portal-like functionality as it was before the refactoring.

**Comment by bmdalex** [comment]
This used to work, @kuzhelov I know it was removed as part of Popup refactoring, can we add it back?

**Comment by alinais** [comment]
#410
