### ISSUE TITLE
Popup: the positioning and aligning of the Popup around the trigger are limited

### ISSUE THREAD

**Issue by mnajdova** [microsoft/fluent-ui-react#313]
### Problem description
The positioning and aligning of the Popup relative to the trigger are limited. For example, the following position is not possible to be defined with the current properties:

![image](https://user-images.githubusercontent.com/4512430/46488141-26b9ca00-c802-11e8-9471-6defaf13b0b8.png)

### Proposed solution
We have currently prop `align` which indicates where should the popup be placed relatively to the trigger. We are missing property that will indicate with which part of the Popup should the trigger be aligned (top, center, start, end, bottom).

**Comment by levithomason** [comment]
The Semantic Popup allows for positioning on any side.  It also also allows for adding vertical and horizontal offsets to align it perfectly.  It has had many iterations for a few years. 
 Let's start with this API:

`position`: https://react.semantic-ui.com/modules/popup/#variations-position
`offset`: https://react.semantic-ui.com/modules/popup/#variations-offset
