### ISSUE TITLE
Move FocusTrapZone related Popup properties to behavior

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#354]
## Feature Request

To be consistent with FocusZone, FocusTrapZone should be defined in the behavior. Move the trapFocus and focusTrapZoneProps properties from Popup to PopupBehavior.

This can be done once https://github.com/stardust-ui/react/pull/239 is merged.

**Comment by levithomason** [comment]
@jurokapsiar #239 is merged
