### ISSUE TITLE
Button: `type` is working incorrecly

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluent-ui-react#374]
## Bug Report

Hi guys, I'm building now some stuff based on Stardust specifications and I found the design problem.

![image](https://user-images.githubusercontent.com/14183168/47203623-a199ed80-d389-11e8-9570-159189ccf561.png)

![image](https://user-images.githubusercontent.com/14183168/47203731-f89fc280-d389-11e8-91a1-688b1fc58d20.png)

However, the `type` prop is reserved in `button`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

### Steps

```jsx
<Button content="Click here" type="reset" />
```

### Expected Result

```html
<button class="ui-button" aria-disabled="false" type="reset">
  <span class="ui-slot">Click here</span>
</button>
```

### Actual Result

```html
<button class="ui-button" aria-disabled="false">
  <span class="ui-slot">Click here</span>
</button>
```

### Version
0.9.1

**Comment by hughreeling** [comment]
As far as I know there are several discussions indirectly about this.
There need to be more clarify about if 'default' , 'primary' and
'secondary' really all need to exist...  and if we shouldn't just use
<Button content="click" primary />

**Comment by levithomason** [comment]
+1 to boolean prop API for this
