### ISSUE TITLE
Popup should support a prop to allow being exclusive

### ISSUE THREAD

**Issue by musingh1** [microsoft/fluent-ui-react#379]
### Problem description
If I have multiple popup triggers on the screen, I want a way to restrict the user to open only one popup at a time
![image](https://user-images.githubusercontent.com/22622723/47234847-01919380-d38c-11e8-87da-2576065a92ff.png)

### Proposed solution
Whenever a Popup is opened check if there is any other existing Popup open and close it.

**Comment by levithomason** [comment]
We need to support something like "closeOnDocumentClick" as well.  That would also solve this issue.  It should also be the default behavior.

**Comment by sophieH29** [comment]
We already have this feature request https://github.com/stardust-ui/react/issues/307
Can we then close this one to avoid duplicates?

**Comment by musingh1** [comment]
I guess we can close this one as dupe of https://github.com/stardust-ui/react/issues/307
