### ISSUE TITLE
Dropdown component

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluent-ui-react#388]
Add basic implementation for Dropdown component.

![image](https://user-images.githubusercontent.com/9615899/47333859-ce4d4e00-d684-11e8-8db6-c804ea4f0fbd.png)

## API
For now, use an API similar to SUIR ([example](https://react.semantic-ui.com/modules/dropdown/#types-multiple-search-selection)):
```jsx
<Dropdown multiple search items={[ ... ]} />
```

Based on prototype in #334:

Since we only support "search" and "multiple", make these required for now.
Dropdown will only include the Input and associated List (menu), no buttons, field label, etc.

Separate `active` items from `selected`:
- `active` means the item is in input box as an active value
- `selected` means the item is highlighted in the menu

More keyboard handlers:
 - click to open
 - esc to close

### className
Additional classes.

### fluid
Boolean to make it stretch as much as container allows.

### items
Shorthand to provide items in the dropdown. Similar to providing ListItems as shorthand inside list.
<img width="429" alt="screen shot 2018-10-25 at 11 16 27" src="https://user-images.githubusercontent.com/11275392/47490325-c9d19280-d848-11e8-8629-7a82db9a8d0c.png">

### label
Shorthand to provide a label before the dropdown.
<img width="456" alt="screen shot 2018-10-25 at 11 16 48" src="https://user-images.githubusercontent.com/11275392/47490302-c0482a80-d848-11e8-929b-84b855ba3589.png">

### multiple
Boolean to provide multi-selection functionality. Will add the active shorthands as Labels before the Input, each with 'X' icon for removal.
<img width="480" alt="screen shot 2018-10-25 at 11 17 33" src="https://user-images.githubusercontent.com/11275392/47490343-d48c2780-d848-11e8-8c83-f563ea19f61a.png">

### onChange
Callback provided to allow user to handle change. Invoked with the props and also with the active option(s), which can be either the shorthand for the active item, or the shorthand collection for the active items.

### onInput
Callback provided to allow user to handle input change in the edit text. Only makes sense if dropdown is a search. Invoked with both the props and the new value of the text in the input.

### placeholder
Text to act as placeholder, optional, in case the dropdown is a search (with text field). Makes sense only if dropdown is a search.
<img width="427" alt="screen shot 2018-10-25 at 11 17 40" src="https://user-images.githubusercontent.com/11275392/47490362-dc4bcc00-d848-11e8-9f99-968d513eecca.png">

### search
Boolean to make the dropdown able to search through the options, with autosuggestions. If false, the search input will be replaced by trigger button.

### styles
Styles that are applied on top of the default ones.

### variables
Variables that are applied on top of the default ones.

**Comment by levithomason** [comment]
Linking the PR: #334

**Comment by silviuavram** [comment]
Linking the most recent prototyp

**Comment by silviuaavram** [comment]
Linking the deployed container with the People Picker prototype: https://stardustacc2.z13.web.core.windows.net/

**Comment by jurokapsiar** [comment]
`onAddItem` and `onRemoveItem` callbacks might be handy besides `onSelect`

**Comment by levithomason** [comment]
- `onInput` should be `onSearchChange`
- `label` will be removed and a FormField would be used to add a label instead

**Comment by silviuaavram** [comment]
Linking PR https://github.com/stardust-ui/react/pull/422

Will also update API in the issue description.

**Comment by silviuaavram** [comment]
The API has been changed _slightly_ and you can view it in the Docs for the component

**Comment by silviuaavram** [comment]
defaultSearchQuery: PropTypes.string, OK
    defaultValue: PropTypes.oneOfType([PropTypes.object, PropTypes.array]), OK
    fluid: PropTypes.bool, OK
    getA11yStatusMessage: PropTypes.func, To Object getA11yStatusMessage
    getA11ySelectedMessage: PropTypes.func, -=-
    getA11yRemovedMessage: PropTypes.func, -=-
    getA11yRemoveItemMessage: PropTypes.func, -=-
    items: PropTypes.arrayOf(PropTypes.object), Remove interface, add component shorthand.
    itemToString: PropTypes.func, OK
    multiple: PropTypes.bool, OK
    noResultsMessage: PropTypes.string, OK
    onCloseIconClick: PropTypes.func, Rename onActionClick
    onCloseIconKeyDown: PropTypes.func, Rename onActionKeyDown
    onDropdownChange: PropTypes.func, Rename onChange, pass null event, inform client, issue DS.
    onInputBlur: PropTypes.func, OK for now
    onInputFocus: PropTypes.func, OK for now
    onInputKeyDown: PropTypes.func, OK for now
    onLabelClick: PropTypes.func, Go to Shorthand. Removed.
    onSearchQueryChange: PropTypes.func, OK
    placeholder: PropTypes.string, OK
    search: PropTypes.bool, OK
    searchQuery: PropTypes.string, OK
    toggleButton: PropTypes.bool, change to toggle, it will be Shorthand. false: nothing. undefined: default, shorthand: merge.
    value: PropTypes.oneOfType([PropTypes.object, PropTypes.array]), OK

**Comment by silviuaavram** [comment]
Implemented in https://github.com/stardust-ui/react/pull/422. Closing.
