### ISSUE TITLE
pxToRem() doesn't support negative values

### ISSUE THREAD

**Issue by bcalvery** [microsoft/fluent-ui-react#394]
### Steps
pass a negative value to the pxToRem function

### Expected Result
I expect a negative Rem value to be returned

### Actual Result
An error is thrown "Invalid value of: …"

### Code:
`export const pxToRem = (value: number = 0): string => {
 if (!_htmlFontSizeInPx) {
 _htmlFontSizeInPx = getComputedFontSize()
 }
 if (process.env.NODE_ENV !== 'production') {
 **if (value < 0) {
 throw new Error(`Invalid value of: '${value}'.`)
 }**
 }
 const convertedValueInRems = value / _htmlFontSizeInPx
 return `${_.round(convertedValueInRems, 4)}rem`
}`

**Comment by hughreeling** [comment]
Closely related to changes in #371.  I hope fix will be added to that.
