### ISSUE TITLE
Unable to style ListItem individual parts

### ISSUE THREAD

**Issue by silviuaavram** [microsoft/fluent-ui-react#403]
## Feature Request
Refactor the ListItem Component to make it possible to be styled individually, with individual styles for content, header, etc.

### Problem description
For the Dropdown component, I need to be able to style different parts of the ListItem when Downshift specifies a ListItem as being highlighted.

### Proposed solution
Refactor the component to support individual styling, similar to Input component.

**Comment by bmdalex** [comment]
related to #388 and #241
@sophieH29 also had issues related to styling `Layout` slots

@levithomason 
@kuzhelov 
@mnajdova 
@miroslavstastny 

we need to get on top of refactoring our layout components, more and more issues related to them not being stardust compliant.

**Comment by levithomason** [comment]
There is ongoing work to update the ListItem to have targetable layout areas for styling, #236.  There is also work to investigate reducing the amount of markup generated by using CSS Grid for layouts, #401.

The result of either of these PRs should resolve this issue.  Any work should pick up on one of these PRs.

**Comment by levithomason** [comment]
I have also relabeled this as a `bug` since it breaks the behavior pattern of a Stardust slot.

**Comment by layershifter** [comment]
Was fixed in #886.
