### ISSUE TITLE
Larger MenuItem icons overlap when using iconOnly prop

### ISSUE THREAD

**Issue by joheredi** [microsoft/fluent-ui-react#409]
### Steps
Create a Menu with a few iconOnly huge/massive MenuItems  

```tsx
const items = [
  { key: 'home', icon: {name: 'home', size:'huge' } },
  { key: 'users', icon: {name: 'users', size: 'huge' } },
  { key: 'search', icon: {name: 'search', size: 'huge'} },
]

const MenuExampleIconOnly = () => <Menu iconOnly defaultActiveIndex={0} items={items} />
```

### Expected Result
Icons should not overlap. For example, if iconOnly is ***not*** used:
![image](https://user-images.githubusercontent.com/21109913/47683341-88185300-db8c-11e8-85b4-2bf4143d1b2a.png)

### Actual Result
![image](https://user-images.githubusercontent.com/21109913/47683275-57d0b480-db8c-11e8-98ac-c86ebfce83e3.png)

### Version
0.10.0

**Comment by bmdalex** [comment]
taking this

**Comment by levithomason** [comment]
Valid bug, however, users should not be specifying size on every icon like this.  The Menu should have a `size` prop which scales the concerns of the menu.
