### ISSUE TITLE
List does not propagate selection prop to ListItem when using children prop to render

### ISSUE THREAD

**Issue by musingh1** [microsoft/fluent-ui-react#412]
### Steps
Check the children API for list selection, and remove the selection prop from <List.Item>
![image](https://user-images.githubusercontent.com/22622723/47810612-f716b880-dd00-11e8-87bb-b58e6518a5d9.png)

### Expected Result
The selection prop on list should be propagated to items

### Actual Result
The selection prop on list is not getting propagated to items

### Version
latest (0.11.0)

**Comment by levithomason** [comment]
State is never managed for children in React.  A component can only manage the state of the children if the component internally creates and controls those children.

### Solution

Use the shorthand `items` prop instead and the state will be automatically controlled.
