### ISSUE TITLE
Fix Lodash typing errors after enforcing @types/lodash

### ISSUE THREAD

**Issue by silviuaavram** [microsoft/fluent-ui-react#420]
## Bug Report
Fix Lodash typing errors after enforcing @types/lodash inside yarn.lock

### Steps
Add @types/lodash in yarn.lock or install a package that requires @types/lodash, such as Cypress.
`yarn build`

### Expected Result
Should build without errors.

### Actual Result
Approximately 20 errors are thrown at build from the non type-enforced use of lodash library in the code.

**Comment by silviuaavram** [comment]
Blocks https://github.com/stardust-ui/react/pull/418

**Comment by bmdalex** [comment]
starting on this, fyi @silviuavram

**Comment by bmdalex** [comment]
fyi @silviuavram you should be unblocked for #418 now
