### ISSUE TITLE
Align `Menu` and `Divider` components to use the `type` property values as boolean

### ISSUE THREAD

**Issue by alinais** [microsoft/fluent-ui-react#421]
### Problem description
Align `Menu` and `Divider` components to use the `type` property values as boolean. 

### Proposed solution
 Check the `Button` update, where  `primary` and `secondary` become boolean props while the `type` remains as a reserved prop.

[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
We have already PR for `Divider`: #327

**Comment by layershifter** [comment]
Picking this.

**Comment by levithomason** [comment]
#327 was closed since primary/secondary doesn't make sense in the context of a Divider.  Instead, they will have `color`s.  See #451 for the color palette and divider color work.
