### ISSUE TITLE
Typechecks on props not working

### ISSUE THREAD

**Issue by aniknafs** [microsoft/fluent-ui-react#424]
### Steps
```
import { Status } from '@stardust-ui/react'
<Status color="red" wrongProp="haha"/>
```
### Expected Result
Typescript complains about the `wrongProp` (not existing or not matching the interface). 

### Actual Result
Typescript is happy. 

Status (and other components) are extending `UIComponent<Extendable<ComponentProps>>` where `Extendable` is telling Typescript to accept any props. 

### Version
0.11.0

**Comment by levithomason** [comment]
This is working as expected.  HTML supports any prop the user wishes to pass so we cannot limit them.  Example, `<Status data-my-prop />`.
