### ISSUE TITLE
Spread the default html prop types on each component

### ISSUE THREAD

**Issue by alinais** [microsoft/fluent-ui-react#425]
### Problem description
Components props are extendable and should be strongly typed. 

### Proposed solution
Spread the W3C html props on each component. It should happen at the render time.

[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

**Comment by mnajdova** [comment]
I took a look into this, and I am not sure what we want to achieve with it. Adding DOM node props to the propTypes will flood the intellisense with attributes that may never be used. We want to advertise the properties specific for the component being used, all DOM elements will still be passed to the root of the component. If there are some properties missing in any of the component, we can take a look on adding additional props, but other then that, I don't see what would be the benefit of this. Here are some links with discussions similar to this one from SUIR: 
https://github.com/Semantic-Org/Semantic-UI-React/issues/1072#issuecomment-268848820
https://github.com/Semantic-Org/Semantic-UI-React/issues/1575
@levithomason @miroslavstastny @kuzhelov @layershifter @Bugaa92 @alinais please share your opinion on this!

**Comment by layershifter** [comment]
_My opinion:_ we should not expose all HTML props and I fully agree with the idea from https://github.com/Semantic-Org/Semantic-UI-React/issues/1072#issuecomment-268848820

**Comment by mnajdova** [comment]
@layershifter thanks for the feedback! I'll wait for a comment from few other contributors as well before closing this one. I am sure there is some reason for this request, so maybe we can at least make some clarifications at least.

**Comment by miroslavstastny** [comment]
I am against spreading html props to components' props - that would make intellisense unusable.

**Comment by mnajdova** [comment]
Based on the input of the other folks, closing this issue, as we are not going to implement it.
