### ISSUE TITLE
Implement color prop for each component that accepts colors

### ISSUE THREAD

**Issue by alinais** [microsoft/fluent-ui-react#426]
### Problem description
Some components need the color prop for better customizing. Use the color palette interface from siteVariables to achieve that.

### Proposed solution
- Implement `color` prop
- create color usage examples

for each component that accepts colors:

- [x] Divider #451 
- [x] Text #597
- [x] Header #628 
- [x] Segment #632 
- [x] Icon #651 
- [x] Label #647
- [ ] Menu
- [ ] Button
- [x] Status

**Comment by alinais** [comment]
depends on #423

**Comment by layershifter** [comment]
This issue is unblocked now because #423 was resolved 👍

**Comment by levithomason** [comment]
Considering this done for now.  We can add Menu/Button colors on request.
