### ISSUE TITLE
[Selection list] Aria-selected is not changing the state, is always false

### ISSUE THREAD

**Issue by kolaps33** [microsoft/fluent-ui-react#464]
### Steps
Testing with reader require to open it in Edge/Narrator. 
1. Navigate to the selection list item
2. press down arrow key to move to another list item
3. press down arrow key to move to another list item
4. observe aria-selected attribute or listen Narrator. 

### Expected Result
aria-selected should change state with selected item

### Actual Result
aria-selected doesn't change state based on selected item
reader doesn't narrate proper selected state

### Version
latest master, before version is v0.11.0

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by levithomason** [comment]
Confirmed.  It appears the aria prop is also not updated on click.  We need to update the accessibility behavior to set aria selected based on the item's active prop.

😕 Womp, actually we don't even have a list item `active` prop.  Let's add that first...
