### ISSUE TITLE
GridPicker component

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#488]
### Problem description
While prototyping two pickers in #480 we found out that:
- there are commonalities between two grid pickers
- we require consumers to apply accessibility knowledge that can be encapsulated in the component.

### Proposed solution
Based on the PR mentioned above, create `GridPicker` and `GridPickerItem` components that will allow user to create a grid item picker.

### MVP
#480

**Comment by levithomason** [comment]
The MVP is merged and prototype is available.  However, this component is too specific to be a Stardust component.  If a consumer requires this control, they should implement it as shown in the prototype.
