### ISSUE TITLE
Rewrite our components using `createComponent` utility

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#494]
### Problem description

We added the `createComponent` factory that is going to be used for:
- wrap 3rd party components in order to achieve Stardust capabilities (especially styling)
- creating custom Stardust components;
- rewriting existing Stardust components.

**The goal is to rewrite at lest 4-5 components using `createComponent` utility before we export it**, as we might need to make changes in the API and we want to minimize these before we expose it to users.

### Proposed solution

Here is a list of the components that can be picked up for rewriting:
- [ ] Accordion
- [ ] Attachment
- [ ] Avatar
- [ ] Button
- [ ] ButtonGroup
- [ ] Chat
- [ ] ChatItem
- [ ] ChatMessage
- [ ] Divider
- [ ] Form
- [ ] FormField
- [ ] Grid
- [ ] Header
- [ ] HeaderDescription
- [ ] Icon
- [ ] Image
- [ ] Input
- [ ] ItemLayout
- [ ] Label
- [ ] Layout
- [ ] List
- [ ] ListItem
- [ ] Menu
- [ ] MenuItem
- [ ] Portal
- [ ] Popup
- [ ] PopupContent
- [ ] RadioGroup
- [ ] RadioGroupItem
- [ ] Segment
- [ ] Status
- [ ] Text

Please update the list with a reference to your username when you pick it up. It'd be best to have one component per PR unless there are a lot of connected changes in `createComponent` API.
**e.g.:**

#### When you pick up the component:
- [ ] Text taken by @John_Doe 

#### When you finish the work related to the component:
- [x] Text fixed by @John_Doe in PR #999

Once we merge 4-5 components we will create a PR for exporting `createComponent`

**Comment by bmdalex** [comment]
fyi
@kuzhelov 
@layershifter  
@levithomason 
@miroslavstastny 
@mnajdova 

 and
@alinais 
@priyankar205 
for assigning priority

**Comment by levithomason** [comment]
See #475
