### ISSUE TITLE
Supporting generating info files for components using the renderComponent function

### ISSUE THREAD

**Issue by mnajdova** [microsoft/fluent-ui-react#502]
## Feature Request
Supporting doc generation for the components created with the createComponent function.

### Problem description
For now, react-docgen-typescript works only with class components. We need to support generating docs for the components created using the renderComponent function.

### Proposed solution
Take a look into the react-docgen-typescript library for adding a custom resolver for the props interfaces.

**Comment by levithomason** [comment]
@kuzhelov Here's the issue that corresponds to the docgen work you're doing.
