### ISSUE TITLE
Icon does not respect 'error' property, but Text does

### ISSUE THREAD

**Issue by vadimvar** [microsoft/fluent-ui-react#506]
### Steps
              <Icon
                name="exclamation"
                size="small"
                circular
                error
                styles={{ paddingTop: "0.6rem" }}
              />
              <Text error content={composeErrorMessage(error)} />

### Expected Result
Expect both icon and text to be red

### Actual Result
The actual result that happened 💣
![image](https://user-images.githubusercontent.com/45048721/48812946-82281480-ece9-11e8-97d1-17ca0ff33303.png)

### Version
x.y.z

### Testcase
[Fork, update, and replace this pen to show the bug]:
https://codesandbox.io/s/2l3n74j9y

**Comment by levithomason** [comment]
1. We need to inherit color in the icon.  We also need to set `fill` to `currentColor` so that SVG icons also inherit font colors.
1. We should then add an example to the icon page so that visual tests can catch this in the future.
