### ISSUE TITLE
RFC: switch to Babel

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluent-ui-react#508]
_Previously we've decided to switch to Babel as compiler to improve our developer experience and get benefits from Babel's ecosystem like plugins. I've separated our switch to small steps that will allow us to make this process clearly._

## 1. Switch docs

I think that our main issue now is very slow work of `yarn start` i.e. start docs and we should solve this problem firstly.

### Actions

- [x] compare the performance of `babel-loader` & `fork-ts-checker-webpack-plugin` VS `awesome-typescript-loader` with `useBabel=true`

`awesome-typescript-loader` doesn't work properly with Babel 7, consider use `babel-loader` because it faster. Requires changes in project structure as we can't use required `--
-isolatedModules` to work properly: https://github.com/babel/babel/issues/8361

### Goals

- docs will start faster (_performance_)
- errors in types should not break webpack's process: _it's really painful when everything is done and it fails on the final step._
- hot reload will work properly https://github.com/gaearon/react-hot-loader#typescript

## 2. Switch to `@babel/register`

The second step is the replacement of `ts-node` with `@babel/register` this will improve performance of all our internal scripts.

## 3. Switch to `gulp-babel`

Replace `gulp-typescript` with `gulp-babel` or even with `pika-pkg`: #1169.

### Use existing plugins

`babel-plugin-lodash` & `babel-plugin-transform-react-remove-prop-types` will allow us to reduce bundle size for consumers.

**Comment by layershifter** [comment]
https://github.com/gaearon/react-hot-loader#typescript

> As of version 4, React Hot Loader requires you to pass your code through Babel to transform it so that it can be hot-reloaded. This can be a pain point for TypeScript users, who usually do not need to integrate Babel as part of their build process.

![before](https://user-images.githubusercontent.com/14183168/50891845-ddcb7000-1405-11e9-87c4-8fdaf83a5bea.gif)

**Comment by miroslavstastny** [comment]
> Requires changes in project structure as we can't use required `-- -isolatedModules` to work properly

See also: https://github.com/babel/babel/pull/9944

**Comment by TheAifam5** [comment]
So I can confirm that `babel` did not fixed the issue. Please read this: https://github.com/babel/babel/issues/9895
