### ISSUE TITLE
Accessibility: Add keybord arrow key support for Tree component

### ISSUE THREAD

**Issue by priyankar205** [microsoft/fluent-ui-react#511]
The Tree component works with tab. We should add keyboard arrow key navigation to make it more accessible.
eg. https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-1/treeview-1a.html

**Comment by jurokapsiar** [comment]
as suggested in #479, the default `href` value on the `TreeTitle` should be removed and replaced by `Enter` and `Space` key handlers.
