### ISSUE TITLE
Keyboard navigation in RTL mode

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#513]
### Problem description
When in RTL mode, Left arrow should move focus to the next horizontal item and Right arrow to the previous.

This applies to the FocusZone as well as to keyboard action handler mapping.

### Proposed solution
Detect RTL mode from the context and if set, set appropriate flag in the FocusZone as well as flip left/right arrow key keyboard handlers.

**Comment by hughreeling** [comment]
Looked fixed by PR 656
