### ISSUE TITLE
Wrappers for Form Validation around the Stardust's form related components

### ISSUE THREAD

**Issue by mnajdova** [microsoft/fluent-ui-react#533]
### Problem description
We need to provide to the user easy to use API for validating the forms created by Stardust components.

### Proposed solution
I've taken look into several libraries for form validation and it seems that formsy-react will be the one we are going to use (open for other alternatives if someone has). We should create wrappers around our components, similar as there is for SUIR - https://github.com/zabute/formsy-semantic-ui-react This would offer the users consistent usage of the components from Stardust, when it comes around form validation.

**Comment by jurokapsiar** [comment]
This will be turned into a backlog item, we will carry the information over. Closing this.
