### ISSUE TITLE
Reorganize the Menu component proposal

### ISSUE THREAD

**Issue by codepretty** [microsoft/fluent-ui-react#546]
### Problem description
Stardust Menu component doc site has 3 Types & 22 Variations. It is confusing to navigate through and parse the examples to find what is needed.

### Proposed solution
We should have Types, Slots, Variations, and Usages with the appropriate examples. We might also want to consider having different components for some of the examples, such as Tabs and Dropdown.

I propose a hierarchy as follows:
#### Types
* Default
* Underline / Bar
* Pointing

#### Slots
* content
* icon
* with a divider (does this belong here or in usages??)
* _possibly a second icon for indicating a selected state? eg)_
![image](https://user-images.githubusercontent.com/828692/49260957-bc359c80-f3f4-11e8-96aa-064341237c0f.png)

#### Variations
* Vertical
* Fluid
* Color (would replace all the primary examples)
* Compact (w/o borders and large padding)

#### Usages
* Menu icon toolbar
* Sub menus
* _... all other necessary examples_

----

Proposing to combine examples in some cases. I believe the Pointing Menu is a good candidate. Currently, these are 2 separate examples in the doc site.

**Proposed**
![image](https://user-images.githubusercontent.com/828692/49260743-c99e5700-f3f3-11e8-81e2-6373bfd0813d.png)

**Comment by codepretty** [comment]
Should some of our Menu examples be a different component?

## Tabs component
We have an example for **Menu as a Tab List**. Is this the right place for it or should it be a new component? Some other sites have a component called **Tabs** that is different from a **Menu** component.
* Material UI
-- Tabs: https://material-ui.com/demos/tabs/
-- Menus: https://material-ui.com/demos/menus/
* Lightning Design (by Salesforce)
-- Tabs: https://www.lightningdesignsystem.com/components/tabs/
-- Menus: https://www.lightningdesignsystem.com/components/menus/

**Comment by layershifter** [comment]
### BlueprintJS

Menu: https://blueprintjs.com/docs/#core/components/menu
Tabs: https://blueprintjs.com/docs/#core/components/tabs

**Comment by levithomason** [comment]
This is much needed thanks.  We should not show all permutations of our variations in the docs.  They should serve as definitions of the component and its variations only.

Let's also add states to the menu reorg.

***

In the future, we may consider adding additional visual test cases that would remove the need for us to show permutations of props in the docs.  It may also be helpful to see an example with more "knobs" for playing with permutations at the top of the doc site for each component:

![http://g.recordit.co/d3dd8YEQR9.gif](http://g.recordit.co/d3dd8YEQR9.gif)
