### ISSUE TITLE
Docs example can be broken and merge into master without any check

### ISSUE THREAD

**Issue by mnajdova** [microsoft/fluent-ui-react#554]
### Steps
With the latest release and the changes introduced for the Editor, we introduced problems with one of the examples for the Popup which was using react-dom. Currently this is how the example looks.
![image](https://user-images.githubusercontent.com/4512430/49442366-967c0f00-f7c9-11e8-9680-d6f28b2e20f9.png)

### Expected Result
The examples on the docs should always work. We must provide some way of testing this, not just the screens of the examples, as those are tested in an isolated (popout) mode.

### Actual Result
We may introduce problems in the docs example, and those are not caught.

### Version
0.13.1

**Comment by layershifter** [comment]
We can try to render them with `SourceRender` and throw error if it happened.

**Comment by levithomason** [comment]
We had a test in Semantic UI React that simply renders all examples and ensures there were no errors.  We should do the same.

Just note that the example file needs to be rendered _through_ the `ComponentExample` opposed to render the example file source directly.  This way, we are sure the example works in the editor and not just that the example itself works.
