### ISSUE TITLE
Add consistency to position prop values: `'before' | 'after'` vs `'start' | 'end'`

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#577]
### Problem description
We have an inconsistency on how refer to items being positioned to the left vs to the right of a reference item. We're using both:

`before|after`: for `Button`, `Icon` and `Popup` components

`start|end`: for `Input`, `Label` and `Menu` (with `Menu.Item`) components

#### Solution 1:

- position: `top|bottom|left|right`
- placement (if applicable): `start|end` or `start|center|end`

Most of our components have position only on X-axis so we'd use just `left|right`.

#### "+":
- used by [Material UI](https://material-ui.com/demos/tooltips/#positioned-tooltips) and [React Bootstrap]( https://material-ui.com/demos/tooltips/#positioned-tooltips) (only position)
- intuitive and easy to grasp

#### "-":
- confusion created in RTL mode where `left|right` are reversed

#### Solution 2:
Same as solution 1 but have: `before|after` instead of `left|right`. It becomes:

- position: `top|bottom|before|after`
- placement (if applicable): `start|end` or `start|center|end`

#### "+":
- still intuitive
- no confusion in RTL mode

#### "-":
- not sure if this is a common standard

#### Solution 3: (least favorable IMO)

Same as solution 1 but have: `start|end` instead of `left|right`. It becomes:

- position: `top|bottom|start|end`
- placement (if applicable): `start|end` or `start|center|end`

#### "+":
- no confusion in RTL mode

#### "-":
- not intuitive because it's not clear if `start|end` refers to X-axis or Y-axis, wheres `before|after` suggests X-axis more clearly
- same values for `position` and `placement` will create further confusion;
- not sure if this is a common standard

**Comment by levithomason** [comment]
Following after the CSS alignment values, we will use `start` and `end` for consistency.
