### ISSUE TITLE
Add typescript examples to DocSite components

### ISSUE THREAD

**Issue by hughreeling** [microsoft/fluent-ui-react#580]
## Feature Request
Add typescript examples to DocSite. Currently only javascript code examples.

### Problem description
Currently DocSite contains only javascript examples.  Now significant number of people are coding using TypeScript and having these examples would be helpful, especially for getting started.

### Proposed solution
Add switching method between Typescript and Javascript code examples

**Comment by layershifter** [comment]
Duplicate #495 😸
