### ISSUE TITLE
AutoControlled component does not handle NOT autocontrolled state

### ISSUE THREAD

**Issue by sophieH29** [microsoft/fluent-ui-react#610]
### Steps
Let's ```componentA``` is derived from ```AutoControlled``` component

```componentA``` has state object
```js
state = {
    someState: true
}
```

And has autocontrolled state and props

```js

props = {
...
autoControlledState: bool
defaultAutoControlledState: bool
...
}
...
static autoControlledProps = ['autoControlledState']
...
```

Steps:
1. Use component 
```js
<componentA defaultAutoControlledState={true} />
```
2. Debug component
3. Check applied state to component

### Expected Result
Expected state is 
```js
state = {
    someState: true,
    autoControlledState: true
}
```

### Actual Result
```js
state = {
    someState: true,
}
```

As a result, ```state``` of the component is not taken into account in ```AutoControlled``` component. Then constructor of ```componentA``` overrides the state value with what was set in ```AutoControlled``` component during initialization.

**Comment by layershifter** [comment]
```js
class SomeComponent extends AutoControlledComponent {
  state = { someState: true }
}
// equals to:
class SomeComponent extends AutoControlledComponent {
  constructor(...args) {
    super(...args)
    console.log(this.state) // { autoControlledState: true }
    this.state = { someState: true }
  }
}

```

The `autoControlledState` variable is assigned inside `constructor()` of `AutoControlledComponent`, [AutoControlledComponent.tsx#L149](https://github.com/stardust-ui/react/blob/v0.15.0/src/lib/AutoControlledComponent.tsx#L149).

The `SomeComponent`'s constructor will be called after it and this means that it will simply reassign the `state` property 👎  More details on [StackOverflow](https://stackoverflow.com/a/43595944/6488546).

More historic details are there https://github.com/Semantic-Org/Semantic-UI-React/pull/1799. The solution is to disallow to use `state` property in components that extends `AutoControlledComponent`, but I don't see any transparent way to do this.
