### ISSUE TITLE
[RFC]: Colors - choosing text color for box components (where color props sets background color)

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#629]
### Problem description
We need to automatically change text color for box components (components where `color` prop goes to background color)

What tool to use for deciding text color for different background shades?

### Proposed solution
Use `color` package and `Color(bgColor).isDark` call to determine if the text is light or dark, but it looks like this is not a preferred package to import? see:
https://github.com/stardust-ui/react/pull/597#discussion_r241344252

**Comment by bmdalex** [comment]
**Q: How do we choose the shades of light and dark text colors?**

A: We need to:
- wait for designers to give us the right redlines for what text colors to use;
- we need to create more proposals and iterate on them, @levithomason would be great if you could summarize your thoughts on these proposals

**Comment by layershifter** [comment]
> We need to automatically change text color for box components

I think that we don't need to do something automatically, we should define mapping explicitly. As I see, described issue should be covered by #636.

**Comment by bmdalex** [comment]
closing as this is covered by #636 now
