### ISSUE TITLE
I am missing a checkbox component.

### ISSUE THREAD

**Issue by aichi** [microsoft/fluent-ui-react#634]
This feature request is to have a checkbox component which is having nicer styling than basic HTML checkbox element. It can look like as a toggle button. 

You can check how we implement it in Boolean renderer.

**Comment by mnajdova** [comment]
I see that SUIR has the Checkbox component: https://react.semantic-ui.com/modules/checkbox/ Are we talking about something like this? I think is reasonable that Stardust will support this in the future.

**Comment by aichi** [comment]
Yes, that's what I expect. I would need a toggle https://react.semantic-ui.com/modules/checkbox/#types-toggle
