### ISSUE TITLE
[RFC] Color prop for components where it can target multiple areas (content, background)

### ISSUE THREAD

**Issue by bmdalex** [microsoft/fluent-ui-react#636]
# [RFC] Color prop for components where it can target multiple areas (content, background)

## Problem description
Let's take the example of `Label` component. The `color` prop for a label can have at least 2 targets:
- the color of the text
- the color of the label's background

How should we create props for this type of components?

## Solution 1
Always pick an area that color goes to and change other colors using variables.

**e.g.:**
for `Label` component, the `color` prop changes the background color, and we're using `color` variable to change the text color:

### API:
```jsx
<Label color='red' variables={{ color: '#fff' }} />
```
will create a label with white text on red background.

**Note**: We should rename `color` variable to `textColor` to avoid confusion.

### +:
- simple solution

### -:
- `color` variable receives a CSS color and does not go through our color palette mechanism (we'd need to implement that)
- confusing that we use a prop and a variable to set colors for areas of the same component

## Solution 2
`color` prop receives an object as value in order to identify the area of the component it sets color for:

**e.g.:**
for `Label` component, the `color` prop changes the text and background colors, so we'd have something like this for the `color` prop:

```typescript
type LabelColorProp = {
  text: string
  background: string
} | string
```

### API:
```jsx
<Label color={{ text: 'red', background: 'green' }} />
```
will create a label with red text on green background.

```jsx
<Label color='red' />
```
will create a label with red text on background with default color.

### +:
- more intuitive than Solution 1
- leverages the color palette mechanism to get correct hex codes for colors

### -:
- complex API
- complex solution

## Solution 3
- always pick an area that color goes to
- change other area colors automatically or using a color scheme: https://github.com/stardust-ui/react/pull/558#discussion_r239333426
- accept overrides using variables

**e.g.:**
for `Label` component:
- the `color` prop changes the background color and determines what text color complements the text color **(same as [SUIR](https://react.semantic-ui.com/elements/label/#variations-colored))** based on a tool / predefined color scheme (see: https://github.com/stardust-ui/react/pull/558#discussion_r239333426)
- we're using `color` variable to override the text color set by `color` prop automatically when setting background color

### API
```jsx
<Label color='red' />
```
will create a label with light colored text that fits best on a red background color.
```jsx
<Label color='white' />
```
will create a label with dark colored text that fits best on a white background.

```jsx
<Label color='white' variables={{ color: 'yellow' }} />
```
will create a label with yellow text on white background.

### +:
- leverages the color palette mechanism to get correct hex codes for colors
- simple API

### -:
- complex solution
- error prone (wrong colors in scheme) and hard to maintain
- can get confusing since variables would override props, we can consider other override mechanisms

**Comment by bmdalex** [comment]
@levithomason 
@kuzhelov 
@mnajdova 
@layershifter 
@miroslavstastny 

can you guys express your thoughts?

**Comment by miroslavstastny** [comment]
From consumer's point of view I vote for Solution 3 - it's theme's responsibility to match correct foreground to the background.
More importantly, it's also up to the theme to decide what the `color` prop means - for one theme, it can mean to set background, for other theme to set border color...

**Comment by bmdalex** [comment]
Agreed, thanks @miroslavstastny 
### How would you handle overriders?

Let's say a user really wants to set a different color for foreground than the one set by `color` prop, while maintaining the background color set by `color` prop. How would that work?

## Solution 1
One idea is to make color related `variables` higher priority than `color` prop and retain the existing variables as some default values;

**e.g.**
```jsx
<Label  />
```
creates a label with grey text on light grey background (default)
![screenshot 2018-12-19 at 17 19 32](https://user-images.githubusercontent.com/5442794/50229181-64b29d00-03b2-11e9-915d-74f8aae49af2.png)

```jsx
<Label color='red'  />
```
creates a label with very light text on red background
![screenshot 2018-12-19 at 17 20 00](https://user-images.githubusercontent.com/5442794/50229192-6a0fe780-03b2-11e9-95c8-1c6cdd6d3666.png)

```jsx
<Label color='red' variables={{ color: 'yellow' }} />
```
creates a label with yellow text (override) on red background.
![screenshot 2018-12-19 at 17 20 20](https://user-images.githubusercontent.com/5442794/50229204-7005c880-03b2-11e9-9340-9b7764420e8d.png)

## Solution 2
Another idea is not to handle this at all and the user can just use color variables for this case and omit `color` prop entirely:

```jsx
<Label color='red' variables={{ color: 'yellow', backgroundColor: 'red' }} />
```
creates a label with yellow text (override) on red background.
![screenshot 2018-12-19 at 17 20 20](https://user-images.githubusercontent.com/5442794/50229204-7005c880-03b2-11e9-9340-9b7764420e8d.png)

### Note:
For this to work we need to introduce the color palette mechanism for color variables values as well, what do you think? @layershifter

**Comment by layershifter** [comment]
### What does Bootstrap?

https://getbootstrap.com/docs/4.1/components/alerts/#examples
![image](https://user-images.githubusercontent.com/14183168/50281515-f7ede000-044f-11e9-8850-1c7c9df5ff5b.png)

### What does SUI?

https://semantic-ui.com/collections/message.html
![image](https://user-images.githubusercontent.com/14183168/50281560-1ce25300-0450-11e9-8693-6f893606c27d.png)

### What does Bulma?

https://bulma.io/documentation/elements/notification/
![image](https://user-images.githubusercontent.com/14183168/50281604-4d29f180-0450-11e9-91b5-dc69fde2416e.png)

**Comment by layershifter** [comment]
I will vote for **Solution 1**. We need to create a color schema and allow define its parts via variables, this looks like nearest Starbucks 😺

**Comment by bmdalex** [comment]
@layershifter - thanks for the input

#### How would you see this color schema work for a `Label` let's say where the `color` prop needs to color both `background` and `textColor` / `foreground` (whatever we want to refer to it as)?

According to your comment about what other libraries do (https://github.com/stardust-ui/react/issues/636#issuecomment-448960412) we might want:
```jsx
<Label color="red" />
```

to create one of these (or whatever the theme wants for the exact shades):

| a `Label` with light `textColor` on darker red `background` ([SUI](https://semantic-ui.com/elements/label.html)) | a `Label` with darker `textColor` on lighter red `background` ([Bootstrap](https://getbootstrap.com/docs/4.1/components/alerts/#examples)) |
|    :---:     |     :---:     |
| ![screenshot 2018-12-20 at 14 52 41](https://user-images.githubusercontent.com/5442794/50286341-be28d380-0467-11e9-830b-156c84bad6d9.png) | ![screenshot 2018-12-20 at 14 52 26](https://user-images.githubusercontent.com/5442794/50286357-caad2c00-0467-11e9-80ea-5a516f9eabcb.png) |

As I see it we might want to reuse our mapping for color variants and do something similar to what I did here:

https://github.com/stardust-ui/react/pull/647/files#r243257825
```typescript
colors: mapColorsToScheme(siteVars, colorVariants => ({
  color: colorVariants[50],
  backgroundColor: colorVariants[500],
})),
```
and use it to set styles.

#### However, it looks like this simple variant <-> color mapping is not generic enough for all colors; some of the variants for `background` (post orange, yellow) are too light to use the matching variant for `foreground` as you can see in the screenshot below:
![screenshot 2018-12-19 at 17 39 22](https://user-images.githubusercontent.com/5442794/50286436-02b46f00-0468-11e9-8b13-5a103d0abb46.png)

My question is:

#### Does this mean we need to define this color schema for every color or choose better variants? Any ideas to unblock this?

**Comment by layershifter** [comment]
> Does this mean we need to define this color schema for every color or choose better variants?

My opinion: some colors should be manually mapped (_if your palette is not great_ :) ), in development mode we can throw warning about unaccessible colors in scheme.

Can you capture a screenshot with a palette from default theme?

**Comment by bmdalex** [comment]
Here's the screenshot (still not great for orange and yellow):

![screenshot 2018-12-20 at 17 15 53](https://user-images.githubusercontent.com/5442794/50292876-f2f25600-047a-11e9-871c-b48548fa3258.png)

> some colors should be manually mapped (if your palette is not great :) )

1. Do we really want to do all this manually?
2. Would it be at component level?

What about defining a foreground and background colors that works for any of the variants for each color? At least it's less work... Something like:

```typescript
export const naturalColors = {
  // ...,
  postOrange: {
    50: '#FDF6F7',
    100: '#FBF2F3',
    200: '#FAEEEF',
    300: '#F9ECED',
    400: '#F8E9EA',
    500: '#F7E5E6',
    600: '#F7E2E4',
    700: '#F5DEE0',
    800: '#F5DBDD',
    900: '#F3D6D8',
    foreground: '#???', // some hex code that works as foreground for any variant
    background: '#???', // some hex code that works as background for any variant
  },
}
```

**Comment by layershifter** [comment]
> 2. Would it be at component level?

At theme level. As I remember there has been already discussion about it and we decided to have a basic scheme on theme level and extend it in components if there will be need.

**Comment by bmdalex** [comment]
> At theme level. As I remember there has been already discussion about it and we decided to have a basic scheme on theme level and extend it in components if there will be need.

@layershifter 

I attempted to implemented a generic color scheme at theme level that is used only for Label now, can you take a look on the PR #647 , please?

here's the commit:
https://github.com/stardust-ui/react/pull/647/commits/43cc49680b90e555b9df08de5021420984a9ac60

### Color Scheme attempt screenshots:

#### Teams Theme
![screenshot 2018-12-21 at 14 28 47](https://user-images.githubusercontent.com/5442794/50342890-a156d380-052d-11e9-87a7-7b610539aabc.png)

#### Default Theme
![screenshot 2018-12-21 at 14 31 29](https://user-images.githubusercontent.com/5442794/50342878-9734d500-052d-11e9-9613-d1d18c02b613.png)
