### ISSUE TITLE
Async Popup doesn't update position and alignment

### ISSUE THREAD

**Issue by joheredi** [microsoft/fluent-ui-react#641]
## Bug Report
When Popup content is loaded asynchronously and it needs to expand, Popup grows in a direction that no longer honors position and alignment

![asyncpopup](https://user-images.githubusercontent.com/21109913/50186898-28f3d680-02d1-11e9-83c0-84706ed7e57b.gif)

### Steps
```jsx
import React from 'react'
import { Button, Popup, Segment } from '@stardust-ui/react'

const Component = () => <Segment styles={{minHeight: "300px"}}>Hello World</Segment>

const PopupExample = () => <Popup position="above" align="top" trigger={<Button icon="expand" />} content={{content: <AsyncData data={<Component />} />}} />

const render = data => {
  return !data ? "...loading" : data;
}

class AsyncData extends React.Component<{ render: Function; data?: any }> {
  state = { loading: true }

  componentDidMount() {
    setTimeout(() => { 
      console.log("TimedOut")
      this.setState({loading: false})
      
    }, 1000 )
  }

  public render() {
    const { loading } = this.state
    const { data } = this.props
    return loading ? "loading" : data
  }
} 

export default PopupExample
```

### Expected Result
After content is loaded and Popup resized, it should maintain its position and alignment

### Actual Result
Doesn't maintain position and alignment

### Version
0.15.0

**Comment by johannao76** [comment]
This is a big problem for @mentions and emojis as for these the popup needs to dynamically change height and the popup needs to stay anchored at its original location.

**Comment by johannao76** [comment]
This issue is still happening in the latest build.

**Comment by layershifter** [comment]
Did you tried solution from #705?
