### ISSUE TITLE
Expose accessibility in createComponent public API

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#655]
## Feature Request

Consumers need to be able to pass a behavior object as `accessibility` in the `createComponent` public API and retrieve the `accessibility` prop in their `render` method .

### Problem description

Following code should wrap the rendered CustomComponent in a focus zone:
```
const CustomComponent = createComponent<any>({
  displayName: "CallingHeader",
  render: ({ accessibility }) => 
...

<customComponent
        accessibility= () => ({focusZone: true})
/>
```

**Comment by layershifter** [comment]
Fixed in #714.
