### ISSUE TITLE
Expose `styles` in createComponent public API

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluent-ui-react#664]
### Problem description
To compose `createComponent` with standard Stardust components (render Stardust component inside `createComponent`) it is not allowed to pass css-in-js classes to the Stardust component, styles must be used instead (#467).

### Proposed solution
Add `styles` to `createComponent` so that it is possible to pass styles to Stardust component

**Comment by layershifter** [comment]
Fixed in #714.
