### ISSUE TITLE
Make Menu API less error prone

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#665]
## Feature Request

It is very easy to create a Menu component structure that does not work correctly.

### Problem description
1. Children API is still possible even if the doc site states that it is not supported
2. When items are passed as shorthand in Menu, they are not always rendered correctly:
- `<Menu items={[ <div>Random Text </div> ]} />`
- `<Menu items={[ () =><div>Random Text </div> ]} />`
3. When MenuItems are passed as shorthand in Menu, similar to 
`<Menu items={[ <MenuItem ... /> ]} />`

### Proposed solution
- do not render `props.children` in `Menu` component, only `items`, error/exception when children is not empty
- always treat `items` array members as shorthand (as if the user would have passed them in `{ content: <div>...</div>)
- fail if `MenuItem` is passed as an item

Alternatively, consider using context to pass required information from  `Menu` to `MenuItem`

**Comment by levithomason** [comment]
If consumers use children, all implementation is up to them.  That is not a problem we are currently solving.

We now place JSX shorthand as children to the shorthand slot component, this solves the `div` case above.

The function case is intentionally meant to circumvent the shorthand creation, so again the user needs to construct the proper components there.  We hand off the component and props for them if they choose that API.
