### ISSUE TITLE
[RFC] Loader (Spinner)

### ISSUE THREAD

**Issue by ydogandjiev** [microsoft/fluent-ui-react#666]
## Feature Request
Startdust needs a progress indicator control (e.g. spinner and/or progress bar) that can be used to indicate to users that the app or some subset of its UI is loading.

### Problem description
I'm trying to migrate my app over from the Office UI Fabric to Stardust and have so far been unable to find a replacement for the Spinner control:
https://developer.microsoft.com/en-us/fabric#/components/spinner

I considered animating the refresh icon to create something that looks like a spinner but that doesn't seem to be a good long term solution.

### Proposed solution
Provide a basic Spinner control as part of the Stardust component library.

**Comment by levithomason** [comment]
Thanks for the notice.  We do need two components for this.

### Progress

A stateful progress bar component.  Reference: https://react.semantic-ui.com/modules/progress

### Loader

A stateless animated component for indicating something is loading.  Reference: https://react.semantic-ui.com/elements/loader.

>Note we call this a "Loader" as it is not required to "spin" in all themes.  Some theme may have a different animation.

**Comment by jurokapsiar** [comment]
Let's use this issue for Loader (Spinner). It is also needed to accomplish the Dropdown loading state. I have created #681 for the progress bar.

**Comment by levithomason** [comment]
Loader is in progress at #685
