### ISSUE TITLE
[RFC] Menu separator (vertical and horizontal)

### ISSUE THREAD

**Issue by joheredi** [microsoft/fluent-ui-react#667]
## Feature Request
Implement Vertical Divider
### Problem description
Stardust already provides a [horizontal divider](https://stardust-ui.github.io/react/components/divider), however, it lacks a vertical divider. Supporting a "vertical" prop would come in handy. For instance to separate menu items in toolbars

**Comment by jurokapsiar** [comment]
Renamed the issue to specifically address menu. Creating a standalone vertical separator might or might not be a prerequisite.
