### ISSUE TITLE
Docsite: initial knobs state ignored 

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluent-ui-react#668]
### Steps
In Docsite check an example with knobs, (ItemLayout/Truncate).

### Expected Result
The example behaves according to knobs

### Actual Result
Knobs state is ignored until it is touched 💣
In the screenshot below, both header and content text should be truncated but knobs attribute passed to the example is empty object. 
![image](https://user-images.githubusercontent.com/9615899/50583747-6167e880-0e6b-11e9-8122-14b19449aa41.png)

### Version
0.15.0

### Testcase
https://stardust-ui.github.io/react/components/item-layout#variations-truncate

**Comment by layershifter** [comment]
```diff
componentWillMount() {
   this.setState({
+    knobs: this.getKnobsValue(),
   })
}
```

This change will fix the issue 👍
