### ISSUE TITLE
Remove references to Segoe Font in Stardust

### ISSUE THREAD

**Issue by hughreeling** [microsoft/fluent-ui-react#692]
### Problem description
Currently have hard coded references to westeuropean version of segoe fonts from sharepoint servers.

If users want other regional characters, then these aren't available.

### Proposed solution
Base themes, and stardust itself to use standard browser fonts.

### MVP
[Fork, update, and replace this pen if you can show the proposed solution]:
https://codesandbox.io/s/2l3n74j9y

**Comment by layershifter** [comment]
See https://github.com/stardust-ui/react/pull/859#issuecomment-461504646 ✌️
