### ISSUE TITLE
Remove isFromKeyboard in favor of :focus-visible

### ISSUE THREAD

**Issue by levithomason** [microsoft/fluent-ui-react#749]
### Problem description
IsFromKeyboard is not like the other states. It requires runtime style compilation. We cannot iterate over the style functions and produce stylesheets due to the presence of this runtime state value. 

We could opt to transform this state into a special class name and require consumers to use isFromKeyboard to apply the class name to their own components, but this is complicated and awkward. 

### Proposed solution
There is a :focus-visible spec that only applies styles on focus from keyboard. There is also an official polyfill. We should investigate this spec compliant future proof selector. It will allow us to iterate style functions without a runtime necessary. 

https://css-tricks.com/keyboard-only-focus-styles
https://github.com/WICG/focus-visible

**Comment by layershifter** [comment]
```html
    /*
      TODO: this could solve the isFromKeyboard and onFocus complication.
            Need to work out how we integrate this static style into style functions.
    [data-whatinput="mouse"] *:focus {
      outline: none !important;
    }
    [data-whatinput="keyboard"] *:focus {
      outline: 2px solid red !important;
      outline-offset: -2px;
      z-index: 1;
    }
    */
```

Other option is to use global selector to disable styles when input device is a mouse.

**Comment by jurokapsiar** [comment]
@layershifter had another idea - to use fela enhancers and allow global prefix in the selectors: https://codesandbox.io/s/young-dust-fy3b0

taking this one step further, we can have an enhancer that will allow us to do:

```
const buttonRule = () => ({
  background: "green",

  ":focus": {
    backgroundColor: "red",

    ':focus-visible': {
      backgroundColor: "orange"
    }
  }
});
```

or something similar

**Comment by notandrew** [comment]
fixed
