### ISSUE TITLE
RTL examples are not tested with screener

### ISSUE THREAD

**Issue by mnajdova** [microsoft/fluent-ui-react#757]
### Problem description
We don't have any screen tests for the RTL examples. We may break some of the RTL functionalities without noticing.

### Proposed solution
We can mark some examples that are RTL representative and test them with RTL applied. This will allow us to catch any RTL related regressions on our PRs.

**Comment by miroslavstastny** [comment]
See related PR #98 for some additional comments.

**Comment by layershifter** [comment]
Fixed in #792.
