### ISSUE TITLE
Dropdown align auto controlled props with Downshift

### ISSUE THREAD

**Issue by silviuaavram** [microsoft/fluent-ui-react#791]
For example, Downshift has `highlightedIndex`, `defaultHighlightedIndex` and `initialHighlightedIndex`. In order to expose `highlightedIndex` as Dropdown autocontrolled prop, some mapping needs to be done between that and the one in Downshift.

Also, `default` is something we consider as `initial` as far as Downshift is concerned.

Follow up from https://github.com/stardust-ui/react/pull/726

**Comment by bmdalex** [comment]
Also we should make `isOpen` and `defaultIsOpen` auto controlled props as we started using the flag internally in #786

**Comment by jurokapsiar** [comment]
Closing, according to @silviuavram "we will continue to have different behavior with initial and default in Downshift and Dropdown"
