### ISSUE TITLE
Single selection dropdown opens when the user clicks on the text or on the toggle button only

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#810]
### Steps
open http://localhost:8080/maximize/dropdown-example-single-selection-shorthand/false
click on the Select your hero title, on the toggle button and then between these two.

### Expected Result
Dropdown should open when the user clicks on it, not only on the title/toggle.

### Actual Result
Dropdown does not open when the user clicks between the title and the toggle.

**Comment by layershifter** [comment]
Now it works as expected:

![dropdown-click](https://user-images.githubusercontent.com/14183168/54821120-00052800-4caa-11e9-9145-bb796367e6ab.gif)
