### ISSUE TITLE
Dialog: add aria-attributes

### ISSUE THREAD

**Issue by layershifter** [microsoft/fluent-ui-react#812]
## Feature Request

Also, would it be possible to allow adding aria-labelledby (which needs an ID reference to the header)?
The logic should be:
- by default, generate `aria-labelledby`
- if `aria-labelledby` provided by the user, use that instead
- if `aria-label` provided, do not generate `aria-labelledby`

For `aria-describedby` I would leave it fully on the consumer to provide correct referecne as not all dialogs have clear description.

https://github.com/stardust-ui/react/pull/790#discussion_r252560457

### Proposed solution
```jsx
const getAriaLabeledBy = (props) => {
  if (props['aria-labelledby']) return props['aria-labelledby']
  if (typeof props.header === 'string' && props.header.id) return props.header.id
  
  return _.uniqid('dialog') // PREFIX
}
```

But, I'm not happy with it, to complex for one prop.

**Comment by jurokapsiar** [comment]
Don't agree with the aria-describedby part. According to ARIA:

```Optionally, the aria-describedby property is set on the element with the dialog role to indicate which element or elements in the dialog contain content that describes the primary purpose or message of the dialog```

If we put the logic inside of a behavior, we can have two variants of them - one that handles just label and another one that handles both label and description.
I would make the second one default and the first one (with just label) optional alternative.
