### ISSUE TITLE
Set all the text in white color when using teamsDark theme 

### ISSUE THREAD

**Issue by vini-gupta** [microsoft/fluent-ui-react#848]
## Feature Request
We need to ensure all text is render in white color when we are using teamsDark theme at the parent level.

### Problem description
Presently the Segment component has its color property set to 'black' by default which is overriding the color property coming from the teamsDark theme. 

### Proposed solution
All Stardust components should verify the theme provided before applying color property to its child components.

![image](https://user-images.githubusercontent.com/47372422/52313345-055d1c00-2963-11e9-8a32-77029858045e.png)

**Comment by layershifter** [comment]
`Segment` doesn't have proper styles for Dark and HC themes. It was fixed in #1014 as side-effect by usage `siteVariables.bodyColor`.

**Comment by layershifter** [comment]
### Teams theme

![image](https://user-images.githubusercontent.com/14183168/53812280-d044e900-3f63-11e9-9ed5-9633f217a4e9.png)

### Teams Dark theme

![image](https://user-images.githubusercontent.com/14183168/53812304-ddfa6e80-3f63-11e9-8c54-a2b9a191376c.png)

### Teams HC

![image](https://user-images.githubusercontent.com/14183168/53812315-e783d680-3f63-11e9-8c1c-8b31bc5ba6cf.png)
