### ISSUE TITLE
feat(screener): customise command to accept parameter for test file(s)

### ISSUE THREAD

**Issue by silviuaavram** [microsoft/fluent-ui-react#860]
## Feature Request

Right now we run `yarn test:visual` and it runs all the tests. These tests take a while to run, so for speeding things up when developing tests locally, we can make the command to accept parameter for a test file/a range of test files (a regexp), which will be passed to `glob.sync` in `screener.config.js` (or something similar).

**Comment by layershifter** [comment]
Was fixed in #980.
