### ISSUE TITLE
Loader needs a delay property

### ISSUE THREAD

**Issue by johannao76** [microsoft/fluent-ui-react#888]
### Problem description
In some cases, loading happens immediately, in which case, we don't want the loading spinner to be rendered at all.

### Proposed solution
Add a delay property to the Loader component to indicate how long to wait before showing it

**Comment by layershifter** [comment]
`delay` prop exists in:
- https://ant.design/components/spin/
- https://evergreen.segment.com/components/spinner/
- https://www.lightningdesignsystem.com/components/spinners/
- https://atlaskit.atlassian.com/packages/core/spinner

It doesn't changes the behavior of the component and can be safely implemented.
