### ISSUE TITLE
feat(Dropdown): close list when the searchQuery is cleared

### ISSUE THREAD

**Issue by silviuaavram** [microsoft/fluent-ui-react#904]
When the search query is emptied, the list should be able to be closed, instead of just showing the `noItemsMessage`.

**Comment by bmdalex** [comment]
This does not seem to be the current behavior. When we clear the search query the full list of options is just restored. Looks ok to me and more intuitive than autoclosing the list.

Anything I'm missing? @silviuavram @jurokapsiar 

fyi @layershifter 
![Screen Recording 2019-03-25 at 17 20 06](https://user-images.githubusercontent.com/5442794/54936285-77dd8780-4f22-11e9-94e3-32341dfe9114.gif)

**Comment by silviuaavram** [comment]
Sorry, my fault. When emptying the input, it was showing all the items. Instead, it should close it, unless opened by toggle or other means.

**Comment by bmdalex** [comment]
fyi @layershifter
