### ISSUE TITLE
Text color of timestamp in mine message should be gray02 (#484644)

### ISSUE THREAD

**Issue by jurokapsiar** [microsoft/fluent-ui-react#924]
### Steps
Open Chat component doc site, obsere the color of the timestamp in "mine" message.

### Expected Result
It needs to be gray02 (484644)

### Actual Result
Currently it is 979593

**Comment by codepretty** [comment]
We want different timestamp colors for messages sent from me vs sent from others. We should keep 979593 for timestamps on messages from others and only change the color of timestamp messages sent from me to 484644.

**Comment by mnajdova** [comment]
@codepretty can you suggest which color should be used on hover? With these changes, the color on mine messages would be the same on hover...
