### ISSUE TITLE
RTL Provider breaks styles

### ISSUE THREAD

**Issue by miroslavstastny** [microsoft/fluent-ui-react#948]
### Steps
```jsx
const buttonStyles = {
    borderLeftColor: 'red',
    borderLeftWidth: '5px',
}

const outerRtl = true
const innerRtl = true

export default () => (
        <Provider theme={mergeThemes(themes.teams, {rtl:outerRtl})}>
            <div>
                <Button content={`outer rtl=${outerRtl.toString()}`} styles={buttonStyles} primary />
                <Provider theme={mergeThemes(themes.teams, {rtl: innerRtl})}>
                    <Button content={`inner rtl=${innerRtl.toString()}`} styles={buttonStyles} primary />
                </Provider>
            </div>
        </Provider>
)
```

### Expected Result
Correctly works for all combinations of `outerRtl` and `innerRtl`

### Actual Result
Results, differ, also depends on `devMode` in `felaRenderer` 💣

#### `devMode: true`
![localhost_3000_](https://user-images.githubusercontent.com/9615899/53242100-17012c00-36a4-11e9-832c-5937b2398870.png)
![localhost_3000_ 1](https://user-images.githubusercontent.com/9615899/53242128-26807500-36a4-11e9-8630-03ecd442ef0e.png)
![localhost_3000_ 2](https://user-images.githubusercontent.com/9615899/53242211-65aec600-36a4-11e9-8413-eb20c3d0cecd.png)
![localhost_3000_ 3](https://user-images.githubusercontent.com/9615899/53242133-2a13fc00-36a4-11e9-8b28-505ec596846e.png)

With inner provider completely removed:

![localhost_3000_ 10](https://user-images.githubusercontent.com/9615899/53242144-3304cd80-36a4-11e9-9c81-26e39f5a9f17.png)
![localhost_3000_ 11](https://user-images.githubusercontent.com/9615899/53242154-36985480-36a4-11e9-8e85-c9ec7f903580.png)

#### `devMode: false`
![localhost_3000_ 4](https://user-images.githubusercontent.com/9615899/53242256-8ecf5680-36a4-11e9-8065-e79634a5fe56.png)
![localhost_3000_ 5](https://user-images.githubusercontent.com/9615899/53242258-9131b080-36a4-11e9-924a-9d15dae57d65.png)
![localhost_3000_ 6](https://user-images.githubusercontent.com/9615899/53242260-942ca100-36a4-11e9-9257-7cfaf9d5a60e.png)
![localhost_3000_ 7](https://user-images.githubusercontent.com/9615899/53242265-968efb00-36a4-11e9-86c7-96841e090705.png)

With inner provider completely removed:
![localhost_3000_ 8](https://user-images.githubusercontent.com/9615899/53242292-a6a6da80-36a4-11e9-996e-d193dde6e822.png)
![localhost_3000_ 9](https://user-images.githubusercontent.com/9615899/53242295-a8709e00-36a4-11e9-812a-dd144670f8c3.png)

### Version
0.21.1
Chrome 72.0.3626.109 Mac

**Comment by miroslavstastny** [comment]
**The problem with smaller fonts (`outerRtl: true`, `innerRtl: true`)**
Static styles are applied on LTR fela renderer. When that renderer is not used anywhere on the page, static styles are not applied 💣

**Comment by miroslavstastny** [comment]
**The problem with styles not being applied in (`devMode: true`, `outerRtl: true`, `innerRtl: false`)**
We use `rendererId: 'rtl'` for RTL Fela renderer but leave `rendererId` `undefined` for LTR.
If you create RTL Fela renderer first and then the LTR one, it breaks 💣

Workaround: use `rendererId: 'ltr'` for LTR Fela renderer.
@layershifter AFAIK you implemented rendererId in Fela, could you please check this?

**Comment by miroslavstastny** [comment]
**The problem with smaller height of outer button (`devMode: false`, `outerRtl: true`, `innerRtl: false`)**
This is a consequence of https://github.com/stardust-ui/react/issues/948#issuecomment-466402378 - when calculating `height: pxToRem(32)` for the outer button, static styles are not applied, html font size is 16px instead of 10px (which should be set by static styles) thus height is set to 2rem instead of 3.2rem (and later when LTR provider is rendered, static styles are applied which make the button lower).

**Comment by layershifter** [comment]
> If you create RTL Fela renderer first and then the LTR one, it breaks 💣

A valid issue, going to track it on the Fela side.

UPD: https://github.com/rofrischmann/fela/pull/681
