### ISSUE TITLE
Doc Site layout broken

### ISSUE THREAD

**Issue by bcalvery** [microsoft/fluent-ui-react#977]
In the Stardust Documentation the component example widths are seemingly random, off center, and being hidden behind the left nav.

![image](https://user-images.githubusercontent.com/15043460/53454911-ac225e80-39dd-11e9-9b71-589d751f25cd.png)
![image](https://user-images.githubusercontent.com/15043460/53454965-d96f0c80-39dd-11e9-83a4-586062f513c1.png)

**Comment by kuzhelov** [comment]
these regressions had happened as part of our transitioning towards not using static styles of Semantic UI in our docs - we are working on addressing them
